// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: admin_overview.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countAdminTraces = `-- name: CountAdminTraces :one
SELECT COUNT(*)::bigint AS trace_count
FROM traces
WHERE last_request_at >= $1::timestamp
  AND last_request_at < $2::timestamp
  AND ($3::bigint IS NULL OR user_id = $3::bigint)
`

type CountAdminTracesParams struct {
	StartAt pgtype.Timestamp `json:"startAt"`
	EndAt   pgtype.Timestamp `json:"endAt"`
	UserID  pgtype.Int8      `json:"userId"`
}

func (q *Queries) CountAdminTraces(ctx context.Context, arg CountAdminTracesParams) (int64, error) {
	row := q.db.QueryRow(ctx, countAdminTraces, arg.StartAt, arg.EndAt, arg.UserID)
	var trace_count int64
	err := row.Scan(&trace_count)
	return trace_count, err
}

const countAdminTracesFiltered = `-- name: CountAdminTracesFiltered :one
SELECT COUNT(*)::bigint AS trace_count
FROM traces t
WHERE t.last_request_at >= $1::timestamp
  AND t.last_request_at < $2::timestamp
  AND ($3::bigint IS NULL OR t.user_id = $3::bigint)
  AND EXISTS (
    SELECT 1
    FROM request r
    WHERE r.parent_span_id = t.parent_span_id
      AND r.user_id = t.user_id
      AND r.created_at >= t.first_request_at
      AND r.created_at <= t.last_request_at
      AND r.type = 1
      AND ($4::text IS NULL OR r.model = $4::text)
      AND ($5::text IS NULL OR r.upstream_model = $5::text)
      AND ($6::int IS NULL OR r.provider_id = $6::int)
  )
`

type CountAdminTracesFilteredParams struct {
	StartAt       pgtype.Timestamp `json:"startAt"`
	EndAt         pgtype.Timestamp `json:"endAt"`
	UserID        pgtype.Int8      `json:"userId"`
	Model         pgtype.Text      `json:"model"`
	UpstreamModel pgtype.Text      `json:"upstreamModel"`
	ProviderID    pgtype.Int4      `json:"providerId"`
}

func (q *Queries) CountAdminTracesFiltered(ctx context.Context, arg CountAdminTracesFilteredParams) (int64, error) {
	row := q.db.QueryRow(ctx, countAdminTracesFiltered,
		arg.StartAt,
		arg.EndAt,
		arg.UserID,
		arg.Model,
		arg.UpstreamModel,
		arg.ProviderID,
	)
	var trace_count int64
	err := row.Scan(&trace_count)
	return trace_count, err
}

const getAdminOverviewSpeedBoxplot = `-- name: GetAdminOverviewSpeedBoxplot :many
WITH speeds AS (
  SELECT
    CASE $1::text
      WHEN 'user' THEN COALESCE(user_id::text, '')
      WHEN 'model' THEN COALESCE(model, '')
      WHEN 'upstreamModel' THEN COALESCE(upstream_model, '')
      WHEN 'provider' THEN COALESCE(provider_id::text, '')
      ELSE ''
    END AS group_key,
    output_tokens::float8 / ((time_spent_ms - ttft_ms)::float8 / 1000.0) AS decode_speed
  FROM request
  WHERE type = 1
    AND status = 2
    AND created_at >= $2::timestamp
    AND created_at < $3::timestamp
    AND ($4::bigint IS NULL OR user_id = $4::bigint)
    AND output_tokens >= 50
    AND ttft_ms IS NOT NULL
    AND time_spent_ms IS NOT NULL
    AND (time_spent_ms - ttft_ms) >= 500
    AND ($5::text IS NULL OR model = $5::text)
    AND ($6::text IS NULL OR upstream_model = $6::text)
    AND ($7::int IS NULL OR provider_id = $7::int)
)
SELECT
  group_key,
  MIN(decode_speed)::float8 AS min_speed,
  percentile_cont(0.25) WITHIN GROUP (ORDER BY decode_speed)::float8 AS p25_speed,
  percentile_cont(0.5) WITHIN GROUP (ORDER BY decode_speed)::float8 AS median_speed,
  percentile_cont(0.95) WITHIN GROUP (ORDER BY decode_speed)::float8 AS p95_speed,
  GREATEST(
    percentile_cont(0.99) WITHIN GROUP (ORDER BY decode_speed),
    percentile_cont(0.5) WITHIN GROUP (ORDER BY decode_speed) * 3
  )::float8 AS max_speed,
  COUNT(*)::bigint AS request_count
FROM speeds
GROUP BY group_key
ORDER BY median_speed DESC, max_speed DESC, group_key ASC
`

type GetAdminOverviewSpeedBoxplotParams struct {
	Dimension     string           `json:"dimension"`
	StartAt       pgtype.Timestamp `json:"startAt"`
	EndAt         pgtype.Timestamp `json:"endAt"`
	UserID        pgtype.Int8      `json:"userId"`
	Model         pgtype.Text      `json:"model"`
	UpstreamModel pgtype.Text      `json:"upstreamModel"`
	ProviderID    pgtype.Int4      `json:"providerId"`
}

type GetAdminOverviewSpeedBoxplotRow struct {
	GroupKey     string  `json:"groupKey"`
	MinSpeed     float64 `json:"minSpeed"`
	P25Speed     float64 `json:"p25Speed"`
	MedianSpeed  float64 `json:"medianSpeed"`
	P95Speed     float64 `json:"p95Speed"`
	MaxSpeed     float64 `json:"maxSpeed"`
	RequestCount int64   `json:"requestCount"`
}

func (q *Queries) GetAdminOverviewSpeedBoxplot(ctx context.Context, arg GetAdminOverviewSpeedBoxplotParams) ([]GetAdminOverviewSpeedBoxplotRow, error) {
	rows, err := q.db.Query(ctx, getAdminOverviewSpeedBoxplot,
		arg.Dimension,
		arg.StartAt,
		arg.EndAt,
		arg.UserID,
		arg.Model,
		arg.UpstreamModel,
		arg.ProviderID,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAdminOverviewSpeedBoxplotRow
	for rows.Next() {
		var i GetAdminOverviewSpeedBoxplotRow
		if err := rows.Scan(
			&i.GroupKey,
			&i.MinSpeed,
			&i.P25Speed,
			&i.MedianSpeed,
			&i.P95Speed,
			&i.MaxSpeed,
			&i.RequestCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAdminOverviewTokenBreakdown = `-- name: GetAdminOverviewTokenBreakdown :one
SELECT
  COALESCE(SUM(input_tokens), 0)::bigint           AS input_tokens,
  COALESCE(SUM(cache_read_tokens), 0)::bigint      AS cache_read_tokens,
  COALESCE(SUM(cache_write_tokens), 0)::bigint     AS cache_write_tokens,
  COALESCE(SUM(cache_write_1h_tokens), 0)::bigint  AS cache_write_1h_tokens,
  COALESCE(SUM(output_tokens), 0)::bigint          AS output_tokens
FROM request_overview_bucketed
WHERE bucket_at >= $1::timestamp
  AND bucket_at < $2::timestamp
  AND ($3::bigint IS NULL OR user_id = $3::bigint)
  AND ($4::text IS NULL OR model = $4::text)
  AND ($5::text IS NULL OR upstream_model = $5::text)
  AND ($6::int IS NULL OR provider_id = $6::int)
`

type GetAdminOverviewTokenBreakdownParams struct {
	StartAt       pgtype.Timestamp `json:"startAt"`
	EndAt         pgtype.Timestamp `json:"endAt"`
	UserID        pgtype.Int8      `json:"userId"`
	Model         pgtype.Text      `json:"model"`
	UpstreamModel pgtype.Text      `json:"upstreamModel"`
	ProviderID    pgtype.Int4      `json:"providerId"`
}

type GetAdminOverviewTokenBreakdownRow struct {
	InputTokens        int64 `json:"inputTokens"`
	CacheReadTokens    int64 `json:"cacheReadTokens"`
	CacheWriteTokens   int64 `json:"cacheWriteTokens"`
	CacheWrite1hTokens int64 `json:"cacheWrite1hTokens"`
	OutputTokens       int64 `json:"outputTokens"`
}

func (q *Queries) GetAdminOverviewTokenBreakdown(ctx context.Context, arg GetAdminOverviewTokenBreakdownParams) (GetAdminOverviewTokenBreakdownRow, error) {
	row := q.db.QueryRow(ctx, getAdminOverviewTokenBreakdown,
		arg.StartAt,
		arg.EndAt,
		arg.UserID,
		arg.Model,
		arg.UpstreamModel,
		arg.ProviderID,
	)
	var i GetAdminOverviewTokenBreakdownRow
	err := row.Scan(
		&i.InputTokens,
		&i.CacheReadTokens,
		&i.CacheWriteTokens,
		&i.CacheWrite1hTokens,
		&i.OutputTokens,
	)
	return i, err
}

const getAdminOverviewTotals = `-- name: GetAdminOverviewTotals :one
WITH filtered AS (
  SELECT
    cost_currency,
    request_count,
    input_tokens,
    cache_read_tokens,
    output_tokens,
    cache_write_tokens,
    cache_write_1h_tokens,
    cost
  FROM request_overview_bucketed
  WHERE bucket_at >= $1::timestamp
    AND bucket_at < $2::timestamp
    AND ($3::bigint IS NULL OR user_id = $3::bigint)
    AND ($4::text IS NULL OR model = $4::text)
    AND ($5::text IS NULL OR upstream_model = $5::text)
    AND ($6::int IS NULL OR provider_id = $6::int)
), totals AS (
  SELECT
    COALESCE(SUM(
      input_tokens + cache_read_tokens + output_tokens + cache_write_tokens + cache_write_1h_tokens
    ), 0)::bigint AS total_tokens,
    COALESCE(SUM(request_count), 0)::bigint AS total_requests
  FROM filtered
), cost_groups AS (
  SELECT cost_currency AS currency, SUM(cost)::float8 AS amount
  FROM filtered
  WHERE cost_currency IS NOT NULL AND cost_currency <> ''
  GROUP BY cost_currency
), cost_json AS (
  SELECT COALESCE(
    jsonb_agg(
      jsonb_build_object('currency', currency, 'amount', amount)
      ORDER BY currency
    ),
    '[]'::jsonb
  )::jsonb AS costs
  FROM cost_groups
)
SELECT
  totals.total_tokens,
  totals.total_requests,
  cost_json.costs::jsonb AS costs
FROM totals CROSS JOIN cost_json
`

type GetAdminOverviewTotalsParams struct {
	StartAt       pgtype.Timestamp `json:"startAt"`
	EndAt         pgtype.Timestamp `json:"endAt"`
	UserID        pgtype.Int8      `json:"userId"`
	Model         pgtype.Text      `json:"model"`
	UpstreamModel pgtype.Text      `json:"upstreamModel"`
	ProviderID    pgtype.Int4      `json:"providerId"`
}

type GetAdminOverviewTotalsRow struct {
	TotalTokens   int64  `json:"totalTokens"`
	TotalRequests int64  `json:"totalRequests"`
	Costs         []byte `json:"costs"`
}

func (q *Queries) GetAdminOverviewTotals(ctx context.Context, arg GetAdminOverviewTotalsParams) (GetAdminOverviewTotalsRow, error) {
	row := q.db.QueryRow(ctx, getAdminOverviewTotals,
		arg.StartAt,
		arg.EndAt,
		arg.UserID,
		arg.Model,
		arg.UpstreamModel,
		arg.ProviderID,
	)
	var i GetAdminOverviewTotalsRow
	err := row.Scan(&i.TotalTokens, &i.TotalRequests, &i.Costs)
	return i, err
}

const listAdminOverviewBreakdownCosts = `-- name: ListAdminOverviewBreakdownCosts :many
SELECT
  COALESCE(user_id, 0)::bigint          AS user_id,
  COALESCE(model, '')::text             AS model,
  COALESCE(upstream_model, '')::text    AS upstream_model,
  COALESCE(provider_id, 0)::int         AS provider_id,
  cost_currency::text                    AS currency,
  SUM(cost)::float8                      AS amount
FROM request_overview_bucketed
WHERE bucket_at >= $1::timestamp
  AND bucket_at < $2::timestamp
  AND ($3::bigint IS NULL OR user_id = $3::bigint)
  AND ($4::text IS NULL OR model = $4::text)
  AND ($5::text IS NULL OR upstream_model = $5::text)
  AND ($6::int IS NULL OR provider_id = $6::int)
  AND cost_currency IS NOT NULL
  AND cost_currency <> ''
GROUP BY 1, 2, 3, 4, 5
`

type ListAdminOverviewBreakdownCostsParams struct {
	StartAt       pgtype.Timestamp `json:"startAt"`
	EndAt         pgtype.Timestamp `json:"endAt"`
	UserID        pgtype.Int8      `json:"userId"`
	Model         pgtype.Text      `json:"model"`
	UpstreamModel pgtype.Text      `json:"upstreamModel"`
	ProviderID    pgtype.Int4      `json:"providerId"`
}

type ListAdminOverviewBreakdownCostsRow struct {
	UserID        int64   `json:"userId"`
	Model         string  `json:"model"`
	UpstreamModel string  `json:"upstreamModel"`
	ProviderID    int32   `json:"providerId"`
	Currency      string  `json:"currency"`
	Amount        float64 `json:"amount"`
}

func (q *Queries) ListAdminOverviewBreakdownCosts(ctx context.Context, arg ListAdminOverviewBreakdownCostsParams) ([]ListAdminOverviewBreakdownCostsRow, error) {
	rows, err := q.db.Query(ctx, listAdminOverviewBreakdownCosts,
		arg.StartAt,
		arg.EndAt,
		arg.UserID,
		arg.Model,
		arg.UpstreamModel,
		arg.ProviderID,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAdminOverviewBreakdownCostsRow
	for rows.Next() {
		var i ListAdminOverviewBreakdownCostsRow
		if err := rows.Scan(
			&i.UserID,
			&i.Model,
			&i.UpstreamModel,
			&i.ProviderID,
			&i.Currency,
			&i.Amount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAdminOverviewBreakdownTokens = `-- name: ListAdminOverviewBreakdownTokens :many
SELECT
  COALESCE(user_id, 0)::bigint          AS user_id,
  COALESCE(model, '')::text             AS model,
  COALESCE(upstream_model, '')::text    AS upstream_model,
  COALESCE(provider_id, 0)::int         AS provider_id,
  SUM(
    input_tokens + cache_read_tokens + output_tokens + cache_write_tokens + cache_write_1h_tokens
  )::bigint AS total_tokens
FROM request_overview_bucketed
WHERE bucket_at >= $1::timestamp
  AND bucket_at < $2::timestamp
  AND ($3::bigint IS NULL OR user_id = $3::bigint)
  AND ($4::text IS NULL OR model = $4::text)
  AND ($5::text IS NULL OR upstream_model = $5::text)
  AND ($6::int IS NULL OR provider_id = $6::int)
GROUP BY 1, 2, 3, 4
HAVING SUM(
  input_tokens + cache_read_tokens + output_tokens + cache_write_tokens + cache_write_1h_tokens
) > 0
`

type ListAdminOverviewBreakdownTokensParams struct {
	StartAt       pgtype.Timestamp `json:"startAt"`
	EndAt         pgtype.Timestamp `json:"endAt"`
	UserID        pgtype.Int8      `json:"userId"`
	Model         pgtype.Text      `json:"model"`
	UpstreamModel pgtype.Text      `json:"upstreamModel"`
	ProviderID    pgtype.Int4      `json:"providerId"`
}

type ListAdminOverviewBreakdownTokensRow struct {
	UserID        int64  `json:"userId"`
	Model         string `json:"model"`
	UpstreamModel string `json:"upstreamModel"`
	ProviderID    int32  `json:"providerId"`
	TotalTokens   int64  `json:"totalTokens"`
}

func (q *Queries) ListAdminOverviewBreakdownTokens(ctx context.Context, arg ListAdminOverviewBreakdownTokensParams) ([]ListAdminOverviewBreakdownTokensRow, error) {
	rows, err := q.db.Query(ctx, listAdminOverviewBreakdownTokens,
		arg.StartAt,
		arg.EndAt,
		arg.UserID,
		arg.Model,
		arg.UpstreamModel,
		arg.ProviderID,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAdminOverviewBreakdownTokensRow
	for rows.Next() {
		var i ListAdminOverviewBreakdownTokensRow
		if err := rows.Scan(
			&i.UserID,
			&i.Model,
			&i.UpstreamModel,
			&i.ProviderID,
			&i.TotalTokens,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAdminOverviewCacheHitRateSeries = `-- name: ListAdminOverviewCacheHitRateSeries :many
SELECT
  bucket_at::timestamp AS bucket_at,
  CASE $1::text
    WHEN 'user' THEN COALESCE(user_id::text, '')
    WHEN 'model' THEN COALESCE(model, '')
    WHEN 'upstreamModel' THEN COALESCE(upstream_model, '')
    WHEN 'provider' THEN COALESCE(provider_id::text, '')
    ELSE ''
  END AS group_key,
  SUM(cache_read_tokens)::float8 AS cache_read_token_sum,
  SUM(input_tokens + cache_read_tokens + cache_write_tokens + cache_write_1h_tokens)::float8 AS input_token_sum
FROM request_overview_bucketed
WHERE bucket_at >= $2::timestamp
  AND bucket_at < $3::timestamp
  AND ($4::bigint IS NULL OR user_id = $4::bigint)
  AND ($5::text IS NULL OR model = $5::text)
  AND ($6::text IS NULL OR upstream_model = $6::text)
  AND ($7::int IS NULL OR provider_id = $7::int)
GROUP BY bucket_at, group_key
HAVING SUM(input_tokens + cache_read_tokens + cache_write_tokens + cache_write_1h_tokens) > 0
ORDER BY bucket_at ASC, group_key ASC
`

type ListAdminOverviewCacheHitRateSeriesParams struct {
	Dimension     string           `json:"dimension"`
	StartAt       pgtype.Timestamp `json:"startAt"`
	EndAt         pgtype.Timestamp `json:"endAt"`
	UserID        pgtype.Int8      `json:"userId"`
	Model         pgtype.Text      `json:"model"`
	UpstreamModel pgtype.Text      `json:"upstreamModel"`
	ProviderID    pgtype.Int4      `json:"providerId"`
}

type ListAdminOverviewCacheHitRateSeriesRow struct {
	BucketAt          pgtype.Timestamp `json:"bucketAt"`
	GroupKey          string           `json:"groupKey"`
	CacheReadTokenSum float64          `json:"cacheReadTokenSum"`
	InputTokenSum     float64          `json:"inputTokenSum"`
}

func (q *Queries) ListAdminOverviewCacheHitRateSeries(ctx context.Context, arg ListAdminOverviewCacheHitRateSeriesParams) ([]ListAdminOverviewCacheHitRateSeriesRow, error) {
	rows, err := q.db.Query(ctx, listAdminOverviewCacheHitRateSeries,
		arg.Dimension,
		arg.StartAt,
		arg.EndAt,
		arg.UserID,
		arg.Model,
		arg.UpstreamModel,
		arg.ProviderID,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAdminOverviewCacheHitRateSeriesRow
	for rows.Next() {
		var i ListAdminOverviewCacheHitRateSeriesRow
		if err := rows.Scan(
			&i.BucketAt,
			&i.GroupKey,
			&i.CacheReadTokenSum,
			&i.InputTokenSum,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAdminOverviewDistribution = `-- name: ListAdminOverviewDistribution :many
SELECT
  CASE $1::text
    WHEN 'user' THEN COALESCE(user_id::text, '')
    WHEN 'model' THEN COALESCE(model, '')
    WHEN 'upstreamModel' THEN COALESCE(upstream_model, '')
    WHEN 'provider' THEN COALESCE(provider_id::text, '')
    ELSE ''
  END AS key,
  SUM(
    input_tokens + cache_read_tokens + output_tokens + cache_write_tokens + cache_write_1h_tokens
  )::bigint AS total_tokens,
  SUM(request_count)::bigint AS request_count
FROM request_overview_bucketed
WHERE bucket_at >= $2::timestamp
  AND bucket_at < $3::timestamp
  AND ($4::bigint IS NULL OR user_id = $4::bigint)
  AND ($5::text IS NULL OR model = $5::text)
  AND ($6::text IS NULL OR upstream_model = $6::text)
  AND ($7::int IS NULL OR provider_id = $7::int)
GROUP BY key
ORDER BY total_tokens DESC, key ASC
`

type ListAdminOverviewDistributionParams struct {
	Dimension     string           `json:"dimension"`
	StartAt       pgtype.Timestamp `json:"startAt"`
	EndAt         pgtype.Timestamp `json:"endAt"`
	UserID        pgtype.Int8      `json:"userId"`
	Model         pgtype.Text      `json:"model"`
	UpstreamModel pgtype.Text      `json:"upstreamModel"`
	ProviderID    pgtype.Int4      `json:"providerId"`
}

type ListAdminOverviewDistributionRow struct {
	Key          string `json:"key"`
	TotalTokens  int64  `json:"totalTokens"`
	RequestCount int64  `json:"requestCount"`
}

func (q *Queries) ListAdminOverviewDistribution(ctx context.Context, arg ListAdminOverviewDistributionParams) ([]ListAdminOverviewDistributionRow, error) {
	rows, err := q.db.Query(ctx, listAdminOverviewDistribution,
		arg.Dimension,
		arg.StartAt,
		arg.EndAt,
		arg.UserID,
		arg.Model,
		arg.UpstreamModel,
		arg.ProviderID,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAdminOverviewDistributionRow
	for rows.Next() {
		var i ListAdminOverviewDistributionRow
		if err := rows.Scan(&i.Key, &i.TotalTokens, &i.RequestCount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAdminOverviewDistributionCosts = `-- name: ListAdminOverviewDistributionCosts :many
SELECT
  CASE $1::text
    WHEN 'user' THEN COALESCE(user_id::text, '')
    WHEN 'model' THEN COALESCE(model, '')
    WHEN 'upstreamModel' THEN COALESCE(upstream_model, '')
    WHEN 'provider' THEN COALESCE(provider_id::text, '')
    ELSE ''
  END AS key,
  cost_currency::text AS currency,
  SUM(cost)::float8 AS amount
FROM request_overview_bucketed
WHERE bucket_at >= $2::timestamp
  AND bucket_at < $3::timestamp
  AND ($4::bigint IS NULL OR user_id = $4::bigint)
  AND ($5::text IS NULL OR model = $5::text)
  AND ($6::text IS NULL OR upstream_model = $6::text)
  AND ($7::int IS NULL OR provider_id = $7::int)
  AND cost_currency IS NOT NULL
  AND cost_currency <> ''
GROUP BY key, currency
ORDER BY key ASC, currency ASC
`

type ListAdminOverviewDistributionCostsParams struct {
	Dimension     string           `json:"dimension"`
	StartAt       pgtype.Timestamp `json:"startAt"`
	EndAt         pgtype.Timestamp `json:"endAt"`
	UserID        pgtype.Int8      `json:"userId"`
	Model         pgtype.Text      `json:"model"`
	UpstreamModel pgtype.Text      `json:"upstreamModel"`
	ProviderID    pgtype.Int4      `json:"providerId"`
}

type ListAdminOverviewDistributionCostsRow struct {
	Key      string  `json:"key"`
	Currency string  `json:"currency"`
	Amount   float64 `json:"amount"`
}

func (q *Queries) ListAdminOverviewDistributionCosts(ctx context.Context, arg ListAdminOverviewDistributionCostsParams) ([]ListAdminOverviewDistributionCostsRow, error) {
	rows, err := q.db.Query(ctx, listAdminOverviewDistributionCosts,
		arg.Dimension,
		arg.StartAt,
		arg.EndAt,
		arg.UserID,
		arg.Model,
		arg.UpstreamModel,
		arg.ProviderID,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAdminOverviewDistributionCostsRow
	for rows.Next() {
		var i ListAdminOverviewDistributionCostsRow
		if err := rows.Scan(&i.Key, &i.Currency, &i.Amount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAdminOverviewSeriesMetrics = `-- name: ListAdminOverviewSeriesMetrics :many
SELECT
  bucket_at::timestamp AS bucket_at,
  CASE $1::text
    WHEN 'user' THEN COALESCE(user_id::text, '')
    WHEN 'model' THEN COALESCE(model, '')
    WHEN 'upstreamModel' THEN COALESCE(upstream_model, '')
    WHEN 'provider' THEN COALESCE(provider_id::text, '')
    ELSE ''
  END AS group_key,
  COALESCE(cost_currency, '')::text AS currency,
  SUM(input_tokens + cache_read_tokens + output_tokens + cache_write_tokens + cache_write_1h_tokens)::bigint AS tokens,
  SUM(request_count)::bigint AS requests,
  SUM(cost)::float8 AS cost
FROM request_overview_bucketed
WHERE bucket_at >= $2::timestamp
  AND bucket_at < $3::timestamp
  AND ($4::bigint IS NULL OR user_id = $4::bigint)
  AND ($5::text IS NULL OR model = $5::text)
  AND ($6::text IS NULL OR upstream_model = $6::text)
  AND ($7::int IS NULL OR provider_id = $7::int)
GROUP BY bucket_at, group_key, currency
ORDER BY bucket_at ASC, group_key ASC, currency ASC
`

type ListAdminOverviewSeriesMetricsParams struct {
	Dimension     string           `json:"dimension"`
	StartAt       pgtype.Timestamp `json:"startAt"`
	EndAt         pgtype.Timestamp `json:"endAt"`
	UserID        pgtype.Int8      `json:"userId"`
	Model         pgtype.Text      `json:"model"`
	UpstreamModel pgtype.Text      `json:"upstreamModel"`
	ProviderID    pgtype.Int4      `json:"providerId"`
}

type ListAdminOverviewSeriesMetricsRow struct {
	BucketAt pgtype.Timestamp `json:"bucketAt"`
	GroupKey string           `json:"groupKey"`
	Currency string           `json:"currency"`
	Tokens   int64            `json:"tokens"`
	Requests int64            `json:"requests"`
	Cost     float64          `json:"cost"`
}

func (q *Queries) ListAdminOverviewSeriesMetrics(ctx context.Context, arg ListAdminOverviewSeriesMetricsParams) ([]ListAdminOverviewSeriesMetricsRow, error) {
	rows, err := q.db.Query(ctx, listAdminOverviewSeriesMetrics,
		arg.Dimension,
		arg.StartAt,
		arg.EndAt,
		arg.UserID,
		arg.Model,
		arg.UpstreamModel,
		arg.ProviderID,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAdminOverviewSeriesMetricsRow
	for rows.Next() {
		var i ListAdminOverviewSeriesMetricsRow
		if err := rows.Scan(
			&i.BucketAt,
			&i.GroupKey,
			&i.Currency,
			&i.Tokens,
			&i.Requests,
			&i.Cost,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAdminOverviewSeriesTraces = `-- name: ListAdminOverviewSeriesTraces :many
SELECT
  time_bucket($1::text::interval, r.created_at, $2::timestamp)::timestamp AS bucket_at,
  CASE $3::text
    WHEN 'user' THEN COALESCE(r.user_id::text, '')
    WHEN 'model' THEN COALESCE(r.model, '')
    WHEN 'upstreamModel' THEN COALESCE(r.upstream_model, '')
    WHEN 'provider' THEN COALESCE(r.provider_id::text, '')
    ELSE ''
  END AS group_key,
  COUNT(DISTINCT r.parent_span_id)::bigint AS trace_count
FROM request r
WHERE r.created_at >= $4::timestamp
  AND r.created_at < $5::timestamp
  AND ($6::bigint IS NULL OR r.user_id = $6::bigint)
  AND r.type = 1
  AND r.parent_span_id IS NOT NULL
  AND r.parent_span_id <> ''
  AND ($7::text IS NULL OR r.model = $7::text)
  AND ($8::text IS NULL OR r.upstream_model = $8::text)
  AND ($9::int IS NULL OR r.provider_id = $9::int)
GROUP BY bucket_at, group_key
ORDER BY bucket_at ASC, group_key ASC
`

type ListAdminOverviewSeriesTracesParams struct {
	BucketWidth   string           `json:"bucketWidth"`
	BucketOrigin  pgtype.Timestamp `json:"bucketOrigin"`
	Dimension     string           `json:"dimension"`
	StartAt       pgtype.Timestamp `json:"startAt"`
	EndAt         pgtype.Timestamp `json:"endAt"`
	UserID        pgtype.Int8      `json:"userId"`
	Model         pgtype.Text      `json:"model"`
	UpstreamModel pgtype.Text      `json:"upstreamModel"`
	ProviderID    pgtype.Int4      `json:"providerId"`
}

type ListAdminOverviewSeriesTracesRow struct {
	BucketAt   pgtype.Timestamp `json:"bucketAt"`
	GroupKey   string           `json:"groupKey"`
	TraceCount int64            `json:"traceCount"`
}

func (q *Queries) ListAdminOverviewSeriesTraces(ctx context.Context, arg ListAdminOverviewSeriesTracesParams) ([]ListAdminOverviewSeriesTracesRow, error) {
	rows, err := q.db.Query(ctx, listAdminOverviewSeriesTraces,
		arg.BucketWidth,
		arg.BucketOrigin,
		arg.Dimension,
		arg.StartAt,
		arg.EndAt,
		arg.UserID,
		arg.Model,
		arg.UpstreamModel,
		arg.ProviderID,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAdminOverviewSeriesTracesRow
	for rows.Next() {
		var i ListAdminOverviewSeriesTracesRow
		if err := rows.Scan(&i.BucketAt, &i.GroupKey, &i.TraceCount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAdminOverviewSpeedSeries = `-- name: ListAdminOverviewSpeedSeries :many
SELECT
  bucket_at::timestamp AS bucket_at,
  CASE $1::text
    WHEN 'user' THEN COALESCE(user_id::text, '')
    WHEN 'model' THEN COALESCE(model, '')
    WHEN 'upstreamModel' THEN COALESCE(upstream_model, '')
    WHEN 'provider' THEN COALESCE(provider_id::text, '')
    ELSE ''
  END AS group_key,
  COALESCE(SUM(prefill_token_sum), 0)::float8 AS prefill_token_sum,
  COALESCE(SUM(prefill_time_sum), 0)::float8 AS prefill_time_sum,
  COALESCE(SUM(prefill_request_count), 0)::bigint AS prefill_request_count,
  COALESCE(SUM(decode_token_sum), 0)::float8 AS decode_token_sum,
  COALESCE(SUM(decode_time_sum), 0)::float8 AS decode_time_sum
FROM request_speed_bucketed
WHERE bucket_at >= $2::timestamp
  AND bucket_at < $3::timestamp
  AND ($4::bigint IS NULL OR user_id = $4::bigint)
  AND ($5::text IS NULL OR model = $5::text)
  AND ($6::text IS NULL OR upstream_model = $6::text)
  AND ($7::int IS NULL OR provider_id = $7::int)
GROUP BY bucket_at, group_key
HAVING SUM(prefill_time_sum) > 0 OR SUM(decode_time_sum) > 0
ORDER BY bucket_at ASC, group_key ASC
`

type ListAdminOverviewSpeedSeriesParams struct {
	Dimension     string           `json:"dimension"`
	StartAt       pgtype.Timestamp `json:"startAt"`
	EndAt         pgtype.Timestamp `json:"endAt"`
	UserID        pgtype.Int8      `json:"userId"`
	Model         pgtype.Text      `json:"model"`
	UpstreamModel pgtype.Text      `json:"upstreamModel"`
	ProviderID    pgtype.Int4      `json:"providerId"`
}

type ListAdminOverviewSpeedSeriesRow struct {
	BucketAt            pgtype.Timestamp `json:"bucketAt"`
	GroupKey            string           `json:"groupKey"`
	PrefillTokenSum     float64          `json:"prefillTokenSum"`
	PrefillTimeSum      float64          `json:"prefillTimeSum"`
	PrefillRequestCount int64            `json:"prefillRequestCount"`
	DecodeTokenSum      float64          `json:"decodeTokenSum"`
	DecodeTimeSum       float64          `json:"decodeTimeSum"`
}

func (q *Queries) ListAdminOverviewSpeedSeries(ctx context.Context, arg ListAdminOverviewSpeedSeriesParams) ([]ListAdminOverviewSpeedSeriesRow, error) {
	rows, err := q.db.Query(ctx, listAdminOverviewSpeedSeries,
		arg.Dimension,
		arg.StartAt,
		arg.EndAt,
		arg.UserID,
		arg.Model,
		arg.UpstreamModel,
		arg.ProviderID,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAdminOverviewSpeedSeriesRow
	for rows.Next() {
		var i ListAdminOverviewSpeedSeriesRow
		if err := rows.Scan(
			&i.BucketAt,
			&i.GroupKey,
			&i.PrefillTokenSum,
			&i.PrefillTimeSum,
			&i.PrefillRequestCount,
			&i.DecodeTokenSum,
			&i.DecodeTimeSum,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAdminOverviewTraceCountsByDimension = `-- name: ListAdminOverviewTraceCountsByDimension :many
SELECT
  CASE $1::text
    WHEN 'user' THEN COALESCE(r.user_id::text, '')
    WHEN 'model' THEN COALESCE(r.model, '')
    WHEN 'upstreamModel' THEN COALESCE(r.upstream_model, '')
    WHEN 'provider' THEN COALESCE(r.provider_id::text, '')
    ELSE ''
  END AS key,
  COUNT(DISTINCT r.parent_span_id)::bigint AS trace_count
FROM request r
WHERE r.created_at >= $2::timestamp
  AND r.created_at < $3::timestamp
  AND ($4::bigint IS NULL OR r.user_id = $4::bigint)
  AND r.type = 1
  AND r.parent_span_id IS NOT NULL
  AND r.parent_span_id <> ''
  AND ($5::text IS NULL OR r.model = $5::text)
  AND ($6::text IS NULL OR r.upstream_model = $6::text)
  AND ($7::int IS NULL OR r.provider_id = $7::int)
GROUP BY key
`

type ListAdminOverviewTraceCountsByDimensionParams struct {
	Dimension     string           `json:"dimension"`
	StartAt       pgtype.Timestamp `json:"startAt"`
	EndAt         pgtype.Timestamp `json:"endAt"`
	UserID        pgtype.Int8      `json:"userId"`
	Model         pgtype.Text      `json:"model"`
	UpstreamModel pgtype.Text      `json:"upstreamModel"`
	ProviderID    pgtype.Int4      `json:"providerId"`
}

type ListAdminOverviewTraceCountsByDimensionRow struct {
	Key        string `json:"key"`
	TraceCount int64  `json:"traceCount"`
}

func (q *Queries) ListAdminOverviewTraceCountsByDimension(ctx context.Context, arg ListAdminOverviewTraceCountsByDimensionParams) ([]ListAdminOverviewTraceCountsByDimensionRow, error) {
	rows, err := q.db.Query(ctx, listAdminOverviewTraceCountsByDimension,
		arg.Dimension,
		arg.StartAt,
		arg.EndAt,
		arg.UserID,
		arg.Model,
		arg.UpstreamModel,
		arg.ProviderID,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAdminOverviewTraceCountsByDimensionRow
	for rows.Next() {
		var i ListAdminOverviewTraceCountsByDimensionRow
		if err := rows.Scan(&i.Key, &i.TraceCount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
