// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: api_key.sql

package db

import (
	"context"
)

const deleteApiKey = `-- name: DeleteApiKey :exec
DELETE FROM api_key WHERE id = $1 AND user_id = $2
`

type DeleteApiKeyParams struct {
	ID     int32 `json:"id"`
	UserID int64 `json:"userId"`
}

func (q *Queries) DeleteApiKey(ctx context.Context, arg DeleteApiKeyParams) error {
	_, err := q.db.Exec(ctx, deleteApiKey, arg.ID, arg.UserID)
	return err
}

const getApiKey = `-- name: GetApiKey :one
SELECT id, name, annotations, key, disabled, created_at, updated_at, user_id FROM api_key WHERE id = $1 AND user_id = $2 LIMIT 1
`

type GetApiKeyParams struct {
	ID     int32 `json:"id"`
	UserID int64 `json:"userId"`
}

func (q *Queries) GetApiKey(ctx context.Context, arg GetApiKeyParams) (ApiKey, error) {
	row := q.db.QueryRow(ctx, getApiKey, arg.ID, arg.UserID)
	var i ApiKey
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Annotations,
		&i.Key,
		&i.Disabled,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.UserID,
	)
	return i, err
}

const getApiKeyByKey = `-- name: GetApiKeyByKey :one
SELECT id, name, annotations, key, disabled, created_at, updated_at, user_id FROM api_key WHERE key = $1 LIMIT 1
`

func (q *Queries) GetApiKeyByKey(ctx context.Context, key string) (ApiKey, error) {
	row := q.db.QueryRow(ctx, getApiKeyByKey, key)
	var i ApiKey
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Annotations,
		&i.Key,
		&i.Disabled,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.UserID,
	)
	return i, err
}

const insertApiKey = `-- name: InsertApiKey :one
INSERT INTO api_key (name, key, disabled, annotations, user_id)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, name, annotations, key, disabled, created_at, updated_at, user_id
`

type InsertApiKeyParams struct {
	Name        string `json:"name"`
	Key         string `json:"key"`
	Disabled    bool   `json:"disabled"`
	Annotations []byte `json:"annotations"`
	UserID      int64  `json:"userId"`
}

func (q *Queries) InsertApiKey(ctx context.Context, arg InsertApiKeyParams) (ApiKey, error) {
	row := q.db.QueryRow(ctx, insertApiKey,
		arg.Name,
		arg.Key,
		arg.Disabled,
		arg.Annotations,
		arg.UserID,
	)
	var i ApiKey
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Annotations,
		&i.Key,
		&i.Disabled,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.UserID,
	)
	return i, err
}

const listApiKeys = `-- name: ListApiKeys :many
SELECT id, name, annotations, key, disabled, created_at, updated_at, user_id FROM api_key WHERE user_id = $1 ORDER BY created_at DESC, id DESC
`

func (q *Queries) ListApiKeys(ctx context.Context, userID int64) ([]ApiKey, error) {
	rows, err := q.db.Query(ctx, listApiKeys, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ApiKey
	for rows.Next() {
		var i ApiKey
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Annotations,
			&i.Key,
			&i.Disabled,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.UserID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateApiKey = `-- name: UpdateApiKey :one
UPDATE api_key
SET name = $2, key = $3, disabled = $4, annotations = $5, updated_at = now()
WHERE id = $1 AND user_id = $6
RETURNING id, name, annotations, key, disabled, created_at, updated_at, user_id
`

type UpdateApiKeyParams struct {
	ID          int32  `json:"id"`
	Name        string `json:"name"`
	Key         string `json:"key"`
	Disabled    bool   `json:"disabled"`
	Annotations []byte `json:"annotations"`
	UserID      int64  `json:"userId"`
}

func (q *Queries) UpdateApiKey(ctx context.Context, arg UpdateApiKeyParams) (ApiKey, error) {
	row := q.db.QueryRow(ctx, updateApiKey,
		arg.ID,
		arg.Name,
		arg.Key,
		arg.Disabled,
		arg.Annotations,
		arg.UserID,
	)
	var i ApiKey
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Annotations,
		&i.Key,
		&i.Disabled,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.UserID,
	)
	return i, err
}
