// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: endpoint.sql

package db

import (
	"context"
)

const deleteEndpoint = `-- name: DeleteEndpoint :exec
DELETE FROM endpoint WHERE path = $1
`

func (q *Queries) DeleteEndpoint(ctx context.Context, path string) error {
	_, err := q.db.Exec(ctx, deleteEndpoint, path)
	return err
}

const getEndpoints = `-- name: GetEndpoints :many
SELECT path, name, model_path, credentials_resolver, endpoint_type, prefix_match FROM endpoint
`

func (q *Queries) GetEndpoints(ctx context.Context) ([]Endpoint, error) {
	rows, err := q.db.Query(ctx, getEndpoints)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Endpoint
	for rows.Next() {
		var i Endpoint
		if err := rows.Scan(
			&i.Path,
			&i.Name,
			&i.ModelPath,
			&i.CredentialsResolver,
			&i.EndpointType,
			&i.PrefixMatch,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getFirstEndpointByType = `-- name: GetFirstEndpointByType :one
SELECT path, name, model_path, credentials_resolver, endpoint_type, prefix_match FROM endpoint WHERE endpoint_type = $1 LIMIT 1
`

func (q *Queries) GetFirstEndpointByType(ctx context.Context, endpointType int32) (Endpoint, error) {
	row := q.db.QueryRow(ctx, getFirstEndpointByType, endpointType)
	var i Endpoint
	err := row.Scan(
		&i.Path,
		&i.Name,
		&i.ModelPath,
		&i.CredentialsResolver,
		&i.EndpointType,
		&i.PrefixMatch,
	)
	return i, err
}

const upsertEndpoint = `-- name: UpsertEndpoint :one
INSERT INTO endpoint (name, path, model_path, credentials_resolver, endpoint_type, prefix_match) VALUES ($1, $2, $3, $4, $5, $6) ON CONFLICT (path) DO UPDATE SET name = $1, model_path = $3, credentials_resolver = $4, endpoint_type = $5, prefix_match = $6 RETURNING path, name, model_path, credentials_resolver, endpoint_type, prefix_match
`

type UpsertEndpointParams struct {
	Name                string `json:"name"`
	Path                string `json:"path"`
	ModelPath           string `json:"modelPath"`
	CredentialsResolver int32  `json:"credentialsResolver"`
	EndpointType        int32  `json:"endpointType"`
	PrefixMatch         bool   `json:"prefixMatch"`
}

func (q *Queries) UpsertEndpoint(ctx context.Context, arg UpsertEndpointParams) (Endpoint, error) {
	row := q.db.QueryRow(ctx, upsertEndpoint,
		arg.Name,
		arg.Path,
		arg.ModelPath,
		arg.CredentialsResolver,
		arg.EndpointType,
		arg.PrefixMatch,
	)
	var i Endpoint
	err := row.Scan(
		&i.Path,
		&i.Name,
		&i.ModelPath,
		&i.CredentialsResolver,
		&i.EndpointType,
		&i.PrefixMatch,
	)
	return i, err
}
