// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: exchange_rate.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteExchangeRate = `-- name: DeleteExchangeRate :exec
DELETE FROM exchange_rate WHERE code = $1
`

func (q *Queries) DeleteExchangeRate(ctx context.Context, code string) error {
	_, err := q.db.Exec(ctx, deleteExchangeRate, code)
	return err
}

const getExchangeRateByCode = `-- name: GetExchangeRateByCode :one
SELECT code, name, symbol, units_per_usd FROM exchange_rate WHERE code = $1 LIMIT 1
`

func (q *Queries) GetExchangeRateByCode(ctx context.Context, code string) (ExchangeRate, error) {
	row := q.db.QueryRow(ctx, getExchangeRateByCode, code)
	var i ExchangeRate
	err := row.Scan(
		&i.Code,
		&i.Name,
		&i.Symbol,
		&i.UnitsPerUsd,
	)
	return i, err
}

const getExchangeRates = `-- name: GetExchangeRates :many
SELECT code, name, symbol, units_per_usd FROM exchange_rate ORDER BY code
`

func (q *Queries) GetExchangeRates(ctx context.Context) ([]ExchangeRate, error) {
	rows, err := q.db.Query(ctx, getExchangeRates)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ExchangeRate
	for rows.Next() {
		var i ExchangeRate
		if err := rows.Scan(
			&i.Code,
			&i.Name,
			&i.Symbol,
			&i.UnitsPerUsd,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertExchangeRate = `-- name: UpsertExchangeRate :one
INSERT INTO exchange_rate (code, name, symbol, units_per_usd)
VALUES ($1, $2, $3, $4)
ON CONFLICT (code) DO UPDATE
  SET name = $2, symbol = $3, units_per_usd = $4
RETURNING code, name, symbol, units_per_usd
`

type UpsertExchangeRateParams struct {
	Code        string         `json:"code"`
	Name        string         `json:"name"`
	Symbol      string         `json:"symbol"`
	UnitsPerUsd pgtype.Numeric `json:"unitsPerUsd"`
}

func (q *Queries) UpsertExchangeRate(ctx context.Context, arg UpsertExchangeRateParams) (ExchangeRate, error) {
	row := q.db.QueryRow(ctx, upsertExchangeRate,
		arg.Code,
		arg.Name,
		arg.Symbol,
		arg.UnitsPerUsd,
	)
	var i ExchangeRate
	err := row.Scan(
		&i.Code,
		&i.Name,
		&i.Symbol,
		&i.UnitsPerUsd,
	)
	return i, err
}
