// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type ApiKey struct {
	ID           int32  `json:"id"`
	Name         string `json:"name"`
	ApiKeyHash   []byte `json:"apiKeyHash"`
	ApiKeyMasked string `json:"apiKeyMasked"`
	Annotations  []byte `json:"annotations"`
}

type Endpoint struct {
	Path                string `json:"path"`
	Name                string `json:"name"`
	ModelPath           string `json:"modelPath"`
	CredentialsResolver int32  `json:"credentialsResolver"`
	EndpointType        int32  `json:"endpointType"`
}

type Model struct {
	Name      string      `json:"name"`
	Title     pgtype.Text `json:"title"`
	Developer pgtype.Text `json:"developer"`
	Series    pgtype.Text `json:"series"`
	Disabled  bool        `json:"disabled"`
}

type Provider struct {
	ID             int32  `json:"id"`
	Name           string `json:"name"`
	Credentials    string `json:"credentials"`
	Priority       int32  `json:"priority"`
	ProviderModels []byte `json:"providerModels"`
	Annotations    []byte `json:"annotations"`
	Disabled       bool   `json:"disabled"`
}

type ProviderEndpoint struct {
	ProviderID   int32  `json:"providerId"`
	EndpointPath string `json:"endpointPath"`
	UpstreamUrl  string `json:"upstreamUrl"`
}

type Request struct {
	ID               string           `json:"id"`
	SpanID           pgtype.Text      `json:"spanId"`
	ParentSpanID     pgtype.Text      `json:"parentSpanId"`
	ProviderID       pgtype.Int4      `json:"providerId"`
	EndpointPath     pgtype.Text      `json:"endpointPath"`
	ApiKeyID         pgtype.Int4      `json:"apiKeyId"`
	Model            pgtype.Text      `json:"model"`
	InputTokens      pgtype.Int4      `json:"inputTokens"`
	CacheReadTokens  pgtype.Int4      `json:"cacheReadTokens"`
	OutputTokens     pgtype.Int4      `json:"outputTokens"`
	CacheWriteTokens pgtype.Int4      `json:"cacheWriteTokens"`
	StatusCode       pgtype.Int4      `json:"statusCode"`
	ErrorMessage     pgtype.Text      `json:"errorMessage"`
	TtftMs           pgtype.Int4      `json:"ttftMs"`
	TimeSpentMs      pgtype.Int4      `json:"timeSpentMs"`
	CreatedAt        pgtype.Timestamp `json:"createdAt"`
	Type             int32            `json:"type"`
	Status           int32            `json:"status"`
	UpstreamModel    pgtype.Text      `json:"upstreamModel"`
}

type Script struct {
	ID        string             `json:"id"`
	Name      string             `json:"name"`
	Source    string             `json:"source"`
	Enabled   bool               `json:"enabled"`
	CreatedAt pgtype.Timestamptz `json:"createdAt"`
	UpdatedAt pgtype.Timestamptz `json:"updatedAt"`
}
