// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type ApiKey struct {
	ID           int32  `json:"id"`
	Name         string `json:"name"`
	ApiKeyHash   []byte `json:"apiKeyHash"`
	ApiKeyMasked string `json:"apiKeyMasked"`
	Annotations  []byte `json:"annotations"`
}

type Endpoint struct {
	ID                  int32  `json:"id"`
	Name                string `json:"name"`
	Path                string `json:"path"`
	ModelPath           string `json:"modelPath"`
	CredentialsResolver int32  `json:"credentialsResolver"`
}

type Model struct {
	Name      string      `json:"name"`
	Title     pgtype.Text `json:"title"`
	Developer pgtype.Text `json:"developer"`
	Series    pgtype.Text `json:"series"`
}

type ModelProviderEndpoint struct {
	ModelName         string      `json:"modelName"`
	ProviderID        int32       `json:"providerId"`
	EndpointID        int32       `json:"endpointId"`
	UpstreamModelName pgtype.Text `json:"upstreamModelName"`
	Priority          int32       `json:"priority"`
	Annotations       []byte      `json:"annotations"`
}

type Provider struct {
	ID             int32  `json:"id"`
	Name           string `json:"name"`
	Credentials    string `json:"credentials"`
	Priority       int32  `json:"priority"`
	ProviderModels []byte `json:"providerModels"`
	Annotations    []byte `json:"annotations"`
}

type ProviderEndpoint struct {
	ProviderID  int32  `json:"providerId"`
	EndpointID  int32  `json:"endpointId"`
	UpstreamUrl string `json:"upstreamUrl"`
}

type Request struct {
	ID               string           `json:"id"`
	SpanID           pgtype.Text      `json:"spanId"`
	ParentSpanID     pgtype.Text      `json:"parentSpanId"`
	ProviderID       int32            `json:"providerId"`
	EndpointID       int32            `json:"endpointId"`
	ApiKeyID         int32            `json:"apiKeyId"`
	Model            pgtype.Text      `json:"model"`
	InputTokens      pgtype.Int4      `json:"inputTokens"`
	CacheReadTokens  pgtype.Int4      `json:"cacheReadTokens"`
	OutputTokens     pgtype.Int4      `json:"outputTokens"`
	CacheWriteTokens pgtype.Int4      `json:"cacheWriteTokens"`
	StatusCode       int32            `json:"statusCode"`
	ErrorMessage     pgtype.Text      `json:"errorMessage"`
	TtftMs           pgtype.Int4      `json:"ttftMs"`
	TimeSpentMs      int32            `json:"timeSpentMs"`
	CreatedAt        pgtype.Timestamp `json:"createdAt"`
}
