// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type ApiKey struct {
	ID          int32              `json:"id"`
	Name        string             `json:"name"`
	Annotations []byte             `json:"annotations"`
	Key         string             `json:"key"`
	Disabled    bool               `json:"disabled"`
	CreatedAt   pgtype.Timestamptz `json:"createdAt"`
	UpdatedAt   pgtype.Timestamptz `json:"updatedAt"`
	UserID      int64              `json:"userId"`
}

type AppUser struct {
	ID          int64              `json:"id"`
	DisplayName string             `json:"displayName"`
	IsAdmin     bool               `json:"isAdmin"`
	CreatedAt   pgtype.Timestamptz `json:"createdAt"`
	UpdatedAt   pgtype.Timestamptz `json:"updatedAt"`
	Disabled    bool               `json:"disabled"`
	Annotations []byte             `json:"annotations"`
}

type Endpoint struct {
	Path                string `json:"path"`
	Name                string `json:"name"`
	ModelPath           string `json:"modelPath"`
	CredentialsResolver int32  `json:"credentialsResolver"`
	EndpointType        int32  `json:"endpointType"`
}

type ExchangeRate struct {
	Code        string         `json:"code"`
	Name        string         `json:"name"`
	Symbol      string         `json:"symbol"`
	UnitsPerUsd pgtype.Numeric `json:"unitsPerUsd"`
}

type Model struct {
	Name        string `json:"name"`
	Disabled    bool   `json:"disabled"`
	Pricing     []byte `json:"pricing"`
	Annotations []byte `json:"annotations"`
}

type Project struct {
	ID          int32              `json:"id"`
	Name        string             `json:"name"`
	Paths       []byte             `json:"paths"`
	FirstSeenAt pgtype.Timestamp   `json:"firstSeenAt"`
	LastSeenAt  pgtype.Timestamp   `json:"lastSeenAt"`
	CreatedAt   pgtype.Timestamptz `json:"createdAt"`
	UpdatedAt   pgtype.Timestamptz `json:"updatedAt"`
	AutoCreated bool               `json:"autoCreated"`
	UserID      int64              `json:"userId"`
}

type Provider struct {
	ID                      int32       `json:"id"`
	Name                    string      `json:"name"`
	Credentials             string      `json:"credentials"`
	Priority                int32       `json:"priority"`
	ProviderModels          []byte      `json:"providerModels"`
	Annotations             []byte      `json:"annotations"`
	Disabled                bool        `json:"disabled"`
	ProxyUrl                pgtype.Text `json:"proxyUrl"`
	ModelsEndpointUrl       string      `json:"modelsEndpointUrl"`
	ModelsEndpointResolver  int32       `json:"modelsEndpointResolver"`
	SupportsNativeWebSearch bool        `json:"supportsNativeWebSearch"`
}

type ProviderEndpoint struct {
	ProviderID          int32  `json:"providerId"`
	EndpointPath        string `json:"endpointPath"`
	UpstreamUrl         string `json:"upstreamUrl"`
	CredentialsResolver int32  `json:"credentialsResolver"`
}

type Request struct {
	ID                  string           `json:"id"`
	SpanID              pgtype.Text      `json:"spanId"`
	ParentSpanID        pgtype.Text      `json:"parentSpanId"`
	ProviderID          pgtype.Int4      `json:"providerId"`
	EndpointPath        pgtype.Text      `json:"endpointPath"`
	ApiKeyID            pgtype.Int4      `json:"apiKeyId"`
	Model               pgtype.Text      `json:"model"`
	InputTokens         pgtype.Int4      `json:"inputTokens"`
	CacheReadTokens     pgtype.Int4      `json:"cacheReadTokens"`
	OutputTokens        pgtype.Int4      `json:"outputTokens"`
	CacheWriteTokens    pgtype.Int4      `json:"cacheWriteTokens"`
	StatusCode          pgtype.Int4      `json:"statusCode"`
	ErrorMessage        pgtype.Text      `json:"errorMessage"`
	TtftMs              pgtype.Int4      `json:"ttftMs"`
	TimeSpentMs         pgtype.Int4      `json:"timeSpentMs"`
	CreatedAt           pgtype.Timestamp `json:"createdAt"`
	Type                int32            `json:"type"`
	Status              int32            `json:"status"`
	UpstreamModel       pgtype.Text      `json:"upstreamModel"`
	ModelCost           pgtype.Numeric   `json:"modelCost"`
	ModelCostCurrency   pgtype.Text      `json:"modelCostCurrency"`
	UserMessagePreview  pgtype.Text      `json:"userMessagePreview"`
	CacheWrite1hTokens  pgtype.Int4      `json:"cacheWrite1hTokens"`
	ProjectID           pgtype.Int4      `json:"projectId"`
	FinishReason        pgtype.Int4      `json:"finishReason"`
	InferredProvider    pgtype.Text      `json:"inferredProvider"`
	InferredModel       pgtype.Text      `json:"inferredModel"`
	InferredModelSource int16            `json:"inferredModelSource"`
	UserID              pgtype.Int8      `json:"userId"`
}

type RequestOverviewBucketed struct {
	BucketAt           interface{}    `json:"bucketAt"`
	ApiKeyID           pgtype.Int4    `json:"apiKeyId"`
	Model              pgtype.Text    `json:"model"`
	UpstreamModel      pgtype.Text    `json:"upstreamModel"`
	ProviderID         pgtype.Int4    `json:"providerId"`
	ProjectID          pgtype.Int4    `json:"projectId"`
	UserID             pgtype.Int8    `json:"userId"`
	CostCurrency       interface{}    `json:"costCurrency"`
	RequestCount       int64          `json:"requestCount"`
	InputTokens        int64          `json:"inputTokens"`
	CacheReadTokens    int64          `json:"cacheReadTokens"`
	OutputTokens       int64          `json:"outputTokens"`
	CacheWriteTokens   int64          `json:"cacheWriteTokens"`
	CacheWrite1hTokens int64          `json:"cacheWrite1hTokens"`
	Cost               pgtype.Numeric `json:"cost"`
}

type RequestSpeedBucketed struct {
	BucketAt            interface{} `json:"bucketAt"`
	Model               pgtype.Text `json:"model"`
	UpstreamModel       pgtype.Text `json:"upstreamModel"`
	ProviderID          pgtype.Int4 `json:"providerId"`
	ApiKeyID            pgtype.Int4 `json:"apiKeyId"`
	ProjectID           pgtype.Int4 `json:"projectId"`
	UserID              pgtype.Int8 `json:"userId"`
	PrefillTokenSum     int64       `json:"prefillTokenSum"`
	PrefillTimeSum      int64       `json:"prefillTimeSum"`
	PrefillRequestCount int64       `json:"prefillRequestCount"`
	DecodeTokenSum      int64       `json:"decodeTokenSum"`
	DecodeTimeSum       int64       `json:"decodeTimeSum"`
}

type Script struct {
	ID        string             `json:"id"`
	Name      string             `json:"name"`
	Source    string             `json:"source"`
	Enabled   bool               `json:"enabled"`
	CreatedAt pgtype.Timestamptz `json:"createdAt"`
	UpdatedAt pgtype.Timestamptz `json:"updatedAt"`
}

type Trace struct {
	ID             string           `json:"id"`
	ParentSpanID   string           `json:"parentSpanId"`
	FirstRequestAt pgtype.Timestamp `json:"firstRequestAt"`
	LastRequestAt  pgtype.Timestamp `json:"lastRequestAt"`
	UpdatedAt      pgtype.Timestamp `json:"updatedAt"`
	UserID         int64            `json:"userId"`
}

type UserIdentity struct {
	ID        int64              `json:"id"`
	UserID    int64              `json:"userId"`
	Provider  string             `json:"provider"`
	Identity  string             `json:"identity"`
	CreatedAt pgtype.Timestamptz `json:"createdAt"`
}

type UserSetting struct {
	UserID    int64              `json:"userId"`
	Key       string             `json:"key"`
	Value     []byte             `json:"value"`
	UpdatedAt pgtype.Timestamptz `json:"updatedAt"`
}
