// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: model.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteModel = `-- name: DeleteModel :exec
DELETE FROM model WHERE name = $1
`

func (q *Queries) DeleteModel(ctx context.Context, name string) error {
	_, err := q.db.Exec(ctx, deleteModel, name)
	return err
}

const getModelByName = `-- name: GetModelByName :one
SELECT name, title, developer, series, disabled FROM model WHERE name = $1 LIMIT 1
`

func (q *Queries) GetModelByName(ctx context.Context, name string) (Model, error) {
	row := q.db.QueryRow(ctx, getModelByName, name)
	var i Model
	err := row.Scan(
		&i.Name,
		&i.Title,
		&i.Developer,
		&i.Series,
		&i.Disabled,
	)
	return i, err
}

const getModels = `-- name: GetModels :many
SELECT name, title, developer, series, disabled FROM model
`

func (q *Queries) GetModels(ctx context.Context) ([]Model, error) {
	rows, err := q.db.Query(ctx, getModels)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Model
	for rows.Next() {
		var i Model
		if err := rows.Scan(
			&i.Name,
			&i.Title,
			&i.Developer,
			&i.Series,
			&i.Disabled,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertModel = `-- name: UpsertModel :one
INSERT INTO model (name, title, developer, series, disabled) VALUES ($1, $2, $3, $4, $5) ON CONFLICT (name) DO UPDATE SET title = $2, developer = $3, series = $4, disabled = $5 RETURNING name, title, developer, series, disabled
`

type UpsertModelParams struct {
	Name      string      `json:"name"`
	Title     pgtype.Text `json:"title"`
	Developer pgtype.Text `json:"developer"`
	Series    pgtype.Text `json:"series"`
	Disabled  bool        `json:"disabled"`
}

func (q *Queries) UpsertModel(ctx context.Context, arg UpsertModelParams) (Model, error) {
	row := q.db.QueryRow(ctx, upsertModel,
		arg.Name,
		arg.Title,
		arg.Developer,
		arg.Series,
		arg.Disabled,
	)
	var i Model
	err := row.Scan(
		&i.Name,
		&i.Title,
		&i.Developer,
		&i.Series,
		&i.Disabled,
	)
	return i, err
}
