// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: overview.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getOverviewCostSummary = `-- name: GetOverviewCostSummary :many
SELECT
  upstream_cost_currency AS currency,
  COALESCE(SUM(upstream_cost), 0)::numeric(20, 6) AS amount
FROM request_overview_hourly
WHERE bucket_at >= $1::timestamp
  AND bucket_at < $2::timestamp
  AND upstream_cost IS NOT NULL
  AND upstream_cost_currency IS NOT NULL
  AND ($3::int IS NULL OR api_key_id = $3::int)
  AND ($4::text IS NULL OR model = $4::text)
  AND ($5::text IS NULL OR upstream_model = $5::text)
  AND ($6::int IS NULL OR provider_id = $6::int)
GROUP BY upstream_cost_currency
ORDER BY upstream_cost_currency
`

type GetOverviewCostSummaryParams struct {
	StartAt       pgtype.Timestamp `json:"startAt"`
	EndAt         pgtype.Timestamp `json:"endAt"`
	ApiKeyID      pgtype.Int4      `json:"apiKeyId"`
	Model         pgtype.Text      `json:"model"`
	UpstreamModel pgtype.Text      `json:"upstreamModel"`
	ProviderID    pgtype.Int4      `json:"providerId"`
}

type GetOverviewCostSummaryRow struct {
	Currency pgtype.Text    `json:"currency"`
	Amount   pgtype.Numeric `json:"amount"`
}

func (q *Queries) GetOverviewCostSummary(ctx context.Context, arg GetOverviewCostSummaryParams) ([]GetOverviewCostSummaryRow, error) {
	rows, err := q.db.Query(ctx, getOverviewCostSummary,
		arg.StartAt,
		arg.EndAt,
		arg.ApiKeyID,
		arg.Model,
		arg.UpstreamModel,
		arg.ProviderID,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetOverviewCostSummaryRow
	for rows.Next() {
		var i GetOverviewCostSummaryRow
		if err := rows.Scan(&i.Currency, &i.Amount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getOverviewDistribution = `-- name: GetOverviewDistribution :many
WITH metric_rows AS (
  SELECT
    CASE $1::text
      WHEN 'apiKey' THEN COALESCE(api_key_id::text, '')
      WHEN 'model' THEN COALESCE(model, '')
      WHEN 'upstreamModel' THEN COALESCE(upstream_model, '')
      WHEN 'provider' THEN COALESCE(provider_id::text, '')
    END AS group_key,
    SUM(request_count)::bigint AS request_count,
    SUM(total_tokens)::bigint AS total_tokens
  FROM request_overview_hourly
  WHERE bucket_at >= $2::timestamp
    AND bucket_at < $3::timestamp
    AND ($4::int IS NULL OR api_key_id = $4::int)
    AND ($5::text IS NULL OR model = $5::text)
    AND ($6::text IS NULL OR upstream_model = $6::text)
    AND ($7::int IS NULL OR provider_id = $7::int)
  GROUP BY group_key
),
cost_rows AS (
  SELECT
    CASE $1::text
      WHEN 'apiKey' THEN COALESCE(api_key_id::text, '')
      WHEN 'model' THEN COALESCE(model, '')
      WHEN 'upstreamModel' THEN COALESCE(upstream_model, '')
      WHEN 'provider' THEN COALESCE(provider_id::text, '')
    END AS group_key,
    upstream_cost_currency AS currency,
    SUM(upstream_cost)::numeric(20, 6) AS amount
  FROM request_overview_hourly
  WHERE bucket_at >= $2::timestamp
    AND bucket_at < $3::timestamp
    AND upstream_cost IS NOT NULL
    AND upstream_cost_currency IS NOT NULL
    AND ($4::int IS NULL OR api_key_id = $4::int)
    AND ($5::text IS NULL OR model = $5::text)
    AND ($6::text IS NULL OR upstream_model = $6::text)
    AND ($7::int IS NULL OR provider_id = $7::int)
  GROUP BY group_key, upstream_cost_currency
),
cost_json AS (
  SELECT
    group_key,
    jsonb_agg(jsonb_build_object('currency', currency, 'amount', amount::float8) ORDER BY currency)::jsonb AS costs
  FROM cost_rows
  GROUP BY group_key
),
trace_rows AS (
  SELECT
    groups.group_key,
    COUNT(DISTINCT t.id)::bigint AS trace_count
  FROM traces t
  JOIN LATERAL (
    SELECT DISTINCT
      CASE $1::text
        WHEN 'apiKey' THEN COALESCE(r.api_key_id::text, '')
        WHEN 'model' THEN COALESCE(r.model, '')
        WHEN 'upstreamModel' THEN COALESCE(r.upstream_model, '')
        WHEN 'provider' THEN COALESCE(r.provider_id::text, '')
      END AS group_key
    FROM request r
    WHERE r.parent_span_id = t.parent_span_id
      AND r.created_at >= t.first_request_at
      AND r.created_at <= t.last_request_at
      AND r.type = 1
      AND ($4::int IS NULL OR r.api_key_id = $4::int)
      AND ($5::text IS NULL OR r.model = $5::text)
      AND ($6::text IS NULL OR r.upstream_model = $6::text)
      AND ($7::int IS NULL OR r.provider_id = $7::int)
  ) groups ON true
  WHERE t.last_request_at >= $2::timestamp
    AND t.last_request_at < $3::timestamp
  GROUP BY groups.group_key
)
SELECT
  $1::text AS dimension,
  COALESCE(metric_rows.group_key, trace_rows.group_key, cost_json.group_key, '')::text AS group_key,
  COALESCE(
    CASE $1::text
      WHEN 'apiKey' THEN api_key.name
      WHEN 'provider' THEN provider.name
      ELSE NULL
    END,
    COALESCE(metric_rows.group_key, trace_rows.group_key, cost_json.group_key, '')
  )::text AS group_label,
  COALESCE(metric_rows.total_tokens, 0)::bigint AS total_tokens,
  COALESCE(metric_rows.request_count, 0)::bigint AS request_count,
  COALESCE(trace_rows.trace_count, 0)::bigint AS trace_count,
  COALESCE(cost_json.costs, '[]'::jsonb)::jsonb AS costs
FROM metric_rows
FULL OUTER JOIN trace_rows ON trace_rows.group_key = metric_rows.group_key
FULL OUTER JOIN cost_json ON cost_json.group_key = COALESCE(metric_rows.group_key, trace_rows.group_key)
LEFT JOIN api_key ON $1::text = 'apiKey'
  AND COALESCE(metric_rows.group_key, trace_rows.group_key, cost_json.group_key) <> ''
  AND api_key.id = COALESCE(metric_rows.group_key, trace_rows.group_key, cost_json.group_key)::int
LEFT JOIN provider ON $1::text = 'provider'
  AND COALESCE(metric_rows.group_key, trace_rows.group_key, cost_json.group_key) <> ''
  AND provider.id = COALESCE(metric_rows.group_key, trace_rows.group_key, cost_json.group_key)::int
ORDER BY total_tokens DESC, request_count DESC, group_label ASC
`

type GetOverviewDistributionParams struct {
	Dimension     string           `json:"dimension"`
	StartAt       pgtype.Timestamp `json:"startAt"`
	EndAt         pgtype.Timestamp `json:"endAt"`
	ApiKeyID      pgtype.Int4      `json:"apiKeyId"`
	Model         pgtype.Text      `json:"model"`
	UpstreamModel pgtype.Text      `json:"upstreamModel"`
	ProviderID    pgtype.Int4      `json:"providerId"`
}

type GetOverviewDistributionRow struct {
	Dimension    string `json:"dimension"`
	GroupKey     string `json:"groupKey"`
	GroupLabel   string `json:"groupLabel"`
	TotalTokens  int64  `json:"totalTokens"`
	RequestCount int64  `json:"requestCount"`
	TraceCount   int64  `json:"traceCount"`
	Costs        []byte `json:"costs"`
}

func (q *Queries) GetOverviewDistribution(ctx context.Context, arg GetOverviewDistributionParams) ([]GetOverviewDistributionRow, error) {
	rows, err := q.db.Query(ctx, getOverviewDistribution,
		arg.Dimension,
		arg.StartAt,
		arg.EndAt,
		arg.ApiKeyID,
		arg.Model,
		arg.UpstreamModel,
		arg.ProviderID,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetOverviewDistributionRow
	for rows.Next() {
		var i GetOverviewDistributionRow
		if err := rows.Scan(
			&i.Dimension,
			&i.GroupKey,
			&i.GroupLabel,
			&i.TotalTokens,
			&i.RequestCount,
			&i.TraceCount,
			&i.Costs,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getOverviewHourlyCostSeries = `-- name: GetOverviewHourlyCostSeries :many
WITH buckets AS (
  SELECT generate_series(
    $2::timestamp,
    $3::timestamp - INTERVAL '1 hour',
    INTERVAL '1 hour'
  )::timestamp AS bucket_at
),
groups AS (
  SELECT DISTINCT
    CASE $1::text
      WHEN 'none' THEN ''
      WHEN 'apiKey' THEN COALESCE(api_key_id::text, '')
      WHEN 'model' THEN COALESCE(model, '')
      WHEN 'upstreamModel' THEN COALESCE(upstream_model, '')
      WHEN 'provider' THEN COALESCE(provider_id::text, '')
    END AS group_key,
    upstream_cost_currency AS currency
  FROM request_overview_hourly
  WHERE bucket_at >= $2::timestamp
    AND bucket_at < $3::timestamp
    AND upstream_cost IS NOT NULL
    AND upstream_cost_currency IS NOT NULL
    AND ($4::int IS NULL OR api_key_id = $4::int)
    AND ($5::text IS NULL OR model = $5::text)
    AND ($6::text IS NULL OR upstream_model = $6::text)
    AND ($7::int IS NULL OR provider_id = $7::int)
),
metric_rows AS (
  SELECT
    bucket_at,
    CASE $1::text
      WHEN 'none' THEN ''
      WHEN 'apiKey' THEN COALESCE(api_key_id::text, '')
      WHEN 'model' THEN COALESCE(model, '')
      WHEN 'upstreamModel' THEN COALESCE(upstream_model, '')
      WHEN 'provider' THEN COALESCE(provider_id::text, '')
    END AS group_key,
    upstream_cost_currency AS currency,
    SUM(upstream_cost)::float8 AS cost_value
  FROM request_overview_hourly
  WHERE bucket_at >= $2::timestamp
    AND bucket_at < $3::timestamp
    AND upstream_cost IS NOT NULL
    AND upstream_cost_currency IS NOT NULL
    AND ($4::int IS NULL OR api_key_id = $4::int)
    AND ($5::text IS NULL OR model = $5::text)
    AND ($6::text IS NULL OR upstream_model = $6::text)
    AND ($7::int IS NULL OR provider_id = $7::int)
  GROUP BY bucket_at, group_key, upstream_cost_currency
)
SELECT
  buckets.bucket_at,
  COALESCE(groups.group_key, '')::text AS group_key,
  COALESCE(
    CASE $1::text
      WHEN 'none' THEN '总量'
      WHEN 'apiKey' THEN api_key.name
      WHEN 'provider' THEN provider.name
      ELSE NULL
    END,
    COALESCE(groups.group_key, '')
  )::text AS group_label,
  COALESCE(metric_rows.cost_value, 0)::float8 AS cost_value,
  COALESCE(groups.currency, '')::text AS currency
FROM buckets
CROSS JOIN (SELECT group_key, currency FROM groups UNION SELECT '', '' WHERE NOT EXISTS (SELECT 1 FROM groups)) groups
LEFT JOIN metric_rows ON metric_rows.bucket_at = buckets.bucket_at
  AND metric_rows.group_key = groups.group_key
  AND metric_rows.currency = groups.currency
LEFT JOIN api_key ON $1::text = 'apiKey'
  AND groups.group_key <> ''
  AND api_key.id = groups.group_key::int
LEFT JOIN provider ON $1::text = 'provider'
  AND groups.group_key <> ''
  AND provider.id = groups.group_key::int
ORDER BY buckets.bucket_at ASC, group_label ASC, COALESCE(groups.currency, '')::text ASC
`

type GetOverviewHourlyCostSeriesParams struct {
	Dimension     string           `json:"dimension"`
	StartAt       pgtype.Timestamp `json:"startAt"`
	EndAt         pgtype.Timestamp `json:"endAt"`
	ApiKeyID      pgtype.Int4      `json:"apiKeyId"`
	Model         pgtype.Text      `json:"model"`
	UpstreamModel pgtype.Text      `json:"upstreamModel"`
	ProviderID    pgtype.Int4      `json:"providerId"`
}

type GetOverviewHourlyCostSeriesRow struct {
	BucketAt   pgtype.Timestamp `json:"bucketAt"`
	GroupKey   string           `json:"groupKey"`
	GroupLabel string           `json:"groupLabel"`
	CostValue  float64          `json:"costValue"`
	Currency   string           `json:"currency"`
}

func (q *Queries) GetOverviewHourlyCostSeries(ctx context.Context, arg GetOverviewHourlyCostSeriesParams) ([]GetOverviewHourlyCostSeriesRow, error) {
	rows, err := q.db.Query(ctx, getOverviewHourlyCostSeries,
		arg.Dimension,
		arg.StartAt,
		arg.EndAt,
		arg.ApiKeyID,
		arg.Model,
		arg.UpstreamModel,
		arg.ProviderID,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetOverviewHourlyCostSeriesRow
	for rows.Next() {
		var i GetOverviewHourlyCostSeriesRow
		if err := rows.Scan(
			&i.BucketAt,
			&i.GroupKey,
			&i.GroupLabel,
			&i.CostValue,
			&i.Currency,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getOverviewHourlyRequestSeries = `-- name: GetOverviewHourlyRequestSeries :many
WITH buckets AS (
  SELECT generate_series(
    $2::timestamp,
    $3::timestamp - INTERVAL '1 hour',
    INTERVAL '1 hour'
  )::timestamp AS bucket_at
),
groups AS (
  SELECT DISTINCT
    CASE $1::text
      WHEN 'none' THEN ''
      WHEN 'apiKey' THEN COALESCE(api_key_id::text, '')
      WHEN 'model' THEN COALESCE(model, '')
      WHEN 'upstreamModel' THEN COALESCE(upstream_model, '')
      WHEN 'provider' THEN COALESCE(provider_id::text, '')
    END AS group_key
  FROM request_overview_hourly
  WHERE bucket_at >= $2::timestamp
    AND bucket_at < $3::timestamp
    AND ($4::int IS NULL OR api_key_id = $4::int)
    AND ($5::text IS NULL OR model = $5::text)
    AND ($6::text IS NULL OR upstream_model = $6::text)
    AND ($7::int IS NULL OR provider_id = $7::int)
),
metric_rows AS (
  SELECT
    bucket_at,
    CASE $1::text
      WHEN 'none' THEN ''
      WHEN 'apiKey' THEN COALESCE(api_key_id::text, '')
      WHEN 'model' THEN COALESCE(model, '')
      WHEN 'upstreamModel' THEN COALESCE(upstream_model, '')
      WHEN 'provider' THEN COALESCE(provider_id::text, '')
    END AS group_key,
    SUM(total_tokens)::float8 AS tokens_value,
    SUM(request_count)::float8 AS requests_value
  FROM request_overview_hourly
  WHERE bucket_at >= $2::timestamp
    AND bucket_at < $3::timestamp
    AND ($4::int IS NULL OR api_key_id = $4::int)
    AND ($5::text IS NULL OR model = $5::text)
    AND ($6::text IS NULL OR upstream_model = $6::text)
    AND ($7::int IS NULL OR provider_id = $7::int)
  GROUP BY bucket_at, group_key
)
SELECT
  buckets.bucket_at,
  COALESCE(groups.group_key, '')::text AS group_key,
  COALESCE(
    CASE $1::text
      WHEN 'none' THEN '总量'
      WHEN 'apiKey' THEN api_key.name
      WHEN 'provider' THEN provider.name
      ELSE NULL
    END,
    COALESCE(groups.group_key, '')
  )::text AS group_label,
  COALESCE(metric_rows.tokens_value, 0)::float8 AS tokens_value,
  COALESCE(metric_rows.requests_value, 0)::float8 AS requests_value
FROM buckets
CROSS JOIN (SELECT group_key FROM groups UNION SELECT '' WHERE NOT EXISTS (SELECT 1 FROM groups)) groups
LEFT JOIN metric_rows ON metric_rows.bucket_at = buckets.bucket_at AND metric_rows.group_key = groups.group_key
LEFT JOIN api_key ON $1::text = 'apiKey'
  AND groups.group_key <> ''
  AND api_key.id = groups.group_key::int
LEFT JOIN provider ON $1::text = 'provider'
  AND groups.group_key <> ''
  AND provider.id = groups.group_key::int
ORDER BY buckets.bucket_at ASC, group_label ASC
`

type GetOverviewHourlyRequestSeriesParams struct {
	Dimension     string           `json:"dimension"`
	StartAt       pgtype.Timestamp `json:"startAt"`
	EndAt         pgtype.Timestamp `json:"endAt"`
	ApiKeyID      pgtype.Int4      `json:"apiKeyId"`
	Model         pgtype.Text      `json:"model"`
	UpstreamModel pgtype.Text      `json:"upstreamModel"`
	ProviderID    pgtype.Int4      `json:"providerId"`
}

type GetOverviewHourlyRequestSeriesRow struct {
	BucketAt      pgtype.Timestamp `json:"bucketAt"`
	GroupKey      string           `json:"groupKey"`
	GroupLabel    string           `json:"groupLabel"`
	TokensValue   float64          `json:"tokensValue"`
	RequestsValue float64          `json:"requestsValue"`
}

func (q *Queries) GetOverviewHourlyRequestSeries(ctx context.Context, arg GetOverviewHourlyRequestSeriesParams) ([]GetOverviewHourlyRequestSeriesRow, error) {
	rows, err := q.db.Query(ctx, getOverviewHourlyRequestSeries,
		arg.Dimension,
		arg.StartAt,
		arg.EndAt,
		arg.ApiKeyID,
		arg.Model,
		arg.UpstreamModel,
		arg.ProviderID,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetOverviewHourlyRequestSeriesRow
	for rows.Next() {
		var i GetOverviewHourlyRequestSeriesRow
		if err := rows.Scan(
			&i.BucketAt,
			&i.GroupKey,
			&i.GroupLabel,
			&i.TokensValue,
			&i.RequestsValue,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getOverviewHourlyTraceSeries = `-- name: GetOverviewHourlyTraceSeries :many
WITH buckets AS (
  SELECT generate_series(
    $2::timestamp,
    $3::timestamp - INTERVAL '1 hour',
    INTERVAL '1 hour'
  )::timestamp AS bucket_at
),
groups AS (
  SELECT ''::text AS group_key
  WHERE $1::text = 'none'
  UNION
  SELECT DISTINCT
    CASE $1::text
      WHEN 'apiKey' THEN COALESCE(r.api_key_id::text, '')
      WHEN 'model' THEN COALESCE(r.model, '')
      WHEN 'upstreamModel' THEN COALESCE(r.upstream_model, '')
      WHEN 'provider' THEN COALESCE(r.provider_id::text, '')
    END AS group_key
  FROM traces t
  JOIN request r ON r.parent_span_id = t.parent_span_id
    AND r.created_at >= t.first_request_at
    AND r.created_at <= t.last_request_at
    AND r.type = 1
  WHERE $1::text <> 'none'
    AND t.last_request_at >= $2::timestamp
    AND t.last_request_at < $3::timestamp
    AND ($4::int IS NULL OR r.api_key_id = $4::int)
    AND ($5::text IS NULL OR r.model = $5::text)
    AND ($6::text IS NULL OR r.upstream_model = $6::text)
    AND ($7::int IS NULL OR r.provider_id = $7::int)
),
metric_rows AS (
  SELECT
    time_bucket('1 hour', t.last_request_at)::timestamp AS bucket_at,
    ''::text AS group_key,
    COUNT(*)::float8 AS trace_value
  FROM traces t
  WHERE $1::text = 'none'
    AND t.last_request_at >= $2::timestamp
    AND t.last_request_at < $3::timestamp
    AND (
      (
        $4::int IS NULL
        AND $5::text IS NULL
        AND $6::text IS NULL
        AND $7::int IS NULL
      )
      OR EXISTS (
        SELECT 1
        FROM request r
        WHERE r.parent_span_id = t.parent_span_id
          AND r.created_at >= t.first_request_at
          AND r.created_at <= t.last_request_at
          AND r.type = 1
          AND ($4::int IS NULL OR r.api_key_id = $4::int)
          AND ($5::text IS NULL OR r.model = $5::text)
          AND ($6::text IS NULL OR r.upstream_model = $6::text)
          AND ($7::int IS NULL OR r.provider_id = $7::int)
      )
    )
  GROUP BY bucket_at
  UNION ALL
  SELECT
    time_bucket('1 hour', t.last_request_at)::timestamp AS bucket_at,
    groups.group_key,
    COUNT(DISTINCT t.id)::float8 AS trace_value
  FROM traces t
  JOIN LATERAL (
    SELECT DISTINCT
      CASE $1::text
        WHEN 'apiKey' THEN COALESCE(r.api_key_id::text, '')
        WHEN 'model' THEN COALESCE(r.model, '')
        WHEN 'upstreamModel' THEN COALESCE(r.upstream_model, '')
        WHEN 'provider' THEN COALESCE(r.provider_id::text, '')
      END AS group_key
    FROM request r
    WHERE r.parent_span_id = t.parent_span_id
      AND r.created_at >= t.first_request_at
      AND r.created_at <= t.last_request_at
      AND r.type = 1
      AND ($4::int IS NULL OR r.api_key_id = $4::int)
      AND ($5::text IS NULL OR r.model = $5::text)
      AND ($6::text IS NULL OR r.upstream_model = $6::text)
      AND ($7::int IS NULL OR r.provider_id = $7::int)
  ) groups ON true
  WHERE $1::text <> 'none'
    AND t.last_request_at >= $2::timestamp
    AND t.last_request_at < $3::timestamp
  GROUP BY bucket_at, groups.group_key
)
SELECT
  buckets.bucket_at,
  COALESCE(groups.group_key, '')::text AS group_key,
  COALESCE(
    CASE $1::text
      WHEN 'none' THEN '总量'
      WHEN 'apiKey' THEN api_key.name
      WHEN 'provider' THEN provider.name
      ELSE NULL
    END,
    COALESCE(groups.group_key, '')
  )::text AS group_label,
  COALESCE(metric_rows.trace_value, 0)::float8 AS trace_value
FROM buckets
CROSS JOIN (SELECT group_key FROM groups UNION SELECT '' WHERE NOT EXISTS (SELECT 1 FROM groups)) groups
LEFT JOIN metric_rows ON metric_rows.bucket_at = buckets.bucket_at AND metric_rows.group_key = groups.group_key
LEFT JOIN api_key ON $1::text = 'apiKey'
  AND groups.group_key <> ''
  AND api_key.id = groups.group_key::int
LEFT JOIN provider ON $1::text = 'provider'
  AND groups.group_key <> ''
  AND provider.id = groups.group_key::int
ORDER BY buckets.bucket_at ASC, group_label ASC
`

type GetOverviewHourlyTraceSeriesParams struct {
	Dimension     string           `json:"dimension"`
	StartAt       pgtype.Timestamp `json:"startAt"`
	EndAt         pgtype.Timestamp `json:"endAt"`
	ApiKeyID      pgtype.Int4      `json:"apiKeyId"`
	Model         pgtype.Text      `json:"model"`
	UpstreamModel pgtype.Text      `json:"upstreamModel"`
	ProviderID    pgtype.Int4      `json:"providerId"`
}

type GetOverviewHourlyTraceSeriesRow struct {
	BucketAt   pgtype.Timestamp `json:"bucketAt"`
	GroupKey   string           `json:"groupKey"`
	GroupLabel string           `json:"groupLabel"`
	TraceValue float64          `json:"traceValue"`
}

func (q *Queries) GetOverviewHourlyTraceSeries(ctx context.Context, arg GetOverviewHourlyTraceSeriesParams) ([]GetOverviewHourlyTraceSeriesRow, error) {
	rows, err := q.db.Query(ctx, getOverviewHourlyTraceSeries,
		arg.Dimension,
		arg.StartAt,
		arg.EndAt,
		arg.ApiKeyID,
		arg.Model,
		arg.UpstreamModel,
		arg.ProviderID,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetOverviewHourlyTraceSeriesRow
	for rows.Next() {
		var i GetOverviewHourlyTraceSeriesRow
		if err := rows.Scan(
			&i.BucketAt,
			&i.GroupKey,
			&i.GroupLabel,
			&i.TraceValue,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getOverviewSummary = `-- name: GetOverviewSummary :one
SELECT
  COALESCE(SUM(request_count), 0)::bigint AS total_requests,
  COALESCE(SUM(total_tokens), 0)::bigint AS total_tokens
FROM request_overview_hourly
WHERE bucket_at >= $1::timestamp
  AND bucket_at < $2::timestamp
  AND ($3::int IS NULL OR api_key_id = $3::int)
  AND ($4::text IS NULL OR model = $4::text)
  AND ($5::text IS NULL OR upstream_model = $5::text)
  AND ($6::int IS NULL OR provider_id = $6::int)
`

type GetOverviewSummaryParams struct {
	StartAt       pgtype.Timestamp `json:"startAt"`
	EndAt         pgtype.Timestamp `json:"endAt"`
	ApiKeyID      pgtype.Int4      `json:"apiKeyId"`
	Model         pgtype.Text      `json:"model"`
	UpstreamModel pgtype.Text      `json:"upstreamModel"`
	ProviderID    pgtype.Int4      `json:"providerId"`
}

type GetOverviewSummaryRow struct {
	TotalRequests int64 `json:"totalRequests"`
	TotalTokens   int64 `json:"totalTokens"`
}

func (q *Queries) GetOverviewSummary(ctx context.Context, arg GetOverviewSummaryParams) (GetOverviewSummaryRow, error) {
	row := q.db.QueryRow(ctx, getOverviewSummary,
		arg.StartAt,
		arg.EndAt,
		arg.ApiKeyID,
		arg.Model,
		arg.UpstreamModel,
		arg.ProviderID,
	)
	var i GetOverviewSummaryRow
	err := row.Scan(&i.TotalRequests, &i.TotalTokens)
	return i, err
}

const getOverviewTraceCount = `-- name: GetOverviewTraceCount :one
SELECT COUNT(*)::bigint AS trace_count
FROM traces t
WHERE t.last_request_at >= $1::timestamp
  AND t.last_request_at < $2::timestamp
  AND (
    (
      $3::int IS NULL
      AND $4::text IS NULL
      AND $5::text IS NULL
      AND $6::int IS NULL
    )
    OR EXISTS (
      SELECT 1
      FROM request r
      WHERE r.parent_span_id = t.parent_span_id
        AND r.created_at >= t.first_request_at
        AND r.created_at <= t.last_request_at
        AND r.type = 1
        AND ($3::int IS NULL OR r.api_key_id = $3::int)
        AND ($4::text IS NULL OR r.model = $4::text)
        AND ($5::text IS NULL OR r.upstream_model = $5::text)
        AND ($6::int IS NULL OR r.provider_id = $6::int)
    )
  )
`

type GetOverviewTraceCountParams struct {
	StartAt       pgtype.Timestamp `json:"startAt"`
	EndAt         pgtype.Timestamp `json:"endAt"`
	ApiKeyID      pgtype.Int4      `json:"apiKeyId"`
	Model         pgtype.Text      `json:"model"`
	UpstreamModel pgtype.Text      `json:"upstreamModel"`
	ProviderID    pgtype.Int4      `json:"providerId"`
}

func (q *Queries) GetOverviewTraceCount(ctx context.Context, arg GetOverviewTraceCountParams) (int64, error) {
	row := q.db.QueryRow(ctx, getOverviewTraceCount,
		arg.StartAt,
		arg.EndAt,
		arg.ApiKeyID,
		arg.Model,
		arg.UpstreamModel,
		arg.ProviderID,
	)
	var trace_count int64
	err := row.Scan(&trace_count)
	return trace_count, err
}
