// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: overview.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countTraces = `-- name: CountTraces :one
SELECT COUNT(*)::bigint AS trace_count
FROM traces
WHERE last_request_at >= $1::timestamp
  AND last_request_at < $2::timestamp
`

type CountTracesParams struct {
	StartAt pgtype.Timestamp `json:"startAt"`
	EndAt   pgtype.Timestamp `json:"endAt"`
}

func (q *Queries) CountTraces(ctx context.Context, arg CountTracesParams) (int64, error) {
	row := q.db.QueryRow(ctx, countTraces, arg.StartAt, arg.EndAt)
	var trace_count int64
	err := row.Scan(&trace_count)
	return trace_count, err
}

const countTracesFiltered = `-- name: CountTracesFiltered :one
SELECT COUNT(*)::bigint AS trace_count
FROM traces t
WHERE t.last_request_at >= $1::timestamp
  AND t.last_request_at < $2::timestamp
  AND EXISTS (
    SELECT 1
    FROM request r
    WHERE r.parent_span_id = t.parent_span_id
      AND r.created_at >= t.first_request_at
      AND r.created_at <= t.last_request_at
      AND r.type = 1
      AND ($3::int IS NULL OR r.api_key_id = $3::int)
      AND ($4::text IS NULL OR r.model = $4::text)
      AND ($5::text IS NULL OR r.upstream_model = $5::text)
      AND ($6::int IS NULL OR r.provider_id = $6::int)
  )
`

type CountTracesFilteredParams struct {
	StartAt       pgtype.Timestamp `json:"startAt"`
	EndAt         pgtype.Timestamp `json:"endAt"`
	ApiKeyID      pgtype.Int4      `json:"apiKeyId"`
	Model         pgtype.Text      `json:"model"`
	UpstreamModel pgtype.Text      `json:"upstreamModel"`
	ProviderID    pgtype.Int4      `json:"providerId"`
}

func (q *Queries) CountTracesFiltered(ctx context.Context, arg CountTracesFilteredParams) (int64, error) {
	row := q.db.QueryRow(ctx, countTracesFiltered,
		arg.StartAt,
		arg.EndAt,
		arg.ApiKeyID,
		arg.Model,
		arg.UpstreamModel,
		arg.ProviderID,
	)
	var trace_count int64
	err := row.Scan(&trace_count)
	return trace_count, err
}

const getOverviewTotals = `-- name: GetOverviewTotals :one
WITH filtered AS (
  SELECT
    cost_currency,
    request_count,
    input_tokens,
    cache_read_tokens,
    output_tokens,
    cache_write_tokens,
    cache_write_1h_tokens,
    cost
  FROM request_overview_hourly
  WHERE bucket_at >= $1::timestamp
    AND bucket_at < $2::timestamp
    AND ($3::int IS NULL OR api_key_id = $3::int)
    AND ($4::text IS NULL OR model = $4::text)
    AND ($5::text IS NULL OR upstream_model = $5::text)
    AND ($6::int IS NULL OR provider_id = $6::int)
), totals AS (
  SELECT
    COALESCE(SUM(
      input_tokens + cache_read_tokens + output_tokens + cache_write_tokens + cache_write_1h_tokens
    ), 0)::bigint AS total_tokens,
    COALESCE(SUM(request_count), 0)::bigint AS total_requests
  FROM filtered
), cost_groups AS (
  SELECT cost_currency AS currency, SUM(cost)::float8 AS amount
  FROM filtered
  WHERE cost_currency IS NOT NULL AND cost_currency <> ''
  GROUP BY cost_currency
), cost_json AS (
  SELECT COALESCE(
    jsonb_agg(
      jsonb_build_object('currency', currency, 'amount', amount)
      ORDER BY currency
    ),
    '[]'::jsonb
  )::jsonb AS costs
  FROM cost_groups
)
SELECT
  totals.total_tokens,
  totals.total_requests,
  cost_json.costs::jsonb AS costs
FROM totals CROSS JOIN cost_json
`

type GetOverviewTotalsParams struct {
	StartAt       pgtype.Timestamp `json:"startAt"`
	EndAt         pgtype.Timestamp `json:"endAt"`
	ApiKeyID      pgtype.Int4      `json:"apiKeyId"`
	Model         pgtype.Text      `json:"model"`
	UpstreamModel pgtype.Text      `json:"upstreamModel"`
	ProviderID    pgtype.Int4      `json:"providerId"`
}

type GetOverviewTotalsRow struct {
	TotalTokens   int64  `json:"totalTokens"`
	TotalRequests int64  `json:"totalRequests"`
	Costs         []byte `json:"costs"`
}

func (q *Queries) GetOverviewTotals(ctx context.Context, arg GetOverviewTotalsParams) (GetOverviewTotalsRow, error) {
	row := q.db.QueryRow(ctx, getOverviewTotals,
		arg.StartAt,
		arg.EndAt,
		arg.ApiKeyID,
		arg.Model,
		arg.UpstreamModel,
		arg.ProviderID,
	)
	var i GetOverviewTotalsRow
	err := row.Scan(&i.TotalTokens, &i.TotalRequests, &i.Costs)
	return i, err
}

const listOverviewDistribution = `-- name: ListOverviewDistribution :many
SELECT
  CASE $1::text
    WHEN 'apiKey' THEN COALESCE(api_key_id::text, '')
    WHEN 'model' THEN COALESCE(model, '')
    WHEN 'upstreamModel' THEN COALESCE(upstream_model, '')
    WHEN 'provider' THEN COALESCE(provider_id::text, '')
    ELSE ''
  END AS key,
  SUM(
    input_tokens + cache_read_tokens + output_tokens + cache_write_tokens + cache_write_1h_tokens
  )::bigint AS total_tokens,
  SUM(request_count)::bigint AS request_count
FROM request_overview_hourly
WHERE bucket_at >= $2::timestamp
  AND bucket_at < $3::timestamp
  AND ($4::int IS NULL OR api_key_id = $4::int)
  AND ($5::text IS NULL OR model = $5::text)
  AND ($6::text IS NULL OR upstream_model = $6::text)
  AND ($7::int IS NULL OR provider_id = $7::int)
GROUP BY key
ORDER BY total_tokens DESC, key ASC
`

type ListOverviewDistributionParams struct {
	Dimension     string           `json:"dimension"`
	StartAt       pgtype.Timestamp `json:"startAt"`
	EndAt         pgtype.Timestamp `json:"endAt"`
	ApiKeyID      pgtype.Int4      `json:"apiKeyId"`
	Model         pgtype.Text      `json:"model"`
	UpstreamModel pgtype.Text      `json:"upstreamModel"`
	ProviderID    pgtype.Int4      `json:"providerId"`
}

type ListOverviewDistributionRow struct {
	Key          string `json:"key"`
	TotalTokens  int64  `json:"totalTokens"`
	RequestCount int64  `json:"requestCount"`
}

func (q *Queries) ListOverviewDistribution(ctx context.Context, arg ListOverviewDistributionParams) ([]ListOverviewDistributionRow, error) {
	rows, err := q.db.Query(ctx, listOverviewDistribution,
		arg.Dimension,
		arg.StartAt,
		arg.EndAt,
		arg.ApiKeyID,
		arg.Model,
		arg.UpstreamModel,
		arg.ProviderID,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListOverviewDistributionRow
	for rows.Next() {
		var i ListOverviewDistributionRow
		if err := rows.Scan(&i.Key, &i.TotalTokens, &i.RequestCount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOverviewDistributionCosts = `-- name: ListOverviewDistributionCosts :many
SELECT
  CASE $1::text
    WHEN 'apiKey' THEN COALESCE(api_key_id::text, '')
    WHEN 'model' THEN COALESCE(model, '')
    WHEN 'upstreamModel' THEN COALESCE(upstream_model, '')
    WHEN 'provider' THEN COALESCE(provider_id::text, '')
    ELSE ''
  END AS key,
  cost_currency::text AS currency,
  SUM(cost)::float8 AS amount
FROM request_overview_hourly
WHERE bucket_at >= $2::timestamp
  AND bucket_at < $3::timestamp
  AND ($4::int IS NULL OR api_key_id = $4::int)
  AND ($5::text IS NULL OR model = $5::text)
  AND ($6::text IS NULL OR upstream_model = $6::text)
  AND ($7::int IS NULL OR provider_id = $7::int)
  AND cost_currency IS NOT NULL
  AND cost_currency <> ''
GROUP BY key, currency
ORDER BY key ASC, currency ASC
`

type ListOverviewDistributionCostsParams struct {
	Dimension     string           `json:"dimension"`
	StartAt       pgtype.Timestamp `json:"startAt"`
	EndAt         pgtype.Timestamp `json:"endAt"`
	ApiKeyID      pgtype.Int4      `json:"apiKeyId"`
	Model         pgtype.Text      `json:"model"`
	UpstreamModel pgtype.Text      `json:"upstreamModel"`
	ProviderID    pgtype.Int4      `json:"providerId"`
}

type ListOverviewDistributionCostsRow struct {
	Key      string  `json:"key"`
	Currency string  `json:"currency"`
	Amount   float64 `json:"amount"`
}

func (q *Queries) ListOverviewDistributionCosts(ctx context.Context, arg ListOverviewDistributionCostsParams) ([]ListOverviewDistributionCostsRow, error) {
	rows, err := q.db.Query(ctx, listOverviewDistributionCosts,
		arg.Dimension,
		arg.StartAt,
		arg.EndAt,
		arg.ApiKeyID,
		arg.Model,
		arg.UpstreamModel,
		arg.ProviderID,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListOverviewDistributionCostsRow
	for rows.Next() {
		var i ListOverviewDistributionCostsRow
		if err := rows.Scan(&i.Key, &i.Currency, &i.Amount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOverviewSeriesMetrics = `-- name: ListOverviewSeriesMetrics :many
SELECT
  bucket_at::timestamp AS bucket_at,
  CASE $1::text
    WHEN 'apiKey' THEN COALESCE(api_key_id::text, '')
    WHEN 'model' THEN COALESCE(model, '')
    WHEN 'upstreamModel' THEN COALESCE(upstream_model, '')
    WHEN 'provider' THEN COALESCE(provider_id::text, '')
    ELSE ''
  END AS group_key,
  COALESCE(cost_currency, '')::text AS currency,
  SUM(input_tokens + cache_read_tokens + output_tokens + cache_write_tokens + cache_write_1h_tokens)::bigint AS tokens,
  SUM(request_count)::bigint AS requests,
  SUM(cost)::float8 AS cost
FROM request_overview_hourly
WHERE bucket_at >= $2::timestamp
  AND bucket_at < $3::timestamp
  AND ($4::int IS NULL OR api_key_id = $4::int)
  AND ($5::text IS NULL OR model = $5::text)
  AND ($6::text IS NULL OR upstream_model = $6::text)
  AND ($7::int IS NULL OR provider_id = $7::int)
GROUP BY bucket_at, group_key, currency
ORDER BY bucket_at ASC, group_key ASC, currency ASC
`

type ListOverviewSeriesMetricsParams struct {
	Dimension     string           `json:"dimension"`
	StartAt       pgtype.Timestamp `json:"startAt"`
	EndAt         pgtype.Timestamp `json:"endAt"`
	ApiKeyID      pgtype.Int4      `json:"apiKeyId"`
	Model         pgtype.Text      `json:"model"`
	UpstreamModel pgtype.Text      `json:"upstreamModel"`
	ProviderID    pgtype.Int4      `json:"providerId"`
}

type ListOverviewSeriesMetricsRow struct {
	BucketAt pgtype.Timestamp `json:"bucketAt"`
	GroupKey string           `json:"groupKey"`
	Currency string           `json:"currency"`
	Tokens   int64            `json:"tokens"`
	Requests int64            `json:"requests"`
	Cost     float64          `json:"cost"`
}

func (q *Queries) ListOverviewSeriesMetrics(ctx context.Context, arg ListOverviewSeriesMetricsParams) ([]ListOverviewSeriesMetricsRow, error) {
	rows, err := q.db.Query(ctx, listOverviewSeriesMetrics,
		arg.Dimension,
		arg.StartAt,
		arg.EndAt,
		arg.ApiKeyID,
		arg.Model,
		arg.UpstreamModel,
		arg.ProviderID,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListOverviewSeriesMetricsRow
	for rows.Next() {
		var i ListOverviewSeriesMetricsRow
		if err := rows.Scan(
			&i.BucketAt,
			&i.GroupKey,
			&i.Currency,
			&i.Tokens,
			&i.Requests,
			&i.Cost,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOverviewSeriesTraces = `-- name: ListOverviewSeriesTraces :many
SELECT
  time_bucket(INTERVAL '1 hour', r.created_at)::timestamp AS bucket_at,
  CASE $1::text
    WHEN 'apiKey' THEN COALESCE(r.api_key_id::text, '')
    WHEN 'model' THEN COALESCE(r.model, '')
    WHEN 'upstreamModel' THEN COALESCE(r.upstream_model, '')
    WHEN 'provider' THEN COALESCE(r.provider_id::text, '')
    ELSE ''
  END AS group_key,
  COUNT(DISTINCT r.parent_span_id)::bigint AS trace_count
FROM request r
WHERE r.created_at >= $2::timestamp
  AND r.created_at < $3::timestamp
  AND r.type = 1
  AND r.parent_span_id IS NOT NULL
  AND r.parent_span_id <> ''
  AND ($4::int IS NULL OR r.api_key_id = $4::int)
  AND ($5::text IS NULL OR r.model = $5::text)
  AND ($6::text IS NULL OR r.upstream_model = $6::text)
  AND ($7::int IS NULL OR r.provider_id = $7::int)
GROUP BY bucket_at, group_key
ORDER BY bucket_at ASC, group_key ASC
`

type ListOverviewSeriesTracesParams struct {
	Dimension     string           `json:"dimension"`
	StartAt       pgtype.Timestamp `json:"startAt"`
	EndAt         pgtype.Timestamp `json:"endAt"`
	ApiKeyID      pgtype.Int4      `json:"apiKeyId"`
	Model         pgtype.Text      `json:"model"`
	UpstreamModel pgtype.Text      `json:"upstreamModel"`
	ProviderID    pgtype.Int4      `json:"providerId"`
}

type ListOverviewSeriesTracesRow struct {
	BucketAt   pgtype.Timestamp `json:"bucketAt"`
	GroupKey   string           `json:"groupKey"`
	TraceCount int64            `json:"traceCount"`
}

func (q *Queries) ListOverviewSeriesTraces(ctx context.Context, arg ListOverviewSeriesTracesParams) ([]ListOverviewSeriesTracesRow, error) {
	rows, err := q.db.Query(ctx, listOverviewSeriesTraces,
		arg.Dimension,
		arg.StartAt,
		arg.EndAt,
		arg.ApiKeyID,
		arg.Model,
		arg.UpstreamModel,
		arg.ProviderID,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListOverviewSeriesTracesRow
	for rows.Next() {
		var i ListOverviewSeriesTracesRow
		if err := rows.Scan(&i.BucketAt, &i.GroupKey, &i.TraceCount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOverviewTraceCountsByDimension = `-- name: ListOverviewTraceCountsByDimension :many
SELECT
  CASE $1::text
    WHEN 'apiKey' THEN COALESCE(r.api_key_id::text, '')
    WHEN 'model' THEN COALESCE(r.model, '')
    WHEN 'upstreamModel' THEN COALESCE(r.upstream_model, '')
    WHEN 'provider' THEN COALESCE(r.provider_id::text, '')
    ELSE ''
  END AS key,
  COUNT(DISTINCT r.parent_span_id)::bigint AS trace_count
FROM request r
WHERE r.created_at >= $2::timestamp
  AND r.created_at < $3::timestamp
  AND r.type = 1
  AND r.parent_span_id IS NOT NULL
  AND r.parent_span_id <> ''
  AND ($4::int IS NULL OR r.api_key_id = $4::int)
  AND ($5::text IS NULL OR r.model = $5::text)
  AND ($6::text IS NULL OR r.upstream_model = $6::text)
  AND ($7::int IS NULL OR r.provider_id = $7::int)
GROUP BY key
`

type ListOverviewTraceCountsByDimensionParams struct {
	Dimension     string           `json:"dimension"`
	StartAt       pgtype.Timestamp `json:"startAt"`
	EndAt         pgtype.Timestamp `json:"endAt"`
	ApiKeyID      pgtype.Int4      `json:"apiKeyId"`
	Model         pgtype.Text      `json:"model"`
	UpstreamModel pgtype.Text      `json:"upstreamModel"`
	ProviderID    pgtype.Int4      `json:"providerId"`
}

type ListOverviewTraceCountsByDimensionRow struct {
	Key        string `json:"key"`
	TraceCount int64  `json:"traceCount"`
}

func (q *Queries) ListOverviewTraceCountsByDimension(ctx context.Context, arg ListOverviewTraceCountsByDimensionParams) ([]ListOverviewTraceCountsByDimensionRow, error) {
	rows, err := q.db.Query(ctx, listOverviewTraceCountsByDimension,
		arg.Dimension,
		arg.StartAt,
		arg.EndAt,
		arg.ApiKeyID,
		arg.Model,
		arg.UpstreamModel,
		arg.ProviderID,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListOverviewTraceCountsByDimensionRow
	for rows.Next() {
		var i ListOverviewTraceCountsByDimensionRow
		if err := rows.Scan(&i.Key, &i.TraceCount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
