// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: project.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteProject = `-- name: DeleteProject :exec
DELETE FROM project WHERE id = $1 AND user_id = $2
`

type DeleteProjectParams struct {
	ID     int32 `json:"id"`
	UserID int64 `json:"userId"`
}

func (q *Queries) DeleteProject(ctx context.Context, arg DeleteProjectParams) error {
	_, err := q.db.Exec(ctx, deleteProject, arg.ID, arg.UserID)
	return err
}

const getProject = `-- name: GetProject :one
SELECT id, name, paths, first_seen_at, last_seen_at, created_at, updated_at, auto_created, user_id FROM project WHERE id = $1 AND user_id = $2 LIMIT 1
`

type GetProjectParams struct {
	ID     int32 `json:"id"`
	UserID int64 `json:"userId"`
}

func (q *Queries) GetProject(ctx context.Context, arg GetProjectParams) (Project, error) {
	row := q.db.QueryRow(ctx, getProject, arg.ID, arg.UserID)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Paths,
		&i.FirstSeenAt,
		&i.LastSeenAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.AutoCreated,
		&i.UserID,
	)
	return i, err
}

const getProjectByName = `-- name: GetProjectByName :one
SELECT id, name, paths, first_seen_at, last_seen_at, created_at, updated_at, auto_created, user_id FROM project WHERE user_id = $1 AND name = $2 LIMIT 1
`

type GetProjectByNameParams struct {
	UserID int64  `json:"userId"`
	Name   string `json:"name"`
}

func (q *Queries) GetProjectByName(ctx context.Context, arg GetProjectByNameParams) (Project, error) {
	row := q.db.QueryRow(ctx, getProjectByName, arg.UserID, arg.Name)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Paths,
		&i.FirstSeenAt,
		&i.LastSeenAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.AutoCreated,
		&i.UserID,
	)
	return i, err
}

const insertAutoCreatedProject = `-- name: InsertAutoCreatedProject :one
INSERT INTO project (name, paths, auto_created, user_id) VALUES ($1, $2, true, $3) RETURNING id, name, paths, first_seen_at, last_seen_at, created_at, updated_at, auto_created, user_id
`

type InsertAutoCreatedProjectParams struct {
	Name   string `json:"name"`
	Paths  []byte `json:"paths"`
	UserID int64  `json:"userId"`
}

func (q *Queries) InsertAutoCreatedProject(ctx context.Context, arg InsertAutoCreatedProjectParams) (Project, error) {
	row := q.db.QueryRow(ctx, insertAutoCreatedProject, arg.Name, arg.Paths, arg.UserID)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Paths,
		&i.FirstSeenAt,
		&i.LastSeenAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.AutoCreated,
		&i.UserID,
	)
	return i, err
}

const insertProject = `-- name: InsertProject :one
INSERT INTO project (name, paths, user_id) VALUES ($1, $2, $3) RETURNING id, name, paths, first_seen_at, last_seen_at, created_at, updated_at, auto_created, user_id
`

type InsertProjectParams struct {
	Name   string `json:"name"`
	Paths  []byte `json:"paths"`
	UserID int64  `json:"userId"`
}

func (q *Queries) InsertProject(ctx context.Context, arg InsertProjectParams) (Project, error) {
	row := q.db.QueryRow(ctx, insertProject, arg.Name, arg.Paths, arg.UserID)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Paths,
		&i.FirstSeenAt,
		&i.LastSeenAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.AutoCreated,
		&i.UserID,
	)
	return i, err
}

const listProjects = `-- name: ListProjects :many
SELECT id, name, paths, first_seen_at, last_seen_at, created_at, updated_at, auto_created, user_id FROM project WHERE user_id = $1 ORDER BY name ASC
`

func (q *Queries) ListProjects(ctx context.Context, userID int64) ([]Project, error) {
	rows, err := q.db.Query(ctx, listProjects, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Project
	for rows.Next() {
		var i Project
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Paths,
			&i.FirstSeenAt,
			&i.LastSeenAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.AutoCreated,
			&i.UserID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const matchProjectByPaths = `-- name: MatchProjectByPaths :one
SELECT p.id
FROM project AS p
CROSS JOIN LATERAL jsonb_array_elements_text(p.paths) AS path
WHERE p.user_id = $1
  AND path = ANY($2::text[])
ORDER BY length(path) DESC, p.id ASC
LIMIT 1
`

type MatchProjectByPathsParams struct {
	UserID         int64    `json:"userId"`
	CandidatePaths []string `json:"candidatePaths"`
}

func (q *Queries) MatchProjectByPaths(ctx context.Context, arg MatchProjectByPathsParams) (int32, error) {
	row := q.db.QueryRow(ctx, matchProjectByPaths, arg.UserID, arg.CandidatePaths)
	var id int32
	err := row.Scan(&id)
	return id, err
}

const mergeProjectReassignRequests = `-- name: MergeProjectReassignRequests :execrows
UPDATE request SET project_id = $1
WHERE project_id = $2
`

type MergeProjectReassignRequestsParams struct {
	TargetID pgtype.Int4 `json:"targetId"`
	SourceID pgtype.Int4 `json:"sourceId"`
}

func (q *Queries) MergeProjectReassignRequests(ctx context.Context, arg MergeProjectReassignRequestsParams) (int64, error) {
	result, err := q.db.Exec(ctx, mergeProjectReassignRequests, arg.TargetID, arg.SourceID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const mergeProjectUpdateTarget = `-- name: MergeProjectUpdateTarget :one
UPDATE project AS p
SET paths = COALESCE((
  SELECT jsonb_agg(DISTINCT elem)
  FROM (
    SELECT jsonb_array_elements_text(p.paths) AS elem
    UNION
    SELECT jsonb_array_elements_text(src.paths) AS elem
    FROM project AS src WHERE src.id = $1
  ) all_paths
), p.paths),
    first_seen_at = LEAST(p.first_seen_at, (
      SELECT first_seen_at FROM project WHERE id = $1
    )),
    last_seen_at  = GREATEST(p.last_seen_at, (
      SELECT last_seen_at FROM project WHERE id = $1
    )),
    updated_at = now()
WHERE p.id = $2
RETURNING id, name, paths, first_seen_at, last_seen_at, created_at, updated_at, auto_created, user_id
`

type MergeProjectUpdateTargetParams struct {
	SourceID int32 `json:"sourceId"`
	TargetID int32 `json:"targetId"`
}

func (q *Queries) MergeProjectUpdateTarget(ctx context.Context, arg MergeProjectUpdateTargetParams) (Project, error) {
	row := q.db.QueryRow(ctx, mergeProjectUpdateTarget, arg.SourceID, arg.TargetID)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Paths,
		&i.FirstSeenAt,
		&i.LastSeenAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.AutoCreated,
		&i.UserID,
	)
	return i, err
}

const updateProject = `-- name: UpdateProject :one
UPDATE project SET name = $3, paths = $4, updated_at = now() WHERE id = $1 AND user_id = $2 RETURNING id, name, paths, first_seen_at, last_seen_at, created_at, updated_at, auto_created, user_id
`

type UpdateProjectParams struct {
	ID     int32  `json:"id"`
	UserID int64  `json:"userId"`
	Name   string `json:"name"`
	Paths  []byte `json:"paths"`
}

func (q *Queries) UpdateProject(ctx context.Context, arg UpdateProjectParams) (Project, error) {
	row := q.db.QueryRow(ctx, updateProject,
		arg.ID,
		arg.UserID,
		arg.Name,
		arg.Paths,
	)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Paths,
		&i.FirstSeenAt,
		&i.LastSeenAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.AutoCreated,
		&i.UserID,
	)
	return i, err
}

const upsertProjectSeen = `-- name: UpsertProjectSeen :exec
UPDATE project
SET first_seen_at = LEAST(COALESCE(first_seen_at, $2::timestamp), $2::timestamp),
    last_seen_at  = GREATEST(COALESCE(last_seen_at,  $2::timestamp), $2::timestamp),
    updated_at    = now()
WHERE id = $1
`

type UpsertProjectSeenParams struct {
	ID     int32            `json:"id"`
	SeenAt pgtype.Timestamp `json:"seenAt"`
}

func (q *Queries) UpsertProjectSeen(ctx context.Context, arg UpsertProjectSeenParams) error {
	_, err := q.db.Exec(ctx, upsertProjectSeen, arg.ID, arg.SeenAt)
	return err
}
