// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: project.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteProject = `-- name: DeleteProject :exec
DELETE FROM project WHERE id = $1
`

func (q *Queries) DeleteProject(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, deleteProject, id)
	return err
}

const getProject = `-- name: GetProject :one
SELECT id, name, paths, first_seen_at, last_seen_at, created_at, updated_at FROM project WHERE id = $1 LIMIT 1
`

func (q *Queries) GetProject(ctx context.Context, id int32) (Project, error) {
	row := q.db.QueryRow(ctx, getProject, id)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Paths,
		&i.FirstSeenAt,
		&i.LastSeenAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getProjectByName = `-- name: GetProjectByName :one
SELECT id, name, paths, first_seen_at, last_seen_at, created_at, updated_at FROM project WHERE name = $1 LIMIT 1
`

func (q *Queries) GetProjectByName(ctx context.Context, name string) (Project, error) {
	row := q.db.QueryRow(ctx, getProjectByName, name)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Paths,
		&i.FirstSeenAt,
		&i.LastSeenAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertProject = `-- name: InsertProject :one
INSERT INTO project (name, paths) VALUES ($1, $2) RETURNING id, name, paths, first_seen_at, last_seen_at, created_at, updated_at
`

type InsertProjectParams struct {
	Name  string `json:"name"`
	Paths []byte `json:"paths"`
}

func (q *Queries) InsertProject(ctx context.Context, arg InsertProjectParams) (Project, error) {
	row := q.db.QueryRow(ctx, insertProject, arg.Name, arg.Paths)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Paths,
		&i.FirstSeenAt,
		&i.LastSeenAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listProjectPaths = `-- name: ListProjectPaths :many
SELECT id AS project_id, jsonb_array_elements_text(paths) AS path
FROM project
WHERE jsonb_array_length(paths) > 0
`

type ListProjectPathsRow struct {
	ProjectID int32  `json:"projectId"`
	Path      string `json:"path"`
}

func (q *Queries) ListProjectPaths(ctx context.Context) ([]ListProjectPathsRow, error) {
	rows, err := q.db.Query(ctx, listProjectPaths)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListProjectPathsRow
	for rows.Next() {
		var i ListProjectPathsRow
		if err := rows.Scan(&i.ProjectID, &i.Path); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProjects = `-- name: ListProjects :many
SELECT id, name, paths, first_seen_at, last_seen_at, created_at, updated_at FROM project ORDER BY name ASC
`

func (q *Queries) ListProjects(ctx context.Context) ([]Project, error) {
	rows, err := q.db.Query(ctx, listProjects)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Project
	for rows.Next() {
		var i Project
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Paths,
			&i.FirstSeenAt,
			&i.LastSeenAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateProject = `-- name: UpdateProject :one
UPDATE project SET name = $2, paths = $3, updated_at = now() WHERE id = $1 RETURNING id, name, paths, first_seen_at, last_seen_at, created_at, updated_at
`

type UpdateProjectParams struct {
	ID    int32  `json:"id"`
	Name  string `json:"name"`
	Paths []byte `json:"paths"`
}

func (q *Queries) UpdateProject(ctx context.Context, arg UpdateProjectParams) (Project, error) {
	row := q.db.QueryRow(ctx, updateProject, arg.ID, arg.Name, arg.Paths)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Paths,
		&i.FirstSeenAt,
		&i.LastSeenAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertProjectSeen = `-- name: UpsertProjectSeen :exec
UPDATE project
SET first_seen_at = LEAST(COALESCE(first_seen_at, $2::timestamp), $2::timestamp),
    last_seen_at  = GREATEST(COALESCE(last_seen_at,  $2::timestamp), $2::timestamp),
    updated_at    = now()
WHERE id = $1
`

type UpsertProjectSeenParams struct {
	ID     int32            `json:"id"`
	SeenAt pgtype.Timestamp `json:"seenAt"`
}

func (q *Queries) UpsertProjectSeen(ctx context.Context, arg UpsertProjectSeenParams) error {
	_, err := q.db.Exec(ctx, upsertProjectSeen, arg.ID, arg.SeenAt)
	return err
}
