// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: provider.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createProvider = `-- name: CreateProvider :one
INSERT INTO provider (name, credentials, priority, provider_models, annotations, disabled, proxy_url, models_endpoint_url, models_endpoint_resolver, supports_native_web_search) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10) RETURNING id, name, credentials, priority, provider_models, annotations, disabled, proxy_url, models_endpoint_url, models_endpoint_resolver, supports_native_web_search
`

type CreateProviderParams struct {
	Name                    string      `json:"name"`
	Credentials             string      `json:"credentials"`
	Priority                int32       `json:"priority"`
	ProviderModels          []byte      `json:"providerModels"`
	Annotations             []byte      `json:"annotations"`
	Disabled                bool        `json:"disabled"`
	ProxyUrl                pgtype.Text `json:"proxyUrl"`
	ModelsEndpointUrl       string      `json:"modelsEndpointUrl"`
	ModelsEndpointResolver  int32       `json:"modelsEndpointResolver"`
	SupportsNativeWebSearch bool        `json:"supportsNativeWebSearch"`
}

func (q *Queries) CreateProvider(ctx context.Context, arg CreateProviderParams) (Provider, error) {
	row := q.db.QueryRow(ctx, createProvider,
		arg.Name,
		arg.Credentials,
		arg.Priority,
		arg.ProviderModels,
		arg.Annotations,
		arg.Disabled,
		arg.ProxyUrl,
		arg.ModelsEndpointUrl,
		arg.ModelsEndpointResolver,
		arg.SupportsNativeWebSearch,
	)
	var i Provider
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Credentials,
		&i.Priority,
		&i.ProviderModels,
		&i.Annotations,
		&i.Disabled,
		&i.ProxyUrl,
		&i.ModelsEndpointUrl,
		&i.ModelsEndpointResolver,
		&i.SupportsNativeWebSearch,
	)
	return i, err
}

const deleteProvider = `-- name: DeleteProvider :exec
DELETE FROM provider WHERE id = $1
`

func (q *Queries) DeleteProvider(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, deleteProvider, id)
	return err
}

const getProviderByID = `-- name: GetProviderByID :one
SELECT id, name, credentials, priority, provider_models, annotations, disabled, proxy_url, models_endpoint_url, models_endpoint_resolver, supports_native_web_search FROM provider WHERE id = $1 LIMIT 1
`

func (q *Queries) GetProviderByID(ctx context.Context, id int32) (Provider, error) {
	row := q.db.QueryRow(ctx, getProviderByID, id)
	var i Provider
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Credentials,
		&i.Priority,
		&i.ProviderModels,
		&i.Annotations,
		&i.Disabled,
		&i.ProxyUrl,
		&i.ModelsEndpointUrl,
		&i.ModelsEndpointResolver,
		&i.SupportsNativeWebSearch,
	)
	return i, err
}

const getProviders = `-- name: GetProviders :many
SELECT id, name, credentials, priority, provider_models, annotations, disabled, proxy_url, models_endpoint_url, models_endpoint_resolver, supports_native_web_search FROM provider ORDER BY priority DESC, id DESC
`

func (q *Queries) GetProviders(ctx context.Context) ([]Provider, error) {
	rows, err := q.db.Query(ctx, getProviders)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Provider
	for rows.Next() {
		var i Provider
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Credentials,
			&i.Priority,
			&i.ProviderModels,
			&i.Annotations,
			&i.Disabled,
			&i.ProxyUrl,
			&i.ModelsEndpointUrl,
			&i.ModelsEndpointResolver,
			&i.SupportsNativeWebSearch,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateProvider = `-- name: UpdateProvider :one
UPDATE provider
  SET
    name = CASE WHEN $1::bool THEN $2::text ELSE name END,
    credentials = CASE WHEN $3::bool THEN $4::text ELSE credentials END,
    priority = CASE WHEN $5::bool THEN $6::int ELSE priority END,
    provider_models = CASE WHEN $7::bool THEN $8::jsonb ELSE provider_models END,
    annotations = CASE WHEN $9::bool THEN $10::jsonb ELSE annotations END,
    disabled = CASE WHEN $11::bool THEN $12::bool ELSE disabled END,
    proxy_url = CASE WHEN $13::bool THEN $14::text ELSE proxy_url END,
    models_endpoint_url = CASE WHEN $15::bool THEN $16::text ELSE models_endpoint_url END,
    models_endpoint_resolver = CASE WHEN $17::bool THEN $18::int ELSE models_endpoint_resolver END,
    supports_native_web_search = CASE WHEN $19::bool THEN $20::bool ELSE supports_native_web_search END
  WHERE id = $21::int
  RETURNING id, name, credentials, priority, provider_models, annotations, disabled, proxy_url, models_endpoint_url, models_endpoint_resolver, supports_native_web_search
`

type UpdateProviderParams struct {
	SetName                    bool   `json:"setName"`
	Name                       string `json:"name"`
	SetCredentials             bool   `json:"setCredentials"`
	Credentials                string `json:"credentials"`
	SetPriority                bool   `json:"setPriority"`
	Priority                   int32  `json:"priority"`
	SetProviderModels          bool   `json:"setProviderModels"`
	ProviderModels             []byte `json:"providerModels"`
	SetAnnotations             bool   `json:"setAnnotations"`
	Annotations                []byte `json:"annotations"`
	SetDisabled                bool   `json:"setDisabled"`
	Disabled                   bool   `json:"disabled"`
	SetProxyUrl                bool   `json:"setProxyUrl"`
	ProxyUrl                   string `json:"proxyUrl"`
	SetModelsEndpointUrl       bool   `json:"setModelsEndpointUrl"`
	ModelsEndpointUrl          string `json:"modelsEndpointUrl"`
	SetModelsEndpointResolver  bool   `json:"setModelsEndpointResolver"`
	ModelsEndpointResolver     int32  `json:"modelsEndpointResolver"`
	SetSupportsNativeWebSearch bool   `json:"setSupportsNativeWebSearch"`
	SupportsNativeWebSearch    bool   `json:"supportsNativeWebSearch"`
	ID                         int32  `json:"id"`
}

func (q *Queries) UpdateProvider(ctx context.Context, arg UpdateProviderParams) (Provider, error) {
	row := q.db.QueryRow(ctx, updateProvider,
		arg.SetName,
		arg.Name,
		arg.SetCredentials,
		arg.Credentials,
		arg.SetPriority,
		arg.Priority,
		arg.SetProviderModels,
		arg.ProviderModels,
		arg.SetAnnotations,
		arg.Annotations,
		arg.SetDisabled,
		arg.Disabled,
		arg.SetProxyUrl,
		arg.ProxyUrl,
		arg.SetModelsEndpointUrl,
		arg.ModelsEndpointUrl,
		arg.SetModelsEndpointResolver,
		arg.ModelsEndpointResolver,
		arg.SetSupportsNativeWebSearch,
		arg.SupportsNativeWebSearch,
		arg.ID,
	)
	var i Provider
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Credentials,
		&i.Priority,
		&i.ProviderModels,
		&i.Annotations,
		&i.Disabled,
		&i.ProxyUrl,
		&i.ModelsEndpointUrl,
		&i.ModelsEndpointResolver,
		&i.SupportsNativeWebSearch,
	)
	return i, err
}
