// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: provider.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createProvider = `-- name: CreateProvider :one
INSERT INTO provider (name, credentials, priority, provider_models, annotations, disabled, proxy_url) VALUES ($1, $2, $3, $4, $5, $6, $7) RETURNING id, name, credentials, priority, provider_models, annotations, disabled, proxy_url
`

type CreateProviderParams struct {
	Name           string      `json:"name"`
	Credentials    string      `json:"credentials"`
	Priority       int32       `json:"priority"`
	ProviderModels []byte      `json:"providerModels"`
	Annotations    []byte      `json:"annotations"`
	Disabled       bool        `json:"disabled"`
	ProxyUrl       pgtype.Text `json:"proxyUrl"`
}

func (q *Queries) CreateProvider(ctx context.Context, arg CreateProviderParams) (Provider, error) {
	row := q.db.QueryRow(ctx, createProvider,
		arg.Name,
		arg.Credentials,
		arg.Priority,
		arg.ProviderModels,
		arg.Annotations,
		arg.Disabled,
		arg.ProxyUrl,
	)
	var i Provider
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Credentials,
		&i.Priority,
		&i.ProviderModels,
		&i.Annotations,
		&i.Disabled,
		&i.ProxyUrl,
	)
	return i, err
}

const deleteProvider = `-- name: DeleteProvider :exec
DELETE FROM provider WHERE id = $1
`

func (q *Queries) DeleteProvider(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, deleteProvider, id)
	return err
}

const getProviderByID = `-- name: GetProviderByID :one
SELECT id, name, credentials, priority, provider_models, annotations, disabled, proxy_url FROM provider WHERE id = $1 LIMIT 1
`

func (q *Queries) GetProviderByID(ctx context.Context, id int32) (Provider, error) {
	row := q.db.QueryRow(ctx, getProviderByID, id)
	var i Provider
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Credentials,
		&i.Priority,
		&i.ProviderModels,
		&i.Annotations,
		&i.Disabled,
		&i.ProxyUrl,
	)
	return i, err
}

const getProviders = `-- name: GetProviders :many
SELECT id, name, credentials, priority, provider_models, annotations, disabled, proxy_url FROM provider
`

func (q *Queries) GetProviders(ctx context.Context) ([]Provider, error) {
	rows, err := q.db.Query(ctx, getProviders)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Provider
	for rows.Next() {
		var i Provider
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Credentials,
			&i.Priority,
			&i.ProviderModels,
			&i.Annotations,
			&i.Disabled,
			&i.ProxyUrl,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateProvider = `-- name: UpdateProvider :one
UPDATE provider
  SET
    name = CASE WHEN $1::bool THEN $2::text ELSE name END,
    credentials = CASE WHEN $3::bool THEN $4::text ELSE credentials END,
    priority = CASE WHEN $5::bool THEN $6::int ELSE priority END,
    provider_models = CASE WHEN $7::bool THEN $8::jsonb ELSE provider_models END,
    annotations = CASE WHEN $9::bool THEN $10::jsonb ELSE annotations END,
    disabled = CASE WHEN $11::bool THEN $12::bool ELSE disabled END,
    proxy_url = CASE WHEN $13::bool THEN $14::text ELSE proxy_url END
  WHERE id = $15::int
  RETURNING id, name, credentials, priority, provider_models, annotations, disabled, proxy_url
`

type UpdateProviderParams struct {
	SetName           bool   `json:"setName"`
	Name              string `json:"name"`
	SetCredentials    bool   `json:"setCredentials"`
	Credentials       string `json:"credentials"`
	SetPriority       bool   `json:"setPriority"`
	Priority          int32  `json:"priority"`
	SetProviderModels bool   `json:"setProviderModels"`
	ProviderModels    []byte `json:"providerModels"`
	SetAnnotations    bool   `json:"setAnnotations"`
	Annotations       []byte `json:"annotations"`
	SetDisabled       bool   `json:"setDisabled"`
	Disabled          bool   `json:"disabled"`
	SetProxyUrl       bool   `json:"setProxyUrl"`
	ProxyUrl          string `json:"proxyUrl"`
	ID                int32  `json:"id"`
}

func (q *Queries) UpdateProvider(ctx context.Context, arg UpdateProviderParams) (Provider, error) {
	row := q.db.QueryRow(ctx, updateProvider,
		arg.SetName,
		arg.Name,
		arg.SetCredentials,
		arg.Credentials,
		arg.SetPriority,
		arg.Priority,
		arg.SetProviderModels,
		arg.ProviderModels,
		arg.SetAnnotations,
		arg.Annotations,
		arg.SetDisabled,
		arg.Disabled,
		arg.SetProxyUrl,
		arg.ProxyUrl,
		arg.ID,
	)
	var i Provider
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Credentials,
		&i.Priority,
		&i.ProviderModels,
		&i.Annotations,
		&i.Disabled,
		&i.ProxyUrl,
	)
	return i, err
}
