// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: provider_endpoint.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteProviderEndpoint = `-- name: DeleteProviderEndpoint :exec
DELETE FROM provider_endpoint
WHERE provider_id = $1 AND endpoint_path = $2
`

type DeleteProviderEndpointParams struct {
	ProviderID   int32  `json:"providerId"`
	EndpointPath string `json:"endpointPath"`
}

func (q *Queries) DeleteProviderEndpoint(ctx context.Context, arg DeleteProviderEndpointParams) error {
	_, err := q.db.Exec(ctx, deleteProviderEndpoint, arg.ProviderID, arg.EndpointPath)
	return err
}

const getProviderEndpoint = `-- name: GetProviderEndpoint :one
SELECT provider_id, endpoint_path, upstream_url, credentials_resolver FROM provider_endpoint
WHERE provider_id = $1 AND endpoint_path = $2
`

type GetProviderEndpointParams struct {
	ProviderID   int32  `json:"providerId"`
	EndpointPath string `json:"endpointPath"`
}

func (q *Queries) GetProviderEndpoint(ctx context.Context, arg GetProviderEndpointParams) (ProviderEndpoint, error) {
	row := q.db.QueryRow(ctx, getProviderEndpoint, arg.ProviderID, arg.EndpointPath)
	var i ProviderEndpoint
	err := row.Scan(
		&i.ProviderID,
		&i.EndpointPath,
		&i.UpstreamUrl,
		&i.CredentialsResolver,
	)
	return i, err
}

const listProviderEndpoints = `-- name: ListProviderEndpoints :many
SELECT provider_id, endpoint_path, upstream_url, credentials_resolver FROM provider_endpoint
WHERE $1::int IS NULL OR provider_id = $1::int
ORDER BY provider_id, endpoint_path
`

func (q *Queries) ListProviderEndpoints(ctx context.Context, providerID pgtype.Int4) ([]ProviderEndpoint, error) {
	rows, err := q.db.Query(ctx, listProviderEndpoints, providerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ProviderEndpoint
	for rows.Next() {
		var i ProviderEndpoint
		if err := rows.Scan(
			&i.ProviderID,
			&i.EndpointPath,
			&i.UpstreamUrl,
			&i.CredentialsResolver,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertProviderEndpoint = `-- name: UpsertProviderEndpoint :one
INSERT INTO provider_endpoint (provider_id, endpoint_path, upstream_url, credentials_resolver)
VALUES ($1, $2, $3, $4)
ON CONFLICT (provider_id, endpoint_path) DO UPDATE SET
  upstream_url = EXCLUDED.upstream_url,
  credentials_resolver = EXCLUDED.credentials_resolver
RETURNING provider_id, endpoint_path, upstream_url, credentials_resolver
`

type UpsertProviderEndpointParams struct {
	ProviderID          int32  `json:"providerId"`
	EndpointPath        string `json:"endpointPath"`
	UpstreamUrl         string `json:"upstreamUrl"`
	CredentialsResolver int32  `json:"credentialsResolver"`
}

func (q *Queries) UpsertProviderEndpoint(ctx context.Context, arg UpsertProviderEndpointParams) (ProviderEndpoint, error) {
	row := q.db.QueryRow(ctx, upsertProviderEndpoint,
		arg.ProviderID,
		arg.EndpointPath,
		arg.UpstreamUrl,
		arg.CredentialsResolver,
	)
	var i ProviderEndpoint
	err := row.Scan(
		&i.ProviderID,
		&i.EndpointPath,
		&i.UpstreamUrl,
		&i.CredentialsResolver,
	)
	return i, err
}
