// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	BackfillTrace(ctx context.Context, arg BackfillTraceParams) error
	CountAdminTraces(ctx context.Context, arg CountAdminTracesParams) (int64, error)
	CountAdminTracesFiltered(ctx context.Context, arg CountAdminTracesFilteredParams) (int64, error)
	CountTraces(ctx context.Context, arg CountTracesParams) (int64, error)
	CountTracesFiltered(ctx context.Context, arg CountTracesFilteredParams) (int64, error)
	CreateProvider(ctx context.Context, arg CreateProviderParams) (Provider, error)
	CreateUserIdentity(ctx context.Context, arg CreateUserIdentityParams) (UserIdentity, error)
	DeleteApiKey(ctx context.Context, arg DeleteApiKeyParams) error
	DeleteEndpoint(ctx context.Context, path string) error
	DeleteExchangeRate(ctx context.Context, code string) error
	DeleteModel(ctx context.Context, name string) error
	DeleteProject(ctx context.Context, arg DeleteProjectParams) error
	DeleteProvider(ctx context.Context, id int32) error
	DeleteProviderEndpoint(ctx context.Context, arg DeleteProviderEndpointParams) error
	DeleteScript(ctx context.Context, id string) error
	DeleteUser(ctx context.Context, id int64) error
	DeleteUserIdentitiesByUser(ctx context.Context, userID int64) error
	DeleteUserIdentity(ctx context.Context, id int64) error
	DeleteUserSetting(ctx context.Context, arg DeleteUserSettingParams) (int64, error)
	GetAdminOverviewSpeedBoxplot(ctx context.Context, arg GetAdminOverviewSpeedBoxplotParams) ([]GetAdminOverviewSpeedBoxplotRow, error)
	GetAdminOverviewTokenBreakdown(ctx context.Context, arg GetAdminOverviewTokenBreakdownParams) (GetAdminOverviewTokenBreakdownRow, error)
	GetAdminOverviewTotals(ctx context.Context, arg GetAdminOverviewTotalsParams) (GetAdminOverviewTotalsRow, error)
	GetApiKey(ctx context.Context, arg GetApiKeyParams) (ApiKey, error)
	GetApiKeyByKey(ctx context.Context, key string) (ApiKey, error)
	GetEndpointByPath(ctx context.Context, path string) (Endpoint, error)
	GetEndpoints(ctx context.Context) ([]Endpoint, error)
	GetExchangeRateByCode(ctx context.Context, code string) (ExchangeRate, error)
	GetExchangeRates(ctx context.Context) ([]ExchangeRate, error)
	GetFirstEndpointByType(ctx context.Context, endpointType int32) (Endpoint, error)
	GetModelByName(ctx context.Context, name string) (Model, error)
	GetModels(ctx context.Context) ([]Model, error)
	GetOverviewSpeedBoxplot(ctx context.Context, arg GetOverviewSpeedBoxplotParams) ([]GetOverviewSpeedBoxplotRow, error)
	GetOverviewTokenBreakdown(ctx context.Context, arg GetOverviewTokenBreakdownParams) (GetOverviewTokenBreakdownRow, error)
	GetOverviewTotals(ctx context.Context, arg GetOverviewTotalsParams) (GetOverviewTotalsRow, error)
	GetProject(ctx context.Context, arg GetProjectParams) (Project, error)
	GetProjectByName(ctx context.Context, arg GetProjectByNameParams) (Project, error)
	GetProviderByID(ctx context.Context, id int32) (Provider, error)
	GetProviderEndpoint(ctx context.Context, arg GetProviderEndpointParams) (ProviderEndpoint, error)
	GetProviders(ctx context.Context) ([]Provider, error)
	// Sister query to GetProvidersByEndpointAndModel for "no-model" endpoints
	// (endpoint.model_path = ''). Returns every non-disabled provider bound to the
	// given endpoint_path, with model-related columns flattened to constants so the
	// consuming Go code can treat both shapes uniformly.
	GetProvidersByEndpoint(ctx context.Context, endpointPath string) ([]GetProvidersByEndpointRow, error)
	GetProvidersByEndpointAndModel(ctx context.Context, arg GetProvidersByEndpointAndModelParams) ([]GetProvidersByEndpointAndModelRow, error)
	// Sister query to GetProvidersByEndpointAndModel that selects across a SET of
	// endpoint types instead of a single endpoint path. The unified gateway
	// routes (/v1/messages, /v1/responses, /v1/chat/completions, and the two
	// Gemini variants) compute the type set from (source format, stream flag)
	// and call this. Returns the same column shape as the path-based query plus
	// e.endpoint_type so the handler can pick the right transformer per row.
	GetProvidersByEndpointTypesAndModel(ctx context.Context, arg GetProvidersByEndpointTypesAndModelParams) ([]GetProvidersByEndpointTypesAndModelRow, error)
	GetRequest(ctx context.Context, arg GetRequestParams) (Request, error)
	GetScript(ctx context.Context, id string) (Script, error)
	GetUserByID(ctx context.Context, id int64) (AppUser, error)
	GetUserByIdentity(ctx context.Context, arg GetUserByIdentityParams) (AppUser, error)
	GetUserIdentity(ctx context.Context, arg GetUserIdentityParams) (UserIdentity, error)
	GetUserIdentityByID(ctx context.Context, id int64) (UserIdentity, error)
	GetUserSetting(ctx context.Context, arg GetUserSettingParams) (UserSetting, error)
	InsertApiKey(ctx context.Context, arg InsertApiKeyParams) (ApiKey, error)
	InsertAutoCreatedProject(ctx context.Context, arg InsertAutoCreatedProjectParams) (Project, error)
	InsertProject(ctx context.Context, arg InsertProjectParams) (Project, error)
	InsertRequest(ctx context.Context, arg InsertRequestParams) (pgtype.Timestamp, error)
	InsertScript(ctx context.Context, arg InsertScriptParams) (Script, error)
	InsertUser(ctx context.Context, arg InsertUserParams) (AppUser, error)
	InsertUserIdentity(ctx context.Context, arg InsertUserIdentityParams) (UserIdentity, error)
	ListAdminOverviewBreakdownCosts(ctx context.Context, arg ListAdminOverviewBreakdownCostsParams) ([]ListAdminOverviewBreakdownCostsRow, error)
	ListAdminOverviewBreakdownTokens(ctx context.Context, arg ListAdminOverviewBreakdownTokensParams) ([]ListAdminOverviewBreakdownTokensRow, error)
	ListAdminOverviewCacheHitRateSeries(ctx context.Context, arg ListAdminOverviewCacheHitRateSeriesParams) ([]ListAdminOverviewCacheHitRateSeriesRow, error)
	ListAdminOverviewDistribution(ctx context.Context, arg ListAdminOverviewDistributionParams) ([]ListAdminOverviewDistributionRow, error)
	ListAdminOverviewDistributionCosts(ctx context.Context, arg ListAdminOverviewDistributionCostsParams) ([]ListAdminOverviewDistributionCostsRow, error)
	ListAdminOverviewSeriesMetrics(ctx context.Context, arg ListAdminOverviewSeriesMetricsParams) ([]ListAdminOverviewSeriesMetricsRow, error)
	ListAdminOverviewSeriesTraces(ctx context.Context, arg ListAdminOverviewSeriesTracesParams) ([]ListAdminOverviewSeriesTracesRow, error)
	ListAdminOverviewSpeedSeries(ctx context.Context, arg ListAdminOverviewSpeedSeriesParams) ([]ListAdminOverviewSpeedSeriesRow, error)
	ListAdminOverviewTraceCountsByDimension(ctx context.Context, arg ListAdminOverviewTraceCountsByDimensionParams) ([]ListAdminOverviewTraceCountsByDimensionRow, error)
	ListApiKeys(ctx context.Context, userID int64) ([]ApiKey, error)
	ListAvailableModelNames(ctx context.Context) ([]string, error)
	ListEnabledScripts(ctx context.Context) ([]Script, error)
	ListOverviewBreakdownCosts(ctx context.Context, arg ListOverviewBreakdownCostsParams) ([]ListOverviewBreakdownCostsRow, error)
	ListOverviewBreakdownTokens(ctx context.Context, arg ListOverviewBreakdownTokensParams) ([]ListOverviewBreakdownTokensRow, error)
	ListOverviewCacheHitRateSeries(ctx context.Context, arg ListOverviewCacheHitRateSeriesParams) ([]ListOverviewCacheHitRateSeriesRow, error)
	ListOverviewDistribution(ctx context.Context, arg ListOverviewDistributionParams) ([]ListOverviewDistributionRow, error)
	ListOverviewDistributionCosts(ctx context.Context, arg ListOverviewDistributionCostsParams) ([]ListOverviewDistributionCostsRow, error)
	ListOverviewSeriesMetrics(ctx context.Context, arg ListOverviewSeriesMetricsParams) ([]ListOverviewSeriesMetricsRow, error)
	ListOverviewSeriesTraces(ctx context.Context, arg ListOverviewSeriesTracesParams) ([]ListOverviewSeriesTracesRow, error)
	ListOverviewSpeedSeries(ctx context.Context, arg ListOverviewSpeedSeriesParams) ([]ListOverviewSpeedSeriesRow, error)
	ListOverviewTraceCountsByDimension(ctx context.Context, arg ListOverviewTraceCountsByDimensionParams) ([]ListOverviewTraceCountsByDimensionRow, error)
	ListProjects(ctx context.Context, userID int64) ([]Project, error)
	ListProviderEndpoints(ctx context.Context, providerID pgtype.Int4) ([]ProviderEndpoint, error)
	ListRequestTraces(ctx context.Context, arg ListRequestTracesParams) ([]ListRequestTracesRow, error)
	ListRequests(ctx context.Context, arg ListRequestsParams) ([]ListRequestsRow, error)
	ListRequestsBySpan(ctx context.Context, arg ListRequestsBySpanParams) ([]ListRequestsBySpanRow, error)
	ListScripts(ctx context.Context) ([]Script, error)
	ListTraceBackfillCandidates(ctx context.Context) ([]ListTraceBackfillCandidatesRow, error)
	ListUserIdentities(ctx context.Context, userID int64) ([]UserIdentity, error)
	ListUserSettings(ctx context.Context, userID int64) ([]UserSetting, error)
	ListUsers(ctx context.Context) ([]AppUser, error)
	MatchProjectByPaths(ctx context.Context, arg MatchProjectByPathsParams) (int32, error)
	MergeProjectReassignRequests(ctx context.Context, arg MergeProjectReassignRequestsParams) (int64, error)
	MergeProjectUpdateTarget(ctx context.Context, arg MergeProjectUpdateTargetParams) (Project, error)
	UpdateApiKey(ctx context.Context, arg UpdateApiKeyParams) (ApiKey, error)
	UpdateProject(ctx context.Context, arg UpdateProjectParams) (Project, error)
	UpdateProvider(ctx context.Context, arg UpdateProviderParams) (Provider, error)
	UpdateRequestMetrics(ctx context.Context, arg UpdateRequestMetricsParams) error
	UpdateRequestModel(ctx context.Context, arg UpdateRequestModelParams) error
	UpdateRequestOnComplete(ctx context.Context, arg UpdateRequestOnCompleteParams) error
	UpdateRequestOnHeader(ctx context.Context, arg UpdateRequestOnHeaderParams) error
	UpdateScript(ctx context.Context, arg UpdateScriptParams) (Script, error)
	UpdateUser(ctx context.Context, arg UpdateUserParams) (AppUser, error)
	UpdateUserAdmin(ctx context.Context, arg UpdateUserAdminParams) (AppUser, error)
	UpdateUserIdentity(ctx context.Context, arg UpdateUserIdentityParams) (UserIdentity, error)
	UpdateUserIdentityUser(ctx context.Context, arg UpdateUserIdentityUserParams) (UserIdentity, error)
	UpsertEndpoint(ctx context.Context, arg UpsertEndpointParams) (Endpoint, error)
	UpsertExchangeRate(ctx context.Context, arg UpsertExchangeRateParams) (ExchangeRate, error)
	UpsertModel(ctx context.Context, arg UpsertModelParams) (Model, error)
	UpsertProjectSeen(ctx context.Context, arg UpsertProjectSeenParams) error
	UpsertProviderEndpoint(ctx context.Context, arg UpsertProviderEndpointParams) (ProviderEndpoint, error)
	UpsertTrace(ctx context.Context, arg UpsertTraceParams) (UpsertTraceRow, error)
	UpsertUserSetting(ctx context.Context, arg UpsertUserSettingParams) (UserSetting, error)
}

var _ Querier = (*Queries)(nil)
