// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: request.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getRequest = `-- name: GetRequest :one
SELECT id, span_id, parent_span_id, provider_id, endpoint_path, api_key_id, model, input_tokens, cache_read_tokens, output_tokens, cache_write_tokens, status_code, error_message, ttft_ms, time_spent_ms, created_at, type, status, upstream_model, model_cost, model_cost_currency, user_message_preview, cache_write_1h_tokens, project_id, finish_reason, inferred_provider, inferred_model, inferred_model_source, user_id FROM request
WHERE id = $1
  AND created_at = $2::timestamp
  AND user_id = $3::bigint
`

type GetRequestParams struct {
	ID          string           `json:"id"`
	IDCreatedAt pgtype.Timestamp `json:"idCreatedAt"`
	UserID      int64            `json:"userId"`
}

func (q *Queries) GetRequest(ctx context.Context, arg GetRequestParams) (Request, error) {
	row := q.db.QueryRow(ctx, getRequest, arg.ID, arg.IDCreatedAt, arg.UserID)
	var i Request
	err := row.Scan(
		&i.ID,
		&i.SpanID,
		&i.ParentSpanID,
		&i.ProviderID,
		&i.EndpointPath,
		&i.ApiKeyID,
		&i.Model,
		&i.InputTokens,
		&i.CacheReadTokens,
		&i.OutputTokens,
		&i.CacheWriteTokens,
		&i.StatusCode,
		&i.ErrorMessage,
		&i.TtftMs,
		&i.TimeSpentMs,
		&i.CreatedAt,
		&i.Type,
		&i.Status,
		&i.UpstreamModel,
		&i.ModelCost,
		&i.ModelCostCurrency,
		&i.UserMessagePreview,
		&i.CacheWrite1hTokens,
		&i.ProjectID,
		&i.FinishReason,
		&i.InferredProvider,
		&i.InferredModel,
		&i.InferredModelSource,
		&i.UserID,
	)
	return i, err
}

const listRequestTraces = `-- name: ListRequestTraces :many
SELECT
  traces.id,
  traces.parent_span_id,
  COALESCE(metrics.meta_request_count, 0)::bigint AS meta_request_count,
  COALESCE(metrics.upstream_request_count, 0)::bigint AS upstream_request_count,
  COALESCE(metrics.total_tokens, 0)::bigint AS total_tokens,
  COALESCE(metrics.input_tokens, 0)::bigint AS input_tokens,
  COALESCE(metrics.cache_read_tokens, 0)::bigint AS cache_read_tokens,
  COALESCE(metrics.output_tokens, 0)::bigint AS output_tokens,
  COALESCE(metrics.cache_write_tokens, 0)::bigint AS cache_write_tokens,
  COALESCE(metrics.cache_write_1h_tokens, 0)::bigint AS cache_write_1h_tokens,
  COALESCE(model_costs.costs, '[]'::jsonb)::jsonb AS model_costs,
  traces.first_request_at,
  traces.last_request_at,
  preview.user_message_preview,
  trace_project.project_id AS project_id
FROM traces
LEFT JOIN LATERAL (
  SELECT
    COUNT(*) FILTER (WHERE type = 0)::bigint AS meta_request_count,
    COUNT(*) FILTER (WHERE type = 1)::bigint AS upstream_request_count,
    COALESCE(SUM(
      COALESCE(input_tokens, 0)
      + COALESCE(cache_read_tokens, 0)
      + COALESCE(output_tokens, 0)
      + COALESCE(cache_write_tokens, 0)
      + COALESCE(cache_write_1h_tokens, 0)
    ) FILTER (WHERE type = 1), 0)::bigint AS total_tokens,
    COALESCE(SUM(COALESCE(input_tokens, 0)) FILTER (WHERE type = 1), 0)::bigint AS input_tokens,
    COALESCE(SUM(COALESCE(cache_read_tokens, 0)) FILTER (WHERE type = 1), 0)::bigint AS cache_read_tokens,
    COALESCE(SUM(COALESCE(output_tokens, 0)) FILTER (WHERE type = 1), 0)::bigint AS output_tokens,
    COALESCE(SUM(COALESCE(cache_write_tokens, 0)) FILTER (WHERE type = 1), 0)::bigint AS cache_write_tokens,
    COALESCE(SUM(COALESCE(cache_write_1h_tokens, 0)) FILTER (WHERE type = 1), 0)::bigint AS cache_write_1h_tokens
  FROM request
  WHERE parent_span_id = traces.parent_span_id
    AND request.user_id = traces.user_id
    AND created_at >= traces.first_request_at
    AND created_at <= traces.last_request_at
) metrics ON true
LEFT JOIN LATERAL (
  SELECT jsonb_agg(
    jsonb_build_object('currency', grouped.currency, 'amount', grouped.amount)
    ORDER BY grouped.currency
  ) AS costs
  FROM (
    SELECT model_cost_currency AS currency, SUM(model_cost)::float8 AS amount
    FROM request
    WHERE parent_span_id = traces.parent_span_id
      AND request.user_id = traces.user_id
      AND created_at >= traces.first_request_at
      AND created_at <= traces.last_request_at
      AND type = 1
      AND model_cost IS NOT NULL
      AND model_cost_currency IS NOT NULL
    GROUP BY model_cost_currency
  ) grouped
) model_costs ON true
LEFT JOIN LATERAL (
  SELECT user_message_preview
  FROM request
  WHERE parent_span_id = traces.parent_span_id
    AND request.user_id = traces.user_id
    AND created_at >= traces.first_request_at
    AND created_at <= traces.last_request_at
    AND type = 0
    AND user_message_preview IS NOT NULL
  ORDER BY created_at DESC, id DESC
  LIMIT 1
) preview ON true
LEFT JOIN LATERAL (
  SELECT project_id
  FROM request
  WHERE parent_span_id = traces.parent_span_id
    AND request.user_id = traces.user_id
    AND created_at >= traces.first_request_at
    AND created_at <= traces.last_request_at
    AND type = 0
    AND project_id IS NOT NULL
  ORDER BY created_at DESC, id DESC
  LIMIT 1
) trace_project ON true
WHERE
  traces.user_id = $1::bigint
  AND (
    $2::timestamp IS NULL
    OR (traces.last_request_at, traces.id) < (
      $2::timestamp,
      $3::text
    )
  )
ORDER BY traces.last_request_at DESC, traces.id DESC
LIMIT $4::int
`

type ListRequestTracesParams struct {
	UserID              int64            `json:"userId"`
	CursorLastRequestAt pgtype.Timestamp `json:"cursorLastRequestAt"`
	CursorTraceID       pgtype.Text      `json:"cursorTraceId"`
	Limit               pgtype.Int4      `json:"limit"`
}

type ListRequestTracesRow struct {
	ID                   string           `json:"id"`
	ParentSpanID         string           `json:"parentSpanId"`
	MetaRequestCount     int64            `json:"metaRequestCount"`
	UpstreamRequestCount int64            `json:"upstreamRequestCount"`
	TotalTokens          int64            `json:"totalTokens"`
	InputTokens          int64            `json:"inputTokens"`
	CacheReadTokens      int64            `json:"cacheReadTokens"`
	OutputTokens         int64            `json:"outputTokens"`
	CacheWriteTokens     int64            `json:"cacheWriteTokens"`
	CacheWrite1hTokens   int64            `json:"cacheWrite1hTokens"`
	ModelCosts           []byte           `json:"modelCosts"`
	FirstRequestAt       pgtype.Timestamp `json:"firstRequestAt"`
	LastRequestAt        pgtype.Timestamp `json:"lastRequestAt"`
	UserMessagePreview   pgtype.Text      `json:"userMessagePreview"`
	ProjectID            pgtype.Int4      `json:"projectId"`
}

func (q *Queries) ListRequestTraces(ctx context.Context, arg ListRequestTracesParams) ([]ListRequestTracesRow, error) {
	rows, err := q.db.Query(ctx, listRequestTraces,
		arg.UserID,
		arg.CursorLastRequestAt,
		arg.CursorTraceID,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListRequestTracesRow
	for rows.Next() {
		var i ListRequestTracesRow
		if err := rows.Scan(
			&i.ID,
			&i.ParentSpanID,
			&i.MetaRequestCount,
			&i.UpstreamRequestCount,
			&i.TotalTokens,
			&i.InputTokens,
			&i.CacheReadTokens,
			&i.OutputTokens,
			&i.CacheWriteTokens,
			&i.CacheWrite1hTokens,
			&i.ModelCosts,
			&i.FirstRequestAt,
			&i.LastRequestAt,
			&i.UserMessagePreview,
			&i.ProjectID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRequests = `-- name: ListRequests :many
SELECT r.id, r.span_id, r.parent_span_id, r.type, r.status, r.provider_id, r.endpoint_path, r.api_key_id, r.model,
       r.upstream_model, r.input_tokens, r.cache_read_tokens, r.output_tokens, r.cache_write_tokens, r.cache_write_1h_tokens,
       r.status_code, r.error_message, r.ttft_ms, r.time_spent_ms, r.created_at,
       r.model_cost, r.model_cost_currency,
       r.user_message_preview, r.project_id, r.finish_reason,
       r.inferred_provider, r.inferred_model, r.inferred_model_source,
       r.user_id
FROM request r
LEFT JOIN traces selected_trace ON selected_trace.id = $1::text
WHERE
  r.user_id = $2::bigint
  AND ($3::int IS NULL OR r.type = $3)
  AND ($4::int IS NULL OR r.provider_id = $4)
  AND ($5::text IS NULL OR r.endpoint_path = $5)
  AND ($6::text IS NULL OR r.model = $6)
  AND ($7::text IS NULL OR r.upstream_model = $7)
  AND ($8::int IS NULL OR r.project_id = $8)
  AND (
    $1::text IS NULL
    OR (
      r.parent_span_id = selected_trace.parent_span_id
      AND r.created_at >= selected_trace.first_request_at
      AND r.created_at <= selected_trace.last_request_at
    )
  )
  AND (
    $9::timestamp IS NULL
    OR (r.created_at, r.id) < ($9::timestamp, $10::text)
  )
ORDER BY r.created_at DESC, r.id DESC
LIMIT $11::int
`

type ListRequestsParams struct {
	TraceID         pgtype.Text      `json:"traceId"`
	UserID          int64            `json:"userId"`
	Type            pgtype.Int4      `json:"type"`
	ProviderID      pgtype.Int4      `json:"providerId"`
	EndpointPath    pgtype.Text      `json:"endpointPath"`
	Model           pgtype.Text      `json:"model"`
	UpstreamModel   pgtype.Text      `json:"upstreamModel"`
	ProjectID       pgtype.Int4      `json:"projectId"`
	CursorCreatedAt pgtype.Timestamp `json:"cursorCreatedAt"`
	CursorID        pgtype.Text      `json:"cursorId"`
	Limit           pgtype.Int4      `json:"limit"`
}

type ListRequestsRow struct {
	ID                  string           `json:"id"`
	SpanID              pgtype.Text      `json:"spanId"`
	ParentSpanID        pgtype.Text      `json:"parentSpanId"`
	Type                int32            `json:"type"`
	Status              int32            `json:"status"`
	ProviderID          pgtype.Int4      `json:"providerId"`
	EndpointPath        pgtype.Text      `json:"endpointPath"`
	ApiKeyID            pgtype.Int4      `json:"apiKeyId"`
	Model               pgtype.Text      `json:"model"`
	UpstreamModel       pgtype.Text      `json:"upstreamModel"`
	InputTokens         pgtype.Int4      `json:"inputTokens"`
	CacheReadTokens     pgtype.Int4      `json:"cacheReadTokens"`
	OutputTokens        pgtype.Int4      `json:"outputTokens"`
	CacheWriteTokens    pgtype.Int4      `json:"cacheWriteTokens"`
	CacheWrite1hTokens  pgtype.Int4      `json:"cacheWrite1hTokens"`
	StatusCode          pgtype.Int4      `json:"statusCode"`
	ErrorMessage        pgtype.Text      `json:"errorMessage"`
	TtftMs              pgtype.Int4      `json:"ttftMs"`
	TimeSpentMs         pgtype.Int4      `json:"timeSpentMs"`
	CreatedAt           pgtype.Timestamp `json:"createdAt"`
	ModelCost           pgtype.Numeric   `json:"modelCost"`
	ModelCostCurrency   pgtype.Text      `json:"modelCostCurrency"`
	UserMessagePreview  pgtype.Text      `json:"userMessagePreview"`
	ProjectID           pgtype.Int4      `json:"projectId"`
	FinishReason        pgtype.Int4      `json:"finishReason"`
	InferredProvider    pgtype.Text      `json:"inferredProvider"`
	InferredModel       pgtype.Text      `json:"inferredModel"`
	InferredModelSource int16            `json:"inferredModelSource"`
	UserID              pgtype.Int8      `json:"userId"`
}

func (q *Queries) ListRequests(ctx context.Context, arg ListRequestsParams) ([]ListRequestsRow, error) {
	rows, err := q.db.Query(ctx, listRequests,
		arg.TraceID,
		arg.UserID,
		arg.Type,
		arg.ProviderID,
		arg.EndpointPath,
		arg.Model,
		arg.UpstreamModel,
		arg.ProjectID,
		arg.CursorCreatedAt,
		arg.CursorID,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListRequestsRow
	for rows.Next() {
		var i ListRequestsRow
		if err := rows.Scan(
			&i.ID,
			&i.SpanID,
			&i.ParentSpanID,
			&i.Type,
			&i.Status,
			&i.ProviderID,
			&i.EndpointPath,
			&i.ApiKeyID,
			&i.Model,
			&i.UpstreamModel,
			&i.InputTokens,
			&i.CacheReadTokens,
			&i.OutputTokens,
			&i.CacheWriteTokens,
			&i.CacheWrite1hTokens,
			&i.StatusCode,
			&i.ErrorMessage,
			&i.TtftMs,
			&i.TimeSpentMs,
			&i.CreatedAt,
			&i.ModelCost,
			&i.ModelCostCurrency,
			&i.UserMessagePreview,
			&i.ProjectID,
			&i.FinishReason,
			&i.InferredProvider,
			&i.InferredModel,
			&i.InferredModelSource,
			&i.UserID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRequestsBySpan = `-- name: ListRequestsBySpan :many
WITH anchor AS (
  SELECT request.span_id
  FROM request
  WHERE request.id = $2::text
    AND request.created_at = $3::timestamp
    AND request.user_id = $1::bigint
)
SELECT r.id, r.span_id, r.parent_span_id, r.type, r.status, r.provider_id, r.endpoint_path,
       r.api_key_id, r.model, r.upstream_model, r.input_tokens, r.cache_read_tokens, r.output_tokens,
       r.cache_write_tokens, r.cache_write_1h_tokens, r.status_code, r.error_message, r.ttft_ms, r.time_spent_ms,
       r.created_at,
       r.model_cost, r.model_cost_currency,
       r.user_message_preview, r.project_id, r.finish_reason,
       r.inferred_provider, r.inferred_model, r.inferred_model_source,
       r.user_id
FROM request r, anchor
WHERE r.span_id = anchor.span_id
  AND r.user_id = $1::bigint
ORDER BY r.created_at ASC, r.id ASC
`

type ListRequestsBySpanParams struct {
	UserID      int64            `json:"userId"`
	ID          string           `json:"id"`
	IDCreatedAt pgtype.Timestamp `json:"idCreatedAt"`
}

type ListRequestsBySpanRow struct {
	ID                  string           `json:"id"`
	SpanID              pgtype.Text      `json:"spanId"`
	ParentSpanID        pgtype.Text      `json:"parentSpanId"`
	Type                int32            `json:"type"`
	Status              int32            `json:"status"`
	ProviderID          pgtype.Int4      `json:"providerId"`
	EndpointPath        pgtype.Text      `json:"endpointPath"`
	ApiKeyID            pgtype.Int4      `json:"apiKeyId"`
	Model               pgtype.Text      `json:"model"`
	UpstreamModel       pgtype.Text      `json:"upstreamModel"`
	InputTokens         pgtype.Int4      `json:"inputTokens"`
	CacheReadTokens     pgtype.Int4      `json:"cacheReadTokens"`
	OutputTokens        pgtype.Int4      `json:"outputTokens"`
	CacheWriteTokens    pgtype.Int4      `json:"cacheWriteTokens"`
	CacheWrite1hTokens  pgtype.Int4      `json:"cacheWrite1hTokens"`
	StatusCode          pgtype.Int4      `json:"statusCode"`
	ErrorMessage        pgtype.Text      `json:"errorMessage"`
	TtftMs              pgtype.Int4      `json:"ttftMs"`
	TimeSpentMs         pgtype.Int4      `json:"timeSpentMs"`
	CreatedAt           pgtype.Timestamp `json:"createdAt"`
	ModelCost           pgtype.Numeric   `json:"modelCost"`
	ModelCostCurrency   pgtype.Text      `json:"modelCostCurrency"`
	UserMessagePreview  pgtype.Text      `json:"userMessagePreview"`
	ProjectID           pgtype.Int4      `json:"projectId"`
	FinishReason        pgtype.Int4      `json:"finishReason"`
	InferredProvider    pgtype.Text      `json:"inferredProvider"`
	InferredModel       pgtype.Text      `json:"inferredModel"`
	InferredModelSource int16            `json:"inferredModelSource"`
	UserID              pgtype.Int8      `json:"userId"`
}

func (q *Queries) ListRequestsBySpan(ctx context.Context, arg ListRequestsBySpanParams) ([]ListRequestsBySpanRow, error) {
	rows, err := q.db.Query(ctx, listRequestsBySpan, arg.UserID, arg.ID, arg.IDCreatedAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListRequestsBySpanRow
	for rows.Next() {
		var i ListRequestsBySpanRow
		if err := rows.Scan(
			&i.ID,
			&i.SpanID,
			&i.ParentSpanID,
			&i.Type,
			&i.Status,
			&i.ProviderID,
			&i.EndpointPath,
			&i.ApiKeyID,
			&i.Model,
			&i.UpstreamModel,
			&i.InputTokens,
			&i.CacheReadTokens,
			&i.OutputTokens,
			&i.CacheWriteTokens,
			&i.CacheWrite1hTokens,
			&i.StatusCode,
			&i.ErrorMessage,
			&i.TtftMs,
			&i.TimeSpentMs,
			&i.CreatedAt,
			&i.ModelCost,
			&i.ModelCostCurrency,
			&i.UserMessagePreview,
			&i.ProjectID,
			&i.FinishReason,
			&i.InferredProvider,
			&i.InferredModel,
			&i.InferredModelSource,
			&i.UserID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateRequest = `-- name: UpdateRequest :exec
UPDATE request SET
  provider_id = CASE WHEN $1::bool THEN $2::int ELSE provider_id END,
  model = CASE WHEN $3::bool THEN $4::text ELSE model END,
  upstream_model = CASE WHEN $5::bool THEN $6::text ELSE upstream_model END,
  endpoint_path = CASE WHEN $7::bool THEN $8::text ELSE endpoint_path END,
  api_key_id = CASE WHEN $9::bool THEN $10::int ELSE api_key_id END,
  user_id = CASE WHEN $11::bool THEN $12::bigint ELSE user_id END,
  project_id = CASE WHEN $13::bool THEN $14::int ELSE project_id END,
  status = CASE WHEN $15::bool THEN $16::int ELSE status END,
  status_code = CASE WHEN $17::bool THEN $18::int ELSE status_code END,
  error_message = CASE WHEN $19::bool THEN $20::text ELSE error_message END,
  time_spent_ms = CASE WHEN $21::bool THEN $22::int ELSE time_spent_ms END,
  ttft_ms = CASE WHEN $23::bool THEN $24::int ELSE ttft_ms END,
  input_tokens = CASE WHEN $25::bool THEN $26::int ELSE input_tokens END,
  output_tokens = CASE WHEN $27::bool THEN $28::int ELSE output_tokens END,
  cache_read_tokens = CASE WHEN $29::bool THEN $30::int ELSE cache_read_tokens END,
  cache_write_tokens = CASE WHEN $31::bool THEN $32::int ELSE cache_write_tokens END,
  cache_write_1h_tokens = CASE WHEN $33::bool THEN $34::int ELSE cache_write_1h_tokens END,
  model_cost = CASE WHEN $35::bool THEN $36::numeric ELSE model_cost END,
  model_cost_currency = CASE WHEN $37::bool THEN $38::text ELSE model_cost_currency END,
  finish_reason = CASE WHEN $39::bool THEN $40::int ELSE finish_reason END,
  inferred_provider = CASE WHEN $41::bool THEN $42::text ELSE inferred_provider END,
  inferred_model = CASE WHEN $43::bool THEN $44::text ELSE inferred_model END,
  inferred_model_source = CASE WHEN $45::bool THEN $46::smallint ELSE inferred_model_source END,
  user_message_preview = CASE WHEN $47::bool THEN $48::text ELSE user_message_preview END
WHERE id = $49::text AND created_at = $50::timestamp
`

type UpdateRequestParams struct {
	SetProviderID          bool             `json:"setProviderId"`
	ProviderID             pgtype.Int4      `json:"providerId"`
	SetModel               bool             `json:"setModel"`
	Model                  pgtype.Text      `json:"model"`
	SetUpstreamModel       bool             `json:"setUpstreamModel"`
	UpstreamModel          pgtype.Text      `json:"upstreamModel"`
	SetEndpointPath        bool             `json:"setEndpointPath"`
	EndpointPath           pgtype.Text      `json:"endpointPath"`
	SetApiKeyID            bool             `json:"setApiKeyId"`
	ApiKeyID               pgtype.Int4      `json:"apiKeyId"`
	SetUserID              bool             `json:"setUserId"`
	UserID                 pgtype.Int8      `json:"userId"`
	SetProjectID           bool             `json:"setProjectId"`
	ProjectID              pgtype.Int4      `json:"projectId"`
	SetStatus              bool             `json:"setStatus"`
	Status                 int32            `json:"status"`
	SetStatusCode          bool             `json:"setStatusCode"`
	StatusCode             pgtype.Int4      `json:"statusCode"`
	SetErrorMessage        bool             `json:"setErrorMessage"`
	ErrorMessage           pgtype.Text      `json:"errorMessage"`
	SetTimeSpentMs         bool             `json:"setTimeSpentMs"`
	TimeSpentMs            pgtype.Int4      `json:"timeSpentMs"`
	SetTtftMs              bool             `json:"setTtftMs"`
	TtftMs                 pgtype.Int4      `json:"ttftMs"`
	SetInputTokens         bool             `json:"setInputTokens"`
	InputTokens            pgtype.Int4      `json:"inputTokens"`
	SetOutputTokens        bool             `json:"setOutputTokens"`
	OutputTokens           pgtype.Int4      `json:"outputTokens"`
	SetCacheReadTokens     bool             `json:"setCacheReadTokens"`
	CacheReadTokens        pgtype.Int4      `json:"cacheReadTokens"`
	SetCacheWriteTokens    bool             `json:"setCacheWriteTokens"`
	CacheWriteTokens       pgtype.Int4      `json:"cacheWriteTokens"`
	SetCacheWrite1hTokens  bool             `json:"setCacheWrite1hTokens"`
	CacheWrite1hTokens     pgtype.Int4      `json:"cacheWrite1hTokens"`
	SetModelCost           bool             `json:"setModelCost"`
	ModelCost              pgtype.Numeric   `json:"modelCost"`
	SetModelCostCurrency   bool             `json:"setModelCostCurrency"`
	ModelCostCurrency      pgtype.Text      `json:"modelCostCurrency"`
	SetFinishReason        bool             `json:"setFinishReason"`
	FinishReason           pgtype.Int4      `json:"finishReason"`
	SetInferredProvider    bool             `json:"setInferredProvider"`
	InferredProvider       pgtype.Text      `json:"inferredProvider"`
	SetInferredModel       bool             `json:"setInferredModel"`
	InferredModel          pgtype.Text      `json:"inferredModel"`
	SetInferredModelSource bool             `json:"setInferredModelSource"`
	InferredModelSource    int16            `json:"inferredModelSource"`
	SetUserMessagePreview  bool             `json:"setUserMessagePreview"`
	UserMessagePreview     pgtype.Text      `json:"userMessagePreview"`
	ID                     string           `json:"id"`
	CreatedAt              pgtype.Timestamp `json:"createdAt"`
}

func (q *Queries) UpdateRequest(ctx context.Context, arg UpdateRequestParams) error {
	_, err := q.db.Exec(ctx, updateRequest,
		arg.SetProviderID,
		arg.ProviderID,
		arg.SetModel,
		arg.Model,
		arg.SetUpstreamModel,
		arg.UpstreamModel,
		arg.SetEndpointPath,
		arg.EndpointPath,
		arg.SetApiKeyID,
		arg.ApiKeyID,
		arg.SetUserID,
		arg.UserID,
		arg.SetProjectID,
		arg.ProjectID,
		arg.SetStatus,
		arg.Status,
		arg.SetStatusCode,
		arg.StatusCode,
		arg.SetErrorMessage,
		arg.ErrorMessage,
		arg.SetTimeSpentMs,
		arg.TimeSpentMs,
		arg.SetTtftMs,
		arg.TtftMs,
		arg.SetInputTokens,
		arg.InputTokens,
		arg.SetOutputTokens,
		arg.OutputTokens,
		arg.SetCacheReadTokens,
		arg.CacheReadTokens,
		arg.SetCacheWriteTokens,
		arg.CacheWriteTokens,
		arg.SetCacheWrite1hTokens,
		arg.CacheWrite1hTokens,
		arg.SetModelCost,
		arg.ModelCost,
		arg.SetModelCostCurrency,
		arg.ModelCostCurrency,
		arg.SetFinishReason,
		arg.FinishReason,
		arg.SetInferredProvider,
		arg.InferredProvider,
		arg.SetInferredModel,
		arg.InferredModel,
		arg.SetInferredModelSource,
		arg.InferredModelSource,
		arg.SetUserMessagePreview,
		arg.UserMessagePreview,
		arg.ID,
		arg.CreatedAt,
	)
	return err
}
