// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: request.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getRequest = `-- name: GetRequest :one
SELECT id, span_id, parent_span_id, provider_id, endpoint_path, api_key_id, model, input_tokens, cache_read_tokens, output_tokens, cache_write_tokens, status_code, error_message, ttft_ms, time_spent_ms, created_at FROM request WHERE id = $1
`

func (q *Queries) GetRequest(ctx context.Context, id string) (Request, error) {
	row := q.db.QueryRow(ctx, getRequest, id)
	var i Request
	err := row.Scan(
		&i.ID,
		&i.SpanID,
		&i.ParentSpanID,
		&i.ProviderID,
		&i.EndpointPath,
		&i.ApiKeyID,
		&i.Model,
		&i.InputTokens,
		&i.CacheReadTokens,
		&i.OutputTokens,
		&i.CacheWriteTokens,
		&i.StatusCode,
		&i.ErrorMessage,
		&i.TtftMs,
		&i.TimeSpentMs,
		&i.CreatedAt,
	)
	return i, err
}

const listRequests = `-- name: ListRequests :many
SELECT id, span_id, parent_span_id, provider_id, endpoint_path, api_key_id, model,
       input_tokens, cache_read_tokens, output_tokens, cache_write_tokens,
       status_code, error_message, ttft_ms, time_spent_ms, created_at
FROM request
WHERE
  ($1::int IS NULL OR provider_id = $1)
  AND ($2::text IS NULL OR endpoint_path = $2)
  AND ($3::text IS NULL OR model = $3)
  AND (
    $4::timestamp IS NULL
    OR (created_at, id) < ($4::timestamp, $5::text)
  )
ORDER BY created_at DESC, id DESC
LIMIT $6::int
`

type ListRequestsParams struct {
	ProviderID      pgtype.Int4      `json:"providerId"`
	EndpointPath    pgtype.Text      `json:"endpointPath"`
	Model           pgtype.Text      `json:"model"`
	CursorCreatedAt pgtype.Timestamp `json:"cursorCreatedAt"`
	CursorID        pgtype.Text      `json:"cursorId"`
	Limit           pgtype.Int4      `json:"limit"`
}

func (q *Queries) ListRequests(ctx context.Context, arg ListRequestsParams) ([]Request, error) {
	rows, err := q.db.Query(ctx, listRequests,
		arg.ProviderID,
		arg.EndpointPath,
		arg.Model,
		arg.CursorCreatedAt,
		arg.CursorID,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Request
	for rows.Next() {
		var i Request
		if err := rows.Scan(
			&i.ID,
			&i.SpanID,
			&i.ParentSpanID,
			&i.ProviderID,
			&i.EndpointPath,
			&i.ApiKeyID,
			&i.Model,
			&i.InputTokens,
			&i.CacheReadTokens,
			&i.OutputTokens,
			&i.CacheWriteTokens,
			&i.StatusCode,
			&i.ErrorMessage,
			&i.TtftMs,
			&i.TimeSpentMs,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
