// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: request.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getRequest = `-- name: GetRequest :one
SELECT id, span_id, parent_span_id, provider_id, endpoint_path, api_key_id, model, input_tokens, cache_read_tokens, output_tokens, cache_write_tokens, status_code, error_message, ttft_ms, time_spent_ms, created_at, type, status, upstream_model, model_cost, model_cost_currency, upstream_cost, upstream_cost_currency FROM request WHERE id = $1
`

func (q *Queries) GetRequest(ctx context.Context, id string) (Request, error) {
	row := q.db.QueryRow(ctx, getRequest, id)
	var i Request
	err := row.Scan(
		&i.ID,
		&i.SpanID,
		&i.ParentSpanID,
		&i.ProviderID,
		&i.EndpointPath,
		&i.ApiKeyID,
		&i.Model,
		&i.InputTokens,
		&i.CacheReadTokens,
		&i.OutputTokens,
		&i.CacheWriteTokens,
		&i.StatusCode,
		&i.ErrorMessage,
		&i.TtftMs,
		&i.TimeSpentMs,
		&i.CreatedAt,
		&i.Type,
		&i.Status,
		&i.UpstreamModel,
		&i.ModelCost,
		&i.ModelCostCurrency,
		&i.UpstreamCost,
		&i.UpstreamCostCurrency,
	)
	return i, err
}

const listRequests = `-- name: ListRequests :many
SELECT id, span_id, parent_span_id, type, status, provider_id, endpoint_path, api_key_id, model,
       upstream_model, input_tokens, cache_read_tokens, output_tokens, cache_write_tokens,
       status_code, error_message, ttft_ms, time_spent_ms, created_at,
       model_cost, model_cost_currency, upstream_cost, upstream_cost_currency
FROM request
WHERE
  ($1::int IS NULL OR type = $1)
  AND ($2::int IS NULL OR provider_id = $2)
  AND ($3::text IS NULL OR endpoint_path = $3)
  AND ($4::text IS NULL OR model = $4)
  AND ($5::text IS NULL OR upstream_model = $5)
  AND (
    $6::timestamp IS NULL
    OR (created_at, id) < ($6::timestamp, $7::text)
  )
ORDER BY created_at DESC, id DESC
LIMIT $8::int
`

type ListRequestsParams struct {
	Type            pgtype.Int4      `json:"type"`
	ProviderID      pgtype.Int4      `json:"providerId"`
	EndpointPath    pgtype.Text      `json:"endpointPath"`
	Model           pgtype.Text      `json:"model"`
	UpstreamModel   pgtype.Text      `json:"upstreamModel"`
	CursorCreatedAt pgtype.Timestamp `json:"cursorCreatedAt"`
	CursorID        pgtype.Text      `json:"cursorId"`
	Limit           pgtype.Int4      `json:"limit"`
}

type ListRequestsRow struct {
	ID                   string           `json:"id"`
	SpanID               pgtype.Text      `json:"spanId"`
	ParentSpanID         pgtype.Text      `json:"parentSpanId"`
	Type                 int32            `json:"type"`
	Status               int32            `json:"status"`
	ProviderID           pgtype.Int4      `json:"providerId"`
	EndpointPath         pgtype.Text      `json:"endpointPath"`
	ApiKeyID             pgtype.Int4      `json:"apiKeyId"`
	Model                pgtype.Text      `json:"model"`
	UpstreamModel        pgtype.Text      `json:"upstreamModel"`
	InputTokens          pgtype.Int4      `json:"inputTokens"`
	CacheReadTokens      pgtype.Int4      `json:"cacheReadTokens"`
	OutputTokens         pgtype.Int4      `json:"outputTokens"`
	CacheWriteTokens     pgtype.Int4      `json:"cacheWriteTokens"`
	StatusCode           pgtype.Int4      `json:"statusCode"`
	ErrorMessage         pgtype.Text      `json:"errorMessage"`
	TtftMs               pgtype.Int4      `json:"ttftMs"`
	TimeSpentMs          pgtype.Int4      `json:"timeSpentMs"`
	CreatedAt            pgtype.Timestamp `json:"createdAt"`
	ModelCost            pgtype.Numeric   `json:"modelCost"`
	ModelCostCurrency    pgtype.Text      `json:"modelCostCurrency"`
	UpstreamCost         pgtype.Numeric   `json:"upstreamCost"`
	UpstreamCostCurrency pgtype.Text      `json:"upstreamCostCurrency"`
}

func (q *Queries) ListRequests(ctx context.Context, arg ListRequestsParams) ([]ListRequestsRow, error) {
	rows, err := q.db.Query(ctx, listRequests,
		arg.Type,
		arg.ProviderID,
		arg.EndpointPath,
		arg.Model,
		arg.UpstreamModel,
		arg.CursorCreatedAt,
		arg.CursorID,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListRequestsRow
	for rows.Next() {
		var i ListRequestsRow
		if err := rows.Scan(
			&i.ID,
			&i.SpanID,
			&i.ParentSpanID,
			&i.Type,
			&i.Status,
			&i.ProviderID,
			&i.EndpointPath,
			&i.ApiKeyID,
			&i.Model,
			&i.UpstreamModel,
			&i.InputTokens,
			&i.CacheReadTokens,
			&i.OutputTokens,
			&i.CacheWriteTokens,
			&i.StatusCode,
			&i.ErrorMessage,
			&i.TtftMs,
			&i.TimeSpentMs,
			&i.CreatedAt,
			&i.ModelCost,
			&i.ModelCostCurrency,
			&i.UpstreamCost,
			&i.UpstreamCostCurrency,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRequestsBySpan = `-- name: ListRequestsBySpan :many
WITH anchor AS (
  SELECT request.span_id FROM request WHERE request.id = $1
)
SELECT r.id, r.span_id, r.parent_span_id, r.type, r.status, r.provider_id, r.endpoint_path,
       r.api_key_id, r.model, r.upstream_model, r.input_tokens, r.cache_read_tokens, r.output_tokens,
       r.cache_write_tokens, r.status_code, r.error_message, r.ttft_ms, r.time_spent_ms,
       r.created_at,
       r.model_cost, r.model_cost_currency, r.upstream_cost, r.upstream_cost_currency
FROM request r, anchor
WHERE r.span_id = anchor.span_id
ORDER BY r.created_at ASC, r.id ASC
`

type ListRequestsBySpanRow struct {
	ID                   string           `json:"id"`
	SpanID               pgtype.Text      `json:"spanId"`
	ParentSpanID         pgtype.Text      `json:"parentSpanId"`
	Type                 int32            `json:"type"`
	Status               int32            `json:"status"`
	ProviderID           pgtype.Int4      `json:"providerId"`
	EndpointPath         pgtype.Text      `json:"endpointPath"`
	ApiKeyID             pgtype.Int4      `json:"apiKeyId"`
	Model                pgtype.Text      `json:"model"`
	UpstreamModel        pgtype.Text      `json:"upstreamModel"`
	InputTokens          pgtype.Int4      `json:"inputTokens"`
	CacheReadTokens      pgtype.Int4      `json:"cacheReadTokens"`
	OutputTokens         pgtype.Int4      `json:"outputTokens"`
	CacheWriteTokens     pgtype.Int4      `json:"cacheWriteTokens"`
	StatusCode           pgtype.Int4      `json:"statusCode"`
	ErrorMessage         pgtype.Text      `json:"errorMessage"`
	TtftMs               pgtype.Int4      `json:"ttftMs"`
	TimeSpentMs          pgtype.Int4      `json:"timeSpentMs"`
	CreatedAt            pgtype.Timestamp `json:"createdAt"`
	ModelCost            pgtype.Numeric   `json:"modelCost"`
	ModelCostCurrency    pgtype.Text      `json:"modelCostCurrency"`
	UpstreamCost         pgtype.Numeric   `json:"upstreamCost"`
	UpstreamCostCurrency pgtype.Text      `json:"upstreamCostCurrency"`
}

func (q *Queries) ListRequestsBySpan(ctx context.Context, id string) ([]ListRequestsBySpanRow, error) {
	rows, err := q.db.Query(ctx, listRequestsBySpan, id)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListRequestsBySpanRow
	for rows.Next() {
		var i ListRequestsBySpanRow
		if err := rows.Scan(
			&i.ID,
			&i.SpanID,
			&i.ParentSpanID,
			&i.Type,
			&i.Status,
			&i.ProviderID,
			&i.EndpointPath,
			&i.ApiKeyID,
			&i.Model,
			&i.UpstreamModel,
			&i.InputTokens,
			&i.CacheReadTokens,
			&i.OutputTokens,
			&i.CacheWriteTokens,
			&i.StatusCode,
			&i.ErrorMessage,
			&i.TtftMs,
			&i.TimeSpentMs,
			&i.CreatedAt,
			&i.ModelCost,
			&i.ModelCostCurrency,
			&i.UpstreamCost,
			&i.UpstreamCostCurrency,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateRequestMetrics = `-- name: UpdateRequestMetrics :exec
UPDATE request
SET ttft_ms = $2, input_tokens = $3, output_tokens = $4,
    cache_read_tokens = $5, cache_write_tokens = $6
WHERE id = $1
`

type UpdateRequestMetricsParams struct {
	ID               string      `json:"id"`
	TtftMs           pgtype.Int4 `json:"ttftMs"`
	InputTokens      pgtype.Int4 `json:"inputTokens"`
	OutputTokens     pgtype.Int4 `json:"outputTokens"`
	CacheReadTokens  pgtype.Int4 `json:"cacheReadTokens"`
	CacheWriteTokens pgtype.Int4 `json:"cacheWriteTokens"`
}

func (q *Queries) UpdateRequestMetrics(ctx context.Context, arg UpdateRequestMetricsParams) error {
	_, err := q.db.Exec(ctx, updateRequestMetrics,
		arg.ID,
		arg.TtftMs,
		arg.InputTokens,
		arg.OutputTokens,
		arg.CacheReadTokens,
		arg.CacheWriteTokens,
	)
	return err
}

const updateRequestModel = `-- name: UpdateRequestModel :exec
UPDATE request SET model = $2 WHERE id = $1
`

type UpdateRequestModelParams struct {
	ID    string      `json:"id"`
	Model pgtype.Text `json:"model"`
}

func (q *Queries) UpdateRequestModel(ctx context.Context, arg UpdateRequestModelParams) error {
	_, err := q.db.Exec(ctx, updateRequestModel, arg.ID, arg.Model)
	return err
}

const updateRequestOnComplete = `-- name: UpdateRequestOnComplete :exec
UPDATE request
SET status_code = $2, error_message = $3, time_spent_ms = $4, status = $5,
    ttft_ms = $6, input_tokens = $7, output_tokens = $8,
    cache_read_tokens = $9, cache_write_tokens = $10,
    model_cost = $11, model_cost_currency = $12,
    upstream_cost = $13, upstream_cost_currency = $14
WHERE id = $1
`

type UpdateRequestOnCompleteParams struct {
	ID                   string         `json:"id"`
	StatusCode           pgtype.Int4    `json:"statusCode"`
	ErrorMessage         pgtype.Text    `json:"errorMessage"`
	TimeSpentMs          pgtype.Int4    `json:"timeSpentMs"`
	Status               int32          `json:"status"`
	TtftMs               pgtype.Int4    `json:"ttftMs"`
	InputTokens          pgtype.Int4    `json:"inputTokens"`
	OutputTokens         pgtype.Int4    `json:"outputTokens"`
	CacheReadTokens      pgtype.Int4    `json:"cacheReadTokens"`
	CacheWriteTokens     pgtype.Int4    `json:"cacheWriteTokens"`
	ModelCost            pgtype.Numeric `json:"modelCost"`
	ModelCostCurrency    pgtype.Text    `json:"modelCostCurrency"`
	UpstreamCost         pgtype.Numeric `json:"upstreamCost"`
	UpstreamCostCurrency pgtype.Text    `json:"upstreamCostCurrency"`
}

func (q *Queries) UpdateRequestOnComplete(ctx context.Context, arg UpdateRequestOnCompleteParams) error {
	_, err := q.db.Exec(ctx, updateRequestOnComplete,
		arg.ID,
		arg.StatusCode,
		arg.ErrorMessage,
		arg.TimeSpentMs,
		arg.Status,
		arg.TtftMs,
		arg.InputTokens,
		arg.OutputTokens,
		arg.CacheReadTokens,
		arg.CacheWriteTokens,
		arg.ModelCost,
		arg.ModelCostCurrency,
		arg.UpstreamCost,
		arg.UpstreamCostCurrency,
	)
	return err
}

const updateRequestOnHeader = `-- name: UpdateRequestOnHeader :exec
UPDATE request
SET provider_id = $2, model = $3, upstream_model = $4, endpoint_path = $5, api_key_id = $6, status = $7
WHERE id = $1
`

type UpdateRequestOnHeaderParams struct {
	ID            string      `json:"id"`
	ProviderID    pgtype.Int4 `json:"providerId"`
	Model         pgtype.Text `json:"model"`
	UpstreamModel pgtype.Text `json:"upstreamModel"`
	EndpointPath  pgtype.Text `json:"endpointPath"`
	ApiKeyID      pgtype.Int4 `json:"apiKeyId"`
	Status        int32       `json:"status"`
}

func (q *Queries) UpdateRequestOnHeader(ctx context.Context, arg UpdateRequestOnHeaderParams) error {
	_, err := q.db.Exec(ctx, updateRequestOnHeader,
		arg.ID,
		arg.ProviderID,
		arg.Model,
		arg.UpstreamModel,
		arg.EndpointPath,
		arg.ApiKeyID,
		arg.Status,
	)
	return err
}
