// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: routing.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getApiKeyByHash = `-- name: GetApiKeyByHash :one
SELECT id, name, api_key_hash, api_key_masked, annotations FROM api_key WHERE api_key_hash = $1 LIMIT 1
`

func (q *Queries) GetApiKeyByHash(ctx context.Context, apiKeyHash []byte) (ApiKey, error) {
	row := q.db.QueryRow(ctx, getApiKeyByHash, apiKeyHash)
	var i ApiKey
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.ApiKeyHash,
		&i.ApiKeyMasked,
		&i.Annotations,
	)
	return i, err
}

const getEndpointByPath = `-- name: GetEndpointByPath :one
SELECT path, name, model_path, credentials_resolver FROM endpoint WHERE path = $1 LIMIT 1
`

func (q *Queries) GetEndpointByPath(ctx context.Context, path string) (Endpoint, error) {
	row := q.db.QueryRow(ctx, getEndpointByPath, path)
	var i Endpoint
	err := row.Scan(
		&i.Path,
		&i.Name,
		&i.ModelPath,
		&i.CredentialsResolver,
	)
	return i, err
}

const getProvidersByEndpointAndModel = `-- name: GetProvidersByEndpointAndModel :many
SELECT mpe.model_name, mpe.provider_id, mpe.endpoint_path, mpe.upstream_model_name, mpe.priority, mpe.annotations, p.name AS provider_name, p.credentials AS provider_credentials, p.priority AS provider_priority, pe.upstream_url, p.annotations AS provider_annotations
  FROM model_provider_endpoint AS mpe
  LEFT JOIN provider AS p ON mpe.provider_id = p.id
  LEFT JOIN provider_endpoint AS pe ON mpe.provider_id = pe.provider_id AND mpe.endpoint_path = pe.endpoint_path
  WHERE mpe.endpoint_path = $1 AND mpe.model_name = $2
`

type GetProvidersByEndpointAndModelParams struct {
	EndpointPath string `json:"endpointPath"`
	ModelName    string `json:"modelName"`
}

type GetProvidersByEndpointAndModelRow struct {
	ModelName           string      `json:"modelName"`
	ProviderID          int32       `json:"providerId"`
	EndpointPath        string      `json:"endpointPath"`
	UpstreamModelName   pgtype.Text `json:"upstreamModelName"`
	Priority            int32       `json:"priority"`
	Annotations         []byte      `json:"annotations"`
	ProviderName        pgtype.Text `json:"providerName"`
	ProviderCredentials pgtype.Text `json:"providerCredentials"`
	ProviderPriority    pgtype.Int4 `json:"providerPriority"`
	UpstreamUrl         pgtype.Text `json:"upstreamUrl"`
	ProviderAnnotations []byte      `json:"providerAnnotations"`
}

func (q *Queries) GetProvidersByEndpointAndModel(ctx context.Context, arg GetProvidersByEndpointAndModelParams) ([]GetProvidersByEndpointAndModelRow, error) {
	rows, err := q.db.Query(ctx, getProvidersByEndpointAndModel, arg.EndpointPath, arg.ModelName)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetProvidersByEndpointAndModelRow
	for rows.Next() {
		var i GetProvidersByEndpointAndModelRow
		if err := rows.Scan(
			&i.ModelName,
			&i.ProviderID,
			&i.EndpointPath,
			&i.UpstreamModelName,
			&i.Priority,
			&i.Annotations,
			&i.ProviderName,
			&i.ProviderCredentials,
			&i.ProviderPriority,
			&i.UpstreamUrl,
			&i.ProviderAnnotations,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertRequest = `-- name: InsertRequest :one
INSERT INTO request (
  id, span_id, parent_span_id, type, status,
  provider_id, endpoint_path, api_key_id, model,
  input_tokens, cache_read_tokens, output_tokens, cache_write_tokens,
  status_code, error_message, ttft_ms, time_spent_ms
) VALUES (
  $1, $2, $3, $4, $5,
  $6, $7, $8, $9,
  $10, $11, $12, $13,
  $14, $15, $16, $17
)
RETURNING created_at
`

type InsertRequestParams struct {
	ID               string      `json:"id"`
	SpanID           pgtype.Text `json:"spanId"`
	ParentSpanID     pgtype.Text `json:"parentSpanId"`
	Type             int32       `json:"type"`
	Status           int32       `json:"status"`
	ProviderID       pgtype.Int4 `json:"providerId"`
	EndpointPath     pgtype.Text `json:"endpointPath"`
	ApiKeyID         pgtype.Int4 `json:"apiKeyId"`
	Model            pgtype.Text `json:"model"`
	InputTokens      pgtype.Int4 `json:"inputTokens"`
	CacheReadTokens  pgtype.Int4 `json:"cacheReadTokens"`
	OutputTokens     pgtype.Int4 `json:"outputTokens"`
	CacheWriteTokens pgtype.Int4 `json:"cacheWriteTokens"`
	StatusCode       pgtype.Int4 `json:"statusCode"`
	ErrorMessage     pgtype.Text `json:"errorMessage"`
	TtftMs           pgtype.Int4 `json:"ttftMs"`
	TimeSpentMs      pgtype.Int4 `json:"timeSpentMs"`
}

func (q *Queries) InsertRequest(ctx context.Context, arg InsertRequestParams) (pgtype.Timestamp, error) {
	row := q.db.QueryRow(ctx, insertRequest,
		arg.ID,
		arg.SpanID,
		arg.ParentSpanID,
		arg.Type,
		arg.Status,
		arg.ProviderID,
		arg.EndpointPath,
		arg.ApiKeyID,
		arg.Model,
		arg.InputTokens,
		arg.CacheReadTokens,
		arg.OutputTokens,
		arg.CacheWriteTokens,
		arg.StatusCode,
		arg.ErrorMessage,
		arg.TtftMs,
		arg.TimeSpentMs,
	)
	var created_at pgtype.Timestamp
	err := row.Scan(&created_at)
	return created_at, err
}
