// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: routing.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getApiKeyByHash = `-- name: GetApiKeyByHash :one
SELECT id, name, api_key_hash, api_key_masked, annotations FROM api_key WHERE api_key_hash = $1 LIMIT 1
`

func (q *Queries) GetApiKeyByHash(ctx context.Context, apiKeyHash []byte) (ApiKey, error) {
	row := q.db.QueryRow(ctx, getApiKeyByHash, apiKeyHash)
	var i ApiKey
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.ApiKeyHash,
		&i.ApiKeyMasked,
		&i.Annotations,
	)
	return i, err
}

const getEndpointByPath = `-- name: GetEndpointByPath :one
SELECT id, name, path, model_path, credentials_resolver FROM endpoint WHERE path = $1 LIMIT 1
`

func (q *Queries) GetEndpointByPath(ctx context.Context, path string) (Endpoint, error) {
	row := q.db.QueryRow(ctx, getEndpointByPath, path)
	var i Endpoint
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Path,
		&i.ModelPath,
		&i.CredentialsResolver,
	)
	return i, err
}

const getProvidersByEndpointAndModel = `-- name: GetProvidersByEndpointAndModel :many
SELECT mpe.model_name, mpe.provider_id, mpe.endpoint_id, mpe.upstream_model_name, mpe.priority, mpe.annotations, p.name AS provider_name, p.credentials AS provider_credentials
  FROM model_provider_endpoint AS mpe
  LEFT JOIN provider AS p ON mpe.provider_id = p.id
  WHERE mpe.endpoint_id = $1 AND mpe.model_name = $2
`

type GetProvidersByEndpointAndModelParams struct {
	EndpointID int32  `json:"endpointId"`
	ModelName  string `json:"modelName"`
}

type GetProvidersByEndpointAndModelRow struct {
	ModelName           string      `json:"modelName"`
	ProviderID          int32       `json:"providerId"`
	EndpointID          int32       `json:"endpointId"`
	UpstreamModelName   pgtype.Text `json:"upstreamModelName"`
	Priority            int32       `json:"priority"`
	Annotations         []byte      `json:"annotations"`
	ProviderName        pgtype.Text `json:"providerName"`
	ProviderCredentials pgtype.Text `json:"providerCredentials"`
}

func (q *Queries) GetProvidersByEndpointAndModel(ctx context.Context, arg GetProvidersByEndpointAndModelParams) ([]GetProvidersByEndpointAndModelRow, error) {
	rows, err := q.db.Query(ctx, getProvidersByEndpointAndModel, arg.EndpointID, arg.ModelName)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetProvidersByEndpointAndModelRow
	for rows.Next() {
		var i GetProvidersByEndpointAndModelRow
		if err := rows.Scan(
			&i.ModelName,
			&i.ProviderID,
			&i.EndpointID,
			&i.UpstreamModelName,
			&i.Priority,
			&i.Annotations,
			&i.ProviderName,
			&i.ProviderCredentials,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
