// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: routing.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getEndpointByPath = `-- name: GetEndpointByPath :one
SELECT path, name, model_path, credentials_resolver, endpoint_type FROM endpoint WHERE path = $1 LIMIT 1
`

func (q *Queries) GetEndpointByPath(ctx context.Context, path string) (Endpoint, error) {
	row := q.db.QueryRow(ctx, getEndpointByPath, path)
	var i Endpoint
	err := row.Scan(
		&i.Path,
		&i.Name,
		&i.ModelPath,
		&i.CredentialsResolver,
		&i.EndpointType,
	)
	return i, err
}

const getProvidersByEndpoint = `-- name: GetProvidersByEndpoint :many
SELECT
  ''::text AS model_name,
  p.id AS provider_id,
  pe.endpoint_path,
  ''::text AS upstream_model_name,
  0::int AS priority,
  '{}'::jsonb AS annotations,
  p.name AS provider_name,
  p.credentials AS provider_credentials,
  p.priority AS provider_priority,
  pe.upstream_url,
  pe.credentials_resolver AS send_credentials_resolver,
  p.proxy_url,
  p.annotations AS provider_annotations,
  '{}'::jsonb AS model_annotations
FROM provider AS p
JOIN provider_endpoint AS pe ON pe.provider_id = p.id
WHERE pe.endpoint_path = $1::text
  AND p.disabled = FALSE
`

type GetProvidersByEndpointRow struct {
	ModelName               string      `json:"modelName"`
	ProviderID              int32       `json:"providerId"`
	EndpointPath            string      `json:"endpointPath"`
	UpstreamModelName       string      `json:"upstreamModelName"`
	Priority                int32       `json:"priority"`
	Annotations             []byte      `json:"annotations"`
	ProviderName            string      `json:"providerName"`
	ProviderCredentials     string      `json:"providerCredentials"`
	ProviderPriority        int32       `json:"providerPriority"`
	UpstreamUrl             string      `json:"upstreamUrl"`
	SendCredentialsResolver int32       `json:"sendCredentialsResolver"`
	ProxyUrl                pgtype.Text `json:"proxyUrl"`
	ProviderAnnotations     []byte      `json:"providerAnnotations"`
	ModelAnnotations        []byte      `json:"modelAnnotations"`
}

// Sister query to GetProvidersByEndpointAndModel for "no-model" endpoints
// (endpoint.model_path = ”). Returns every non-disabled provider bound to the
// given endpoint_path, with model-related columns flattened to constants so the
// consuming Go code can treat both shapes uniformly.
func (q *Queries) GetProvidersByEndpoint(ctx context.Context, endpointPath string) ([]GetProvidersByEndpointRow, error) {
	rows, err := q.db.Query(ctx, getProvidersByEndpoint, endpointPath)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetProvidersByEndpointRow
	for rows.Next() {
		var i GetProvidersByEndpointRow
		if err := rows.Scan(
			&i.ModelName,
			&i.ProviderID,
			&i.EndpointPath,
			&i.UpstreamModelName,
			&i.Priority,
			&i.Annotations,
			&i.ProviderName,
			&i.ProviderCredentials,
			&i.ProviderPriority,
			&i.UpstreamUrl,
			&i.SendCredentialsResolver,
			&i.ProxyUrl,
			&i.ProviderAnnotations,
			&i.ModelAnnotations,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getProvidersByEndpointAndModel = `-- name: GetProvidersByEndpointAndModel :many
SELECT
  $1::text AS model_name,
  p.id AS provider_id,
  pe.endpoint_path,
  COALESCE(elem ->> 'upstreamModelName', '')::text AS upstream_model_name,
  COALESCE((elem ->> 'priority')::int, 0)::int AS priority,
  (COALESCE(elem -> 'annotations', '{}'::jsonb))::jsonb AS annotations,
  p.name AS provider_name,
  p.credentials AS provider_credentials,
  p.priority AS provider_priority,
  pe.upstream_url,
  pe.credentials_resolver AS send_credentials_resolver,
  p.proxy_url,
  p.annotations AS provider_annotations,
  m.annotations AS model_annotations
FROM provider AS p
JOIN provider_endpoint AS pe ON pe.provider_id = p.id
JOIN model AS m ON m.name = $1::text
CROSS JOIN LATERAL jsonb_array_elements(p.provider_models) AS elem
WHERE pe.endpoint_path = $2::text
  AND p.provider_models @> jsonb_build_array(jsonb_build_object('model', $1::text))
  AND elem ->> 'model' = $1::text
  AND p.disabled = FALSE
  AND m.disabled = FALSE
  AND COALESCE((elem ->> 'disabled')::boolean, false) = false
  AND (
    elem -> 'endpoints' IS NULL
    OR jsonb_typeof(elem -> 'endpoints') <> 'array'
    OR jsonb_array_length(elem -> 'endpoints') = 0
    OR elem -> 'endpoints' @> to_jsonb(ARRAY[pe.endpoint_path])
  )
`

type GetProvidersByEndpointAndModelParams struct {
	ModelName    string `json:"modelName"`
	EndpointPath string `json:"endpointPath"`
}

type GetProvidersByEndpointAndModelRow struct {
	ModelName               string      `json:"modelName"`
	ProviderID              int32       `json:"providerId"`
	EndpointPath            string      `json:"endpointPath"`
	UpstreamModelName       string      `json:"upstreamModelName"`
	Priority                int32       `json:"priority"`
	Annotations             []byte      `json:"annotations"`
	ProviderName            string      `json:"providerName"`
	ProviderCredentials     string      `json:"providerCredentials"`
	ProviderPriority        int32       `json:"providerPriority"`
	UpstreamUrl             string      `json:"upstreamUrl"`
	SendCredentialsResolver int32       `json:"sendCredentialsResolver"`
	ProxyUrl                pgtype.Text `json:"proxyUrl"`
	ProviderAnnotations     []byte      `json:"providerAnnotations"`
	ModelAnnotations        []byte      `json:"modelAnnotations"`
}

func (q *Queries) GetProvidersByEndpointAndModel(ctx context.Context, arg GetProvidersByEndpointAndModelParams) ([]GetProvidersByEndpointAndModelRow, error) {
	rows, err := q.db.Query(ctx, getProvidersByEndpointAndModel, arg.ModelName, arg.EndpointPath)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetProvidersByEndpointAndModelRow
	for rows.Next() {
		var i GetProvidersByEndpointAndModelRow
		if err := rows.Scan(
			&i.ModelName,
			&i.ProviderID,
			&i.EndpointPath,
			&i.UpstreamModelName,
			&i.Priority,
			&i.Annotations,
			&i.ProviderName,
			&i.ProviderCredentials,
			&i.ProviderPriority,
			&i.UpstreamUrl,
			&i.SendCredentialsResolver,
			&i.ProxyUrl,
			&i.ProviderAnnotations,
			&i.ModelAnnotations,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getProvidersByEndpointTypesAndModel = `-- name: GetProvidersByEndpointTypesAndModel :many
SELECT
  $1::text AS model_name,
  p.id AS provider_id,
  pe.endpoint_path,
  e.endpoint_type AS endpoint_type,
  COALESCE(elem ->> 'upstreamModelName', '')::text AS upstream_model_name,
  COALESCE((elem ->> 'priority')::int, 0)::int AS priority,
  (COALESCE(elem -> 'annotations', '{}'::jsonb))::jsonb AS annotations,
  p.name AS provider_name,
  p.credentials AS provider_credentials,
  p.priority AS provider_priority,
  pe.upstream_url,
  pe.credentials_resolver AS send_credentials_resolver,
  p.proxy_url,
  p.annotations AS provider_annotations,
  m.annotations AS model_annotations
FROM provider AS p
JOIN provider_endpoint AS pe ON pe.provider_id = p.id
JOIN endpoint AS e ON e.path = pe.endpoint_path
JOIN model AS m ON m.name = $1::text
CROSS JOIN LATERAL jsonb_array_elements(p.provider_models) AS elem
WHERE e.endpoint_type = ANY($2::int[])
  AND p.provider_models @> jsonb_build_array(jsonb_build_object('model', $1::text))
  AND elem ->> 'model' = $1::text
  AND p.disabled = FALSE
  AND m.disabled = FALSE
  AND COALESCE((elem ->> 'disabled')::boolean, false) = false
  AND (
    elem -> 'endpoints' IS NULL
    OR jsonb_typeof(elem -> 'endpoints') <> 'array'
    OR jsonb_array_length(elem -> 'endpoints') = 0
    OR elem -> 'endpoints' @> to_jsonb(ARRAY[pe.endpoint_path])
  )
`

type GetProvidersByEndpointTypesAndModelParams struct {
	ModelName     string  `json:"modelName"`
	EndpointTypes []int32 `json:"endpointTypes"`
}

type GetProvidersByEndpointTypesAndModelRow struct {
	ModelName               string      `json:"modelName"`
	ProviderID              int32       `json:"providerId"`
	EndpointPath            string      `json:"endpointPath"`
	EndpointType            int32       `json:"endpointType"`
	UpstreamModelName       string      `json:"upstreamModelName"`
	Priority                int32       `json:"priority"`
	Annotations             []byte      `json:"annotations"`
	ProviderName            string      `json:"providerName"`
	ProviderCredentials     string      `json:"providerCredentials"`
	ProviderPriority        int32       `json:"providerPriority"`
	UpstreamUrl             string      `json:"upstreamUrl"`
	SendCredentialsResolver int32       `json:"sendCredentialsResolver"`
	ProxyUrl                pgtype.Text `json:"proxyUrl"`
	ProviderAnnotations     []byte      `json:"providerAnnotations"`
	ModelAnnotations        []byte      `json:"modelAnnotations"`
}

// Sister query to GetProvidersByEndpointAndModel that selects across a SET of
// endpoint types instead of a single endpoint path. The unified gateway
// routes (/v1/messages, /v1/responses, /v1/chat/completions, and the two
// Gemini variants) compute the type set from (source format, stream flag)
// and call this. Returns the same column shape as the path-based query plus
// e.endpoint_type so the handler can pick the right transformer per row.
func (q *Queries) GetProvidersByEndpointTypesAndModel(ctx context.Context, arg GetProvidersByEndpointTypesAndModelParams) ([]GetProvidersByEndpointTypesAndModelRow, error) {
	rows, err := q.db.Query(ctx, getProvidersByEndpointTypesAndModel, arg.ModelName, arg.EndpointTypes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetProvidersByEndpointTypesAndModelRow
	for rows.Next() {
		var i GetProvidersByEndpointTypesAndModelRow
		if err := rows.Scan(
			&i.ModelName,
			&i.ProviderID,
			&i.EndpointPath,
			&i.EndpointType,
			&i.UpstreamModelName,
			&i.Priority,
			&i.Annotations,
			&i.ProviderName,
			&i.ProviderCredentials,
			&i.ProviderPriority,
			&i.UpstreamUrl,
			&i.SendCredentialsResolver,
			&i.ProxyUrl,
			&i.ProviderAnnotations,
			&i.ModelAnnotations,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertRequest = `-- name: InsertRequest :one
INSERT INTO request (
  id, span_id, parent_span_id, type, status,
  provider_id, endpoint_path, api_key_id, model, upstream_model,
  input_tokens, cache_read_tokens, output_tokens, cache_write_tokens, cache_write_1h_tokens,
  status_code, error_message, ttft_ms, time_spent_ms,
  user_message_preview, project_id, created_at
) VALUES (
  $1, $2, $3, $4, $5,
  $6, $7, $8, $9, $10,
  $11, $12, $13, $14, $15,
  $16, $17, $18, $19,
  $20, $21, $22
)
RETURNING created_at
`

type InsertRequestParams struct {
	ID                 string           `json:"id"`
	SpanID             pgtype.Text      `json:"spanId"`
	ParentSpanID       pgtype.Text      `json:"parentSpanId"`
	Type               int32            `json:"type"`
	Status             int32            `json:"status"`
	ProviderID         pgtype.Int4      `json:"providerId"`
	EndpointPath       pgtype.Text      `json:"endpointPath"`
	ApiKeyID           pgtype.Int4      `json:"apiKeyId"`
	Model              pgtype.Text      `json:"model"`
	UpstreamModel      pgtype.Text      `json:"upstreamModel"`
	InputTokens        pgtype.Int4      `json:"inputTokens"`
	CacheReadTokens    pgtype.Int4      `json:"cacheReadTokens"`
	OutputTokens       pgtype.Int4      `json:"outputTokens"`
	CacheWriteTokens   pgtype.Int4      `json:"cacheWriteTokens"`
	CacheWrite1hTokens pgtype.Int4      `json:"cacheWrite1hTokens"`
	StatusCode         pgtype.Int4      `json:"statusCode"`
	ErrorMessage       pgtype.Text      `json:"errorMessage"`
	TtftMs             pgtype.Int4      `json:"ttftMs"`
	TimeSpentMs        pgtype.Int4      `json:"timeSpentMs"`
	UserMessagePreview pgtype.Text      `json:"userMessagePreview"`
	ProjectID          pgtype.Int4      `json:"projectId"`
	CreatedAt          pgtype.Timestamp `json:"createdAt"`
}

func (q *Queries) InsertRequest(ctx context.Context, arg InsertRequestParams) (pgtype.Timestamp, error) {
	row := q.db.QueryRow(ctx, insertRequest,
		arg.ID,
		arg.SpanID,
		arg.ParentSpanID,
		arg.Type,
		arg.Status,
		arg.ProviderID,
		arg.EndpointPath,
		arg.ApiKeyID,
		arg.Model,
		arg.UpstreamModel,
		arg.InputTokens,
		arg.CacheReadTokens,
		arg.OutputTokens,
		arg.CacheWriteTokens,
		arg.CacheWrite1hTokens,
		arg.StatusCode,
		arg.ErrorMessage,
		arg.TtftMs,
		arg.TimeSpentMs,
		arg.UserMessagePreview,
		arg.ProjectID,
		arg.CreatedAt,
	)
	var created_at pgtype.Timestamp
	err := row.Scan(&created_at)
	return created_at, err
}
