// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: script.sql

package db

import (
	"context"
)

const deleteScript = `-- name: DeleteScript :exec
DELETE FROM script WHERE id = $1
`

func (q *Queries) DeleteScript(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, deleteScript, id)
	return err
}

const getScript = `-- name: GetScript :one
SELECT id, name, source, enabled, created_at, updated_at FROM script WHERE id = $1 LIMIT 1
`

func (q *Queries) GetScript(ctx context.Context, id string) (Script, error) {
	row := q.db.QueryRow(ctx, getScript, id)
	var i Script
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Source,
		&i.Enabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertScript = `-- name: InsertScript :one
INSERT INTO script (id, name, source, enabled)
VALUES ($1, $2, $3, $4)
RETURNING id, name, source, enabled, created_at, updated_at
`

type InsertScriptParams struct {
	ID      string `json:"id"`
	Name    string `json:"name"`
	Source  string `json:"source"`
	Enabled bool   `json:"enabled"`
}

func (q *Queries) InsertScript(ctx context.Context, arg InsertScriptParams) (Script, error) {
	row := q.db.QueryRow(ctx, insertScript,
		arg.ID,
		arg.Name,
		arg.Source,
		arg.Enabled,
	)
	var i Script
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Source,
		&i.Enabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listEnabledScripts = `-- name: ListEnabledScripts :many
SELECT id, name, source, enabled, created_at, updated_at FROM script WHERE enabled = TRUE ORDER BY id ASC
`

func (q *Queries) ListEnabledScripts(ctx context.Context) ([]Script, error) {
	rows, err := q.db.Query(ctx, listEnabledScripts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Script
	for rows.Next() {
		var i Script
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Source,
			&i.Enabled,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listScripts = `-- name: ListScripts :many
SELECT id, name, source, enabled, created_at, updated_at FROM script ORDER BY created_at DESC, id DESC
`

func (q *Queries) ListScripts(ctx context.Context) ([]Script, error) {
	rows, err := q.db.Query(ctx, listScripts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Script
	for rows.Next() {
		var i Script
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Source,
			&i.Enabled,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateScript = `-- name: UpdateScript :one
UPDATE script
SET name = $2, source = $3, enabled = $4, updated_at = now()
WHERE id = $1
RETURNING id, name, source, enabled, created_at, updated_at
`

type UpdateScriptParams struct {
	ID      string `json:"id"`
	Name    string `json:"name"`
	Source  string `json:"source"`
	Enabled bool   `json:"enabled"`
}

func (q *Queries) UpdateScript(ctx context.Context, arg UpdateScriptParams) (Script, error) {
	row := q.db.QueryRow(ctx, updateScript,
		arg.ID,
		arg.Name,
		arg.Source,
		arg.Enabled,
	)
	var i Script
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Source,
		&i.Enabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
