// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: trace.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const backfillTrace = `-- name: BackfillTrace :exec
INSERT INTO traces (id, parent_span_id, first_request_at, last_request_at)
VALUES ($1, $2, $3, $4)
ON CONFLICT (parent_span_id) DO UPDATE
SET first_request_at = LEAST(traces.first_request_at, EXCLUDED.first_request_at),
    last_request_at = GREATEST(traces.last_request_at, EXCLUDED.last_request_at),
    updated_at = CURRENT_TIMESTAMP
`

type BackfillTraceParams struct {
	ID             string           `json:"id"`
	ParentSpanID   string           `json:"parentSpanId"`
	FirstRequestAt pgtype.Timestamp `json:"firstRequestAt"`
	LastRequestAt  pgtype.Timestamp `json:"lastRequestAt"`
}

func (q *Queries) BackfillTrace(ctx context.Context, arg BackfillTraceParams) error {
	_, err := q.db.Exec(ctx, backfillTrace,
		arg.ID,
		arg.ParentSpanID,
		arg.FirstRequestAt,
		arg.LastRequestAt,
	)
	return err
}

const listTraceBackfillCandidates = `-- name: ListTraceBackfillCandidates :many
WITH request_traces AS (
  SELECT parent_span_id, MIN(created_at)::timestamp AS first_request_at, MAX(created_at)::timestamp AS last_request_at
  FROM request
  WHERE parent_span_id IS NOT NULL AND parent_span_id <> ''
  GROUP BY parent_span_id
)
SELECT request_traces.parent_span_id, request_traces.first_request_at, request_traces.last_request_at
FROM request_traces
LEFT JOIN traces ON traces.parent_span_id = request_traces.parent_span_id
WHERE traces.parent_span_id IS NULL
  OR traces.first_request_at > request_traces.first_request_at
  OR traces.last_request_at < request_traces.last_request_at
ORDER BY request_traces.first_request_at, request_traces.parent_span_id
`

type ListTraceBackfillCandidatesRow struct {
	ParentSpanID   pgtype.Text      `json:"parentSpanId"`
	FirstRequestAt pgtype.Timestamp `json:"firstRequestAt"`
	LastRequestAt  pgtype.Timestamp `json:"lastRequestAt"`
}

func (q *Queries) ListTraceBackfillCandidates(ctx context.Context) ([]ListTraceBackfillCandidatesRow, error) {
	rows, err := q.db.Query(ctx, listTraceBackfillCandidates)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListTraceBackfillCandidatesRow
	for rows.Next() {
		var i ListTraceBackfillCandidatesRow
		if err := rows.Scan(&i.ParentSpanID, &i.FirstRequestAt, &i.LastRequestAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertTrace = `-- name: UpsertTrace :one
INSERT INTO traces (id, parent_span_id, first_request_at, last_request_at)
VALUES ($1, $2, $3, $3)
ON CONFLICT (parent_span_id) DO UPDATE
SET first_request_at = LEAST(traces.first_request_at, EXCLUDED.first_request_at),
    last_request_at = GREATEST(traces.last_request_at, EXCLUDED.last_request_at),
    updated_at = CURRENT_TIMESTAMP
RETURNING id, parent_span_id, first_request_at, last_request_at
`

type UpsertTraceParams struct {
	ID             string           `json:"id"`
	ParentSpanID   string           `json:"parentSpanId"`
	FirstRequestAt pgtype.Timestamp `json:"firstRequestAt"`
}

type UpsertTraceRow struct {
	ID             string           `json:"id"`
	ParentSpanID   string           `json:"parentSpanId"`
	FirstRequestAt pgtype.Timestamp `json:"firstRequestAt"`
	LastRequestAt  pgtype.Timestamp `json:"lastRequestAt"`
}

func (q *Queries) UpsertTrace(ctx context.Context, arg UpsertTraceParams) (UpsertTraceRow, error) {
	row := q.db.QueryRow(ctx, upsertTrace, arg.ID, arg.ParentSpanID, arg.FirstRequestAt)
	var i UpsertTraceRow
	err := row.Scan(
		&i.ID,
		&i.ParentSpanID,
		&i.FirstRequestAt,
		&i.LastRequestAt,
	)
	return i, err
}
