// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: user_session.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteExpiredUserSessions = `-- name: DeleteExpiredUserSessions :exec
DELETE FROM user_session WHERE user_id = $1 AND expires_at <= $2
`

type DeleteExpiredUserSessionsParams struct {
	UserID    int64              `json:"userId"`
	ExpiresAt pgtype.Timestamptz `json:"expiresAt"`
}

// DeleteExpiredUserSessions runs on every successful login and only touches the
// logging-in user's rows. Sessions of users who never come back are lazy garbage;
// they cost nothing but disk, so there is no background sweeper.
func (q *Queries) DeleteExpiredUserSessions(ctx context.Context, arg DeleteExpiredUserSessionsParams) error {
	_, err := q.db.Exec(ctx, deleteExpiredUserSessions, arg.UserID, arg.ExpiresAt)
	return err
}

const deleteUserSession = `-- name: DeleteUserSession :exec
DELETE FROM user_session WHERE id = $1
`

func (q *Queries) DeleteUserSession(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, deleteUserSession, id)
	return err
}

const deleteUserSessionsByUser = `-- name: DeleteUserSessionsByUser :exec
DELETE FROM user_session WHERE user_id = $1
`

func (q *Queries) DeleteUserSessionsByUser(ctx context.Context, userID int64) error {
	_, err := q.db.Exec(ctx, deleteUserSessionsByUser, userID)
	return err
}

const insertUserSession = `-- name: InsertUserSession :exec
INSERT INTO user_session (id, user_id, expires_at) VALUES ($1, $2, $3)
`

type InsertUserSessionParams struct {
	ID        string             `json:"id"`
	UserID    int64              `json:"userId"`
	ExpiresAt pgtype.Timestamptz `json:"expiresAt"`
}

func (q *Queries) InsertUserSession(ctx context.Context, arg InsertUserSessionParams) error {
	_, err := q.db.Exec(ctx, insertUserSession, arg.ID, arg.UserID, arg.ExpiresAt)
	return err
}

const touchUserSession = `-- name: TouchUserSession :one
WITH touched AS (
  UPDATE user_session SET expires_at = $1
  WHERE user_session.id = $2 AND user_session.expires_at > $3
  RETURNING user_id
)
SELECT app_user.id, app_user.display_name, app_user.is_admin, app_user.created_at, app_user.updated_at, app_user.disabled, app_user.annotations FROM app_user JOIN touched ON app_user.id = touched.user_id
`

type TouchUserSessionParams struct {
	NewExpiresAt pgtype.Timestamptz `json:"newExpiresAt"`
	ID           string             `json:"id"`
	Now          pgtype.Timestamptz `json:"now"`
}

// TouchUserSession reads a session and slides its expiry in one statement: the
// UPDATE is the read, so there is no window in which a just-expired row could be
// observed as live, and the JOIN folds the user lookup into the same round trip
// (a deleted user's session therefore returns no rows and reads as "no session").
// new_expires_at is now + session_ttl; both timestamps are supplied by Go like
// every other timestamp in this schema.
func (q *Queries) TouchUserSession(ctx context.Context, arg TouchUserSessionParams) (AppUser, error) {
	row := q.db.QueryRow(ctx, touchUserSession, arg.NewExpiresAt, arg.ID, arg.Now)
	var i AppUser
	err := row.Scan(
		&i.ID,
		&i.DisplayName,
		&i.IsAdmin,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Disabled,
		&i.Annotations,
	)
	return i, err
}
