// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: user.sql

package db

import (
	"context"
)

const getUserByID = `-- name: GetUserByID :one
SELECT id, display_name, is_admin, created_at, updated_at FROM app_user WHERE id = $1 LIMIT 1
`

func (q *Queries) GetUserByID(ctx context.Context, id int64) (AppUser, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i AppUser
	err := row.Scan(
		&i.ID,
		&i.DisplayName,
		&i.IsAdmin,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByIdentity = `-- name: GetUserByIdentity :one
SELECT u.id, u.display_name, u.is_admin, u.created_at, u.updated_at FROM app_user u
JOIN user_identity i ON i.user_id = u.id
WHERE i.provider = $1 AND i.identity = $2
LIMIT 1
`

type GetUserByIdentityParams struct {
	Provider string `json:"provider"`
	Identity string `json:"identity"`
}

func (q *Queries) GetUserByIdentity(ctx context.Context, arg GetUserByIdentityParams) (AppUser, error) {
	row := q.db.QueryRow(ctx, getUserByIdentity, arg.Provider, arg.Identity)
	var i AppUser
	err := row.Scan(
		&i.ID,
		&i.DisplayName,
		&i.IsAdmin,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertUser = `-- name: InsertUser :one
INSERT INTO app_user (display_name, is_admin) VALUES ($1, $2) RETURNING id, display_name, is_admin, created_at, updated_at
`

type InsertUserParams struct {
	DisplayName string `json:"displayName"`
	IsAdmin     bool   `json:"isAdmin"`
}

func (q *Queries) InsertUser(ctx context.Context, arg InsertUserParams) (AppUser, error) {
	row := q.db.QueryRow(ctx, insertUser, arg.DisplayName, arg.IsAdmin)
	var i AppUser
	err := row.Scan(
		&i.ID,
		&i.DisplayName,
		&i.IsAdmin,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertUserIdentity = `-- name: InsertUserIdentity :one
INSERT INTO user_identity (user_id, provider, identity)
VALUES ($1, $2, $3)
ON CONFLICT (provider, identity) DO NOTHING
RETURNING id, user_id, provider, identity, created_at
`

type InsertUserIdentityParams struct {
	UserID   int64  `json:"userId"`
	Provider string `json:"provider"`
	Identity string `json:"identity"`
}

func (q *Queries) InsertUserIdentity(ctx context.Context, arg InsertUserIdentityParams) (UserIdentity, error) {
	row := q.db.QueryRow(ctx, insertUserIdentity, arg.UserID, arg.Provider, arg.Identity)
	var i UserIdentity
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Provider,
		&i.Identity,
		&i.CreatedAt,
	)
	return i, err
}

const updateUserAdmin = `-- name: UpdateUserAdmin :one
UPDATE app_user SET is_admin = $2, updated_at = now() WHERE id = $1 RETURNING id, display_name, is_admin, created_at, updated_at
`

type UpdateUserAdminParams struct {
	ID      int64 `json:"id"`
	IsAdmin bool  `json:"isAdmin"`
}

func (q *Queries) UpdateUserAdmin(ctx context.Context, arg UpdateUserAdminParams) (AppUser, error) {
	row := q.db.QueryRow(ctx, updateUserAdmin, arg.ID, arg.IsAdmin)
	var i AppUser
	err := row.Scan(
		&i.ID,
		&i.DisplayName,
		&i.IsAdmin,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
