// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: user_setting.sql

package db

import (
	"context"
)

const deleteUserSetting = `-- name: DeleteUserSetting :execrows
DELETE FROM user_setting WHERE user_id = $1 AND key = $2
`

type DeleteUserSettingParams struct {
	UserID int64  `json:"userId"`
	Key    string `json:"key"`
}

func (q *Queries) DeleteUserSetting(ctx context.Context, arg DeleteUserSettingParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteUserSetting, arg.UserID, arg.Key)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getUserSetting = `-- name: GetUserSetting :one
SELECT user_id, key, value, updated_at FROM user_setting WHERE user_id = $1 AND key = $2 LIMIT 1
`

type GetUserSettingParams struct {
	UserID int64  `json:"userId"`
	Key    string `json:"key"`
}

func (q *Queries) GetUserSetting(ctx context.Context, arg GetUserSettingParams) (UserSetting, error) {
	row := q.db.QueryRow(ctx, getUserSetting, arg.UserID, arg.Key)
	var i UserSetting
	err := row.Scan(
		&i.UserID,
		&i.Key,
		&i.Value,
		&i.UpdatedAt,
	)
	return i, err
}

const listUserSettings = `-- name: ListUserSettings :many
SELECT user_id, key, value, updated_at FROM user_setting WHERE user_id = $1 ORDER BY key
`

func (q *Queries) ListUserSettings(ctx context.Context, userID int64) ([]UserSetting, error) {
	rows, err := q.db.Query(ctx, listUserSettings, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []UserSetting
	for rows.Next() {
		var i UserSetting
		if err := rows.Scan(
			&i.UserID,
			&i.Key,
			&i.Value,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertUserSetting = `-- name: UpsertUserSetting :one
INSERT INTO user_setting (user_id, key, value, updated_at)
VALUES ($1, $2, $3, now())
ON CONFLICT (user_id, key) DO UPDATE SET value = $3, updated_at = now()
RETURNING user_id, key, value, updated_at
`

type UpsertUserSettingParams struct {
	UserID int64  `json:"userId"`
	Key    string `json:"key"`
	Value  []byte `json:"value"`
}

func (q *Queries) UpsertUserSetting(ctx context.Context, arg UpsertUserSettingParams) (UserSetting, error) {
	row := q.db.QueryRow(ctx, upsertUserSetting, arg.UserID, arg.Key, arg.Value)
	var i UserSetting
	err := row.Scan(
		&i.UserID,
		&i.Key,
		&i.Value,
		&i.UpdatedAt,
	)
	return i, err
}
