[tools]
go = "latest"
node = "latest"
oapi-codegen = "latest"
pnpm = "latest"
sqlc = "latest"

[env]
_.file = [".env.default", { path = ".env", optional = true }]

[tasks.server]
run = "go run ./cmd/picotera/main.go"

[tasks.web]
run = "pnpm dev"
dir = "dashboard"

[tasks.openapi]
run = "go run ./cmd/picotera/main.go openapi > openapi.yaml"
