packages:
  - dashboard
allowBuilds:
  vue-demi: true

overrides:
  '@vue/compat': '3.6.0-beta.13'
  '@vue/compiler-core': '3.6.0-beta.13'
  '@vue/compiler-dom': '3.6.0-beta.13'
  '@vue/compiler-sfc': '3.6.0-beta.13'
  '@vue/compiler-ssr': '3.6.0-beta.13'
  '@vue/compiler-vapor': '3.6.0-beta.13'
  '@vue/reactivity': '3.6.0-beta.13'
  '@vue/runtime-core': '3.6.0-beta.13'
  '@vue/runtime-dom': '3.6.0-beta.13'
  '@vue/runtime-vapor': '3.6.0-beta.13'
  '@vue/server-renderer': '3.6.0-beta.13'
  '@vue/shared': '3.6.0-beta.13'
  'vue': '3.6.0-beta.13'

peerDependencyRules:
  allowAny:
    - 'vue'

storeDir: ./.pnpm-store
