/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/picotera/api-keys": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List all API keys */
        get: operations["listApiKeys"];
        put?: never;
        /** Create an API key */
        post: operations["createApiKey"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/picotera/api-keys/delete": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Delete an API key */
        post: operations["deleteApiKey"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/picotera/api-keys/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get an API key */
        get: operations["getApiKey"];
        /** Update an API key */
        put: operations["updateApiKey"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/picotera/endpoints": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List all endpoints */
        get: operations["listEndpoints"];
        /** Upsert an endpoint */
        put: operations["upsertEndpoint"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/picotera/endpoints/delete": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Delete an endpoint */
        post: operations["deleteEndpoint"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/picotera/exchange-rates": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List all exchange rates */
        get: operations["listExchangeRates"];
        /** Upsert an exchange rate */
        put: operations["putExchangeRate"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/picotera/exchange-rates/delete": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Delete an exchange rate */
        post: operations["deleteExchangeRate"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/picotera/exchange-rates/{code}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get an exchange rate by code */
        get: operations["getExchangeRate"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/picotera/kv": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List KV entries */
        get: operations["listKvEntries"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/picotera/kv/delete": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Delete a KV entry */
        post: operations["deleteKvEntry"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/picotera/kv/{key}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a KV entry */
        get: operations["getKvEntry"];
        /** Create or update a KV entry */
        put: operations["upsertKvEntry"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/picotera/models": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List all models */
        get: operations["listModels"];
        /** Upsert a model */
        put: operations["putModel"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/picotera/models/delete": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Delete a model */
        post: operations["deleteModel"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/picotera/models/{name}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a model by name */
        get: operations["getModel"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/picotera/overview/distribution": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get overview distribution for a dimension */
        get: operations["getOverviewDistribution"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/picotera/overview/series": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get hourly overview series for a dimension */
        get: operations["getOverviewSeries"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/picotera/overview/speed-boxplot": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get decode speed box plot statistics for a dimension */
        get: operations["getOverviewSpeedBoxplot"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/picotera/overview/summary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get overview summary totals */
        get: operations["getOverviewSummary"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/picotera/pricing/matches": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Match built-in pricing candidates for a model */
        post: operations["matchPricing"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/picotera/projects": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List all projects */
        get: operations["listProjects"];
        /** Upsert a project */
        put: operations["upsertProject"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/picotera/projects/delete": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Delete a project */
        post: operations["deleteProject"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/picotera/projects/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a project by ID */
        get: operations["getProject"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/picotera/provider-endpoints": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List provider endpoints */
        get: operations["listProviderEndpoints"];
        /** Upsert a provider endpoint */
        put: operations["upsertProviderEndpoint"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/picotera/provider-endpoints/delete": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Delete a provider endpoint */
        post: operations["deleteProviderEndpoint"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/picotera/providers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List all providers */
        get: operations["listProviders"];
        /** Upsert a provider */
        put: operations["upsertProvider"];
        /** Create a new provider */
        post: operations["createProvider"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/picotera/providers/delete": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Delete a provider */
        post: operations["deleteProvider"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/picotera/providers/fetch-models": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Fetch model list from upstream provider */
        post: operations["fetchModels"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/picotera/providers/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a provider by ID */
        get: operations["getProvider"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/picotera/providers/{id}/models": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Replace a provider's model list without touching other fields */
        put: operations["updateProviderModels"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/picotera/request-traces": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List request traces */
        get: operations["listRequestTraces"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/picotera/requests": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List requests */
        get: operations["listRequests"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/picotera/requests/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a request by ID */
        get: operations["getRequest"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/picotera/requests/{id}/interrupt": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Interrupt an in-flight request (meta or upstream) */
        post: operations["interruptRequest"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/picotera/requests/{id}/live": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get in-memory live status of an in-flight request */
        get: operations["getRequestLive"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/picotera/requests/{id}/spans": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List spans (meta + upstream) related to a request */
        get: operations["listRequestSpans"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/picotera/scripts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List all scripts */
        get: operations["listScripts"];
        put?: never;
        /** Create a script */
        post: operations["createScript"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/picotera/scripts/delete": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Delete a script */
        post: operations["deleteScript"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/picotera/scripts/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a script */
        get: operations["getScript"];
        /** Update a script */
        put: operations["updateScript"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/picotera/settings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List all global settings */
        get: operations["listGlobalSettings"];
        /** Create or update a global setting */
        put: operations["upsertGlobalSetting"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/picotera/settings/{key}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a global setting by key */
        get: operations["getGlobalSetting"];
        put?: never;
        post?: never;
        /** Delete a global setting */
        delete: operations["deleteGlobalSetting"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/picotera/simulate/dispatch": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Simulate dispatch and return ranked candidates */
        post: operations["simulateDispatch"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        ApiKeyMutateBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/ApiKeyMutateBody.json
             */
            readonly $schema?: string;
            annotations?: {
                [key: string]: string;
            };
            disabled?: boolean;
            key?: string;
            name: string;
        };
        ApiKeyView: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/ApiKeyView.json
             */
            readonly $schema?: string;
            annotations: {
                [key: string]: string;
            };
            createdAt: string;
            disabled: boolean;
            /** Format: int32 */
            id: number;
            key: string;
            name: string;
            updatedAt: string;
        };
        CreateProviderRequestBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/CreateProviderRequestBody.json
             */
            readonly $schema?: string;
            annotations: {
                [key: string]: string;
            };
            credentials: string;
            disabled: boolean;
            /** @enum {string} */
            modelsEndpointResolver?: "unknown" | "generalApiKey" | "bearerToken" | "xApiKey" | "searchKey" | "googApiKey";
            modelsEndpointUrl?: string;
            name: string;
            /** Format: int32 */
            priority: number;
            providerModels: components["schemas"]["ProviderModelEntry"][] | null;
            proxyUrl?: string;
            supportsNativeWebSearch: boolean;
        };
        DeleteApiKeyRequestBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/DeleteApiKeyRequestBody.json
             */
            readonly $schema?: string;
            /** Format: int32 */
            id: number;
        };
        DeleteEndpointRequestBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/DeleteEndpointRequestBody.json
             */
            readonly $schema?: string;
            path: string;
        };
        DeleteExchangeRateRequestBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/DeleteExchangeRateRequestBody.json
             */
            readonly $schema?: string;
            code: string;
        };
        DeleteKvEntryRequestBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/DeleteKvEntryRequestBody.json
             */
            readonly $schema?: string;
            key: string;
        };
        DeleteModelRequestBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/DeleteModelRequestBody.json
             */
            readonly $schema?: string;
            name: string;
        };
        DeleteProjectRequestBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/DeleteProjectRequestBody.json
             */
            readonly $schema?: string;
            /** Format: int32 */
            id: number;
        };
        DeleteProviderEndpointRequestBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/DeleteProviderEndpointRequestBody.json
             */
            readonly $schema?: string;
            endpointPath: string;
            /** Format: int32 */
            providerId: number;
        };
        DeleteProviderRequestBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/DeleteProviderRequestBody.json
             */
            readonly $schema?: string;
            /** Format: int32 */
            id: number;
        };
        DeleteScriptRequestBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/DeleteScriptRequestBody.json
             */
            readonly $schema?: string;
            id: string;
        };
        EndpointView: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/EndpointView.json
             */
            readonly $schema?: string;
            /** @enum {string} */
            credentialsResolver: "generalApiKey" | "bearerToken" | "xApiKey" | "searchKey" | "googApiKey" | "unknown";
            /** @enum {string} */
            endpointType: "general" | "openaiChatCompletions" | "openaiResponses" | "anthropicMessages" | "anthropicCountTokens" | "geminiGenerateContent" | "geminiStreamGenerateContent" | "exaSearch" | "modelList" | "unknown";
            modelPath: string;
            name: string;
            path: string;
        };
        ExchangeRateView: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/ExchangeRateView.json
             */
            readonly $schema?: string;
            code: string;
            name: string;
            symbol: string;
            /** Format: double */
            unitsPerUsd: number;
        };
        FetchModelsRequestBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/FetchModelsRequestBody.json
             */
            readonly $schema?: string;
            /** Format: int32 */
            providerId: number;
        };
        FetchModelsResponseBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/FetchModelsResponseBody.json
             */
            readonly $schema?: string;
            /** Format: int32 */
            providerId: number;
            providerModels: components["schemas"]["ProviderModelEntry"][] | null;
            removedModels: string[] | null;
        };
        GlobalSettingView: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/GlobalSettingView.json
             */
            readonly $schema?: string;
            key: string;
            value: unknown;
        };
        InterruptRequestResponseBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/InterruptRequestResponseBody.json
             */
            readonly $schema?: string;
            interrupted: boolean;
        };
        KvEntryView: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/KvEntryView.json
             */
            readonly $schema?: string;
            key: string;
            /** Format: int64 */
            ttl: number;
            value: string;
        };
        KvMutateBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/KvMutateBody.json
             */
            readonly $schema?: string;
            /** Format: int64 */
            ttlSeconds?: number;
            value: string;
        };
        MatchPricingRequestBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/MatchPricingRequestBody.json
             */
            readonly $schema?: string;
            /** @example claude-sonnet-4-6 */
            targetModel: string;
        };
        MatchPricingResponseBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/MatchPricingResponseBody.json
             */
            readonly $schema?: string;
            candidates: components["schemas"]["PricingMatchCandidate"][] | null;
        };
        ModelView: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/ModelView.json
             */
            readonly $schema?: string;
            annotations: {
                [key: string]: string;
            };
            disabled: boolean;
            name: string;
            pricing?: components["schemas"]["Pricing"];
        };
        OverviewBreakdownRowView: {
            /** Format: int32 */
            apiKeyId: number;
            costs: components["schemas"]["OverviewCostView"][] | null;
            model: string;
            /** Format: int32 */
            projectId: number;
            /** Format: int32 */
            providerId: number;
            /** Format: int64 */
            totalTokens: number;
            upstreamModel: string;
        };
        OverviewCostView: {
            /** Format: double */
            amount: number;
            currency: string;
        };
        OverviewDistributionRowView: {
            costs: components["schemas"]["OverviewCostView"][] | null;
            key: string;
            label: string;
            /** Format: int64 */
            requestCount: number;
            /** Format: int64 */
            totalTokens: number;
            /** Format: int64 */
            traceCount: number;
        };
        OverviewDistributionView: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/OverviewDistributionView.json
             */
            readonly $schema?: string;
            dimension: string;
            rows: components["schemas"]["OverviewDistributionRowView"][] | null;
            window: components["schemas"]["OverviewWindowView"];
        };
        OverviewSeriesGroupView: {
            key: string;
            label: string;
        };
        OverviewSeriesPointView: {
            bucketAt: string;
            currency: string;
            groupKey: string;
            metric: string;
            /** Format: double */
            value: number;
        };
        OverviewSeriesView: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/OverviewSeriesView.json
             */
            readonly $schema?: string;
            buckets: string[] | null;
            dimension: string;
            groups: components["schemas"]["OverviewSeriesGroupView"][] | null;
            points: components["schemas"]["OverviewSeriesPointView"][] | null;
            window: components["schemas"]["OverviewWindowView"];
        };
        OverviewSpeedBoxplotItemView: {
            /** Format: int64 */
            count: number;
            key: string;
            label: string;
            /** Format: double */
            max: number;
            /** Format: double */
            median: number;
            /** Format: double */
            min: number;
            /** Format: double */
            p25: number;
            /** Format: double */
            p95: number;
        };
        OverviewSpeedBoxplotView: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/OverviewSpeedBoxplotView.json
             */
            readonly $schema?: string;
            dimension: string;
            items: components["schemas"]["OverviewSpeedBoxplotItemView"][] | null;
            window: components["schemas"]["OverviewWindowView"];
        };
        OverviewSummaryView: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/OverviewSummaryView.json
             */
            readonly $schema?: string;
            breakdown: components["schemas"]["OverviewBreakdownRowView"][] | null;
            costs: components["schemas"]["OverviewCostView"][] | null;
            tokenBreakdown: components["schemas"]["OverviewTokenBreakdownView"];
            /** Format: int64 */
            totalRequests: number;
            /** Format: int64 */
            totalTokens: number;
            /** Format: int64 */
            totalTraceCount: number;
            window: components["schemas"]["OverviewWindowView"];
        };
        OverviewTokenBreakdownView: {
            /** Format: int64 */
            cacheRead: number;
            /** Format: int64 */
            cacheWrite: number;
            /** Format: int64 */
            cacheWrite1h: number;
            /** Format: int64 */
            input: number;
            /** Format: int64 */
            output: number;
        };
        OverviewWindowView: {
            bucket: string;
            endAt: string;
            range: string;
            startAt: string;
        };
        PaginatedBodyKvEntryView: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/PaginatedBodyKvEntryView.json
             */
            readonly $schema?: string;
            items: components["schemas"]["KvEntryView"][] | null;
            pagination: components["schemas"]["PaginationInfo"];
        };
        PaginatedBodyRequestTraceView: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/PaginatedBodyRequestTraceView.json
             */
            readonly $schema?: string;
            items: components["schemas"]["RequestTraceView"][] | null;
            pagination: components["schemas"]["PaginationInfo"];
        };
        PaginatedBodyRequestView: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/PaginatedBodyRequestView.json
             */
            readonly $schema?: string;
            items: components["schemas"]["RequestView"][] | null;
            pagination: components["schemas"]["PaginationInfo"];
        };
        PaginationInfo: {
            hasMore: boolean;
            nextCursor?: string;
        };
        PicoTeraError: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/PicoTeraError.json
             */
            readonly $schema?: string;
            code: string;
            details: string[] | null;
            message: string;
        };
        Pricing: {
            currency: string;
            tiers: components["schemas"]["PricingTier"][] | null;
        };
        PricingMatchCandidate: {
            /** @example claude-sonnet-4-6 */
            modelId: string;
            /** @example Claude Sonnet 4.6 */
            modelName: string;
            pricing: components["schemas"]["Pricing"];
            /** @example anthropic */
            providerId: string;
            /** @example Anthropic */
            providerName: string;
            /**
             * Format: int64
             * @example 0
             */
            score: number;
        };
        PricingTier: {
            /** Format: double */
            cacheRead: number;
            /** Format: double */
            cacheWrite: number;
            /** Format: double */
            cacheWrite1h: number;
            /** Format: double */
            implicitCacheRead: number;
            /** Format: double */
            input: number;
            /** Format: int64 */
            minInputTokens: number;
            /** Format: double */
            output: number;
        };
        ProjectView: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/ProjectView.json
             */
            readonly $schema?: string;
            createdAt: string;
            firstSeenAt?: string;
            /** Format: int32 */
            id: number;
            lastSeenAt?: string;
            name: string;
            paths: string[] | null;
            updatedAt: string;
        };
        ProviderEndpointView: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/ProviderEndpointView.json
             */
            readonly $schema?: string;
            /** @enum {string} */
            credentialsResolver?: "unknown" | "generalApiKey" | "bearerToken" | "xApiKey" | "searchKey" | "googApiKey";
            endpointPath: string;
            /** Format: int32 */
            providerId: number;
            upstreamUrl: string;
        };
        ProviderModelEntry: {
            annotations?: {
                [key: string]: string;
            };
            disabled?: boolean;
            endpoints?: string[] | null;
            model: string;
            /** Format: int32 */
            priority?: number;
            upstreamModelName?: string;
        };
        ProviderView: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/ProviderView.json
             */
            readonly $schema?: string;
            annotations: {
                [key: string]: string;
            };
            credentials: string;
            disabled: boolean;
            /** Format: int32 */
            id: number;
            /** @enum {string} */
            modelsEndpointResolver?: "unknown" | "generalApiKey" | "bearerToken" | "xApiKey" | "searchKey" | "googApiKey";
            modelsEndpointUrl?: string;
            name: string;
            /** Format: int32 */
            priority: number;
            providerModels: components["schemas"]["ProviderModelEntry"][] | null;
            proxyUrl?: string;
            supportsNativeWebSearch: boolean;
        };
        RequestLiveView: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/RequestLiveView.json
             */
            readonly $schema?: string;
            body?: string;
            /** Format: int64 */
            bytesReceived: number;
            headersReceived: boolean;
            inFlight: boolean;
            kind?: string;
            lastChunkAt?: string;
            phase?: string;
            startedAt?: string;
            /** Format: int64 */
            statusCode?: number;
        };
        RequestTraceView: {
            /** Format: int64 */
            cacheReadTokens: number;
            /** Format: int64 */
            cacheWrite1hTokens: number;
            /** Format: int64 */
            cacheWriteTokens: number;
            firstRequestAt?: string;
            id: string;
            /** Format: int64 */
            inputTokens: number;
            lastRequestAt?: string;
            /** Format: int64 */
            metaRequestCount: number;
            modelCosts: components["schemas"]["TraceCostView"][] | null;
            /** Format: int64 */
            outputTokens: number;
            parentSpanId: string;
            /** Format: int32 */
            projectId?: number;
            /** Format: int64 */
            totalTokens: number;
            /** Format: int64 */
            upstreamRequestCount: number;
            userMessagePreview?: string;
        };
        RequestView: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/RequestView.json
             */
            readonly $schema?: string;
            /** Format: int32 */
            apiKeyId?: number;
            /** Format: int32 */
            cacheReadTokens?: number;
            /** Format: int32 */
            cacheWrite1hTokens?: number;
            /** Format: int32 */
            cacheWriteTokens?: number;
            createdAt?: string;
            endpointPath?: string;
            errorMessage?: string;
            /** Format: int32 */
            finishReason?: number;
            id: string;
            /** Format: int32 */
            inputTokens?: number;
            model?: string;
            /** Format: double */
            modelCost?: number;
            modelCostCurrency?: string;
            /** Format: int32 */
            outputTokens?: number;
            parentSpanId?: string;
            /** Format: int32 */
            projectId?: number;
            /** Format: int32 */
            providerId?: number;
            requestArtifactUrl?: string;
            responseArtifactUrl?: string;
            spanId?: string;
            /** Format: int32 */
            status: number;
            /** Format: int32 */
            statusCode?: number;
            /** Format: int32 */
            timeSpentMs?: number;
            /** Format: int32 */
            ttftMs?: number;
            /** Format: int32 */
            type: number;
            upstreamModel?: string;
            userMessagePreview?: string;
        };
        ScriptMutateBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/ScriptMutateBody.json
             */
            readonly $schema?: string;
            enabled: boolean;
            name: string;
            source: string;
        };
        ScriptView: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/ScriptView.json
             */
            readonly $schema?: string;
            createdAt: string;
            enabled: boolean;
            id: string;
            name: string;
            source: string;
            updatedAt: string;
        };
        SimulateCandidate: {
            bridged: boolean;
            mergedAnnotations: {
                [key: string]: string;
            };
            mpe: components["schemas"]["SimulateMPE"];
            outboundProfile?: components["schemas"]["SimulateOutboundProfile"];
            provider: components["schemas"]["SimulateProviderSummary"];
            upstreamFormat: string;
        };
        SimulateDispatchRequestBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/SimulateDispatchRequestBody.json
             */
            readonly $schema?: string;
            /** Format: int32 */
            apiKeyId: number;
            /** @description Raw JSON request body string. Empty allowed (body omitted from hook context). */
            body: string;
            endpoint: components["schemas"]["SimulateEndpointSelector"];
            model: string;
            /** @description Optional path variable map (used when the endpoint path contains {name} tokens). */
            pathVars?: {
                [key: string]: string;
            };
        };
        SimulateDispatchResponseBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/SimulateDispatchResponseBody.json
             */
            readonly $schema?: string;
            candidates: components["schemas"]["SimulateCandidate"][] | null;
            logs: components["schemas"]["SimulateLogEntry"][] | null;
            originalModel: string;
            resolvedModel: string;
            sourceFormat: string;
            stream: boolean;
        };
        SimulateEndpointSelector: {
            /**
             * @description Unified source format; required when kind==unified.
             * @enum {string}
             */
            format?: "anthropicMessages" | "openaiChatCompletions" | "openaiResponses" | "geminiGenerateContent" | "geminiStreamGenerateContent";
            /**
             * @description "path" picks a configured endpoint row; "unified" picks one of the five unified routes.
             * @enum {string}
             */
            kind: "path" | "unified";
            /** @description Endpoint path; required when kind==path. */
            path?: string;
        };
        SimulateLogEntry: {
            level: string;
            message: string;
            ts: string;
        };
        SimulateMPE: {
            annotations: {
                [key: string]: string;
            };
            endpointPath: string;
            modelName: string;
            /** Format: int32 */
            priority: number;
            /** Format: int32 */
            providerId: number;
            upstreamModelName: string;
        };
        SimulateOutboundProfile: {
            config: {
                [key: string]: unknown;
            };
            type: string;
        };
        SimulateProviderSummary: {
            annotations: {
                [key: string]: string;
            };
            disabled: boolean;
            /** Format: int32 */
            id: number;
            name: string;
            /** Format: int32 */
            priority: number;
        };
        TraceCostView: {
            /** Format: double */
            amount: number;
            currency: string;
        };
        UpdateProviderModelsRequestBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/UpdateProviderModelsRequestBody.json
             */
            readonly $schema?: string;
            providerModels: components["schemas"]["ProviderModelEntry"][] | null;
        };
        UpsertGlobalSettingRequestBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/UpsertGlobalSettingRequestBody.json
             */
            readonly $schema?: string;
            key: string;
            value: unknown;
        };
        UpsertProjectRequestBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/UpsertProjectRequestBody.json
             */
            readonly $schema?: string;
            /** Format: int32 */
            id?: number;
            name: string;
            paths: string[] | null;
        };
        UpsertProviderRequestBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/UpsertProviderRequestBody.json
             */
            readonly $schema?: string;
            annotations: {
                [key: string]: string;
            };
            credentials: string;
            disabled: boolean;
            /** Format: int32 */
            id?: number;
            /** @enum {string} */
            modelsEndpointResolver?: "unknown" | "generalApiKey" | "bearerToken" | "xApiKey" | "searchKey" | "googApiKey";
            modelsEndpointUrl?: string;
            name: string;
            /** Format: int32 */
            priority: number;
            providerModels: components["schemas"]["ProviderModelEntry"][] | null;
            proxyUrl?: string;
            supportsNativeWebSearch: boolean;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    listApiKeys: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiKeyView"][] | null;
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PicoTeraError"];
                };
            };
        };
    };
    createApiKey: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ApiKeyMutateBody"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiKeyView"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PicoTeraError"];
                };
            };
        };
    };
    deleteApiKey: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DeleteApiKeyRequestBody"];
            };
        };
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PicoTeraError"];
                };
            };
        };
    };
    getApiKey: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiKeyView"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PicoTeraError"];
                };
            };
        };
    };
    updateApiKey: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ApiKeyMutateBody"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiKeyView"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PicoTeraError"];
                };
            };
        };
    };
    listEndpoints: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EndpointView"][] | null;
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PicoTeraError"];
                };
            };
        };
    };
    upsertEndpoint: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EndpointView"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EndpointView"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PicoTeraError"];
                };
            };
        };
    };
    deleteEndpoint: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DeleteEndpointRequestBody"];
            };
        };
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PicoTeraError"];
                };
            };
        };
    };
    listExchangeRates: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExchangeRateView"][] | null;
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PicoTeraError"];
                };
            };
        };
    };
    putExchangeRate: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ExchangeRateView"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExchangeRateView"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PicoTeraError"];
                };
            };
        };
    };
    deleteExchangeRate: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DeleteExchangeRateRequestBody"];
            };
        };
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PicoTeraError"];
                };
            };
        };
    };
    getExchangeRate: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                code: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExchangeRateView"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PicoTeraError"];
                };
            };
        };
    };
    listKvEntries: {
        parameters: {
            query?: {
                pattern?: string;
                cursor?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedBodyKvEntryView"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PicoTeraError"];
                };
            };
        };
    };
    deleteKvEntry: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DeleteKvEntryRequestBody"];
            };
        };
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PicoTeraError"];
                };
            };
        };
    };
    getKvEntry: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                key: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["KvEntryView"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PicoTeraError"];
                };
            };
        };
    };
    upsertKvEntry: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                key: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["KvMutateBody"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["KvEntryView"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PicoTeraError"];
                };
            };
        };
    };
    listModels: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ModelView"][] | null;
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PicoTeraError"];
                };
            };
        };
    };
    putModel: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ModelView"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ModelView"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PicoTeraError"];
                };
            };
        };
    };
    deleteModel: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DeleteModelRequestBody"];
            };
        };
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PicoTeraError"];
                };
            };
        };
    };
    getModel: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ModelView"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PicoTeraError"];
                };
            };
        };
    };
    getOverviewDistribution: {
        parameters: {
            query: {
                range: "1d" | "7d" | "1m";
                apiKeyId?: number;
                model?: string;
                upstreamModel?: string;
                providerId?: number;
                projectId?: number;
                dimension: "apiKey" | "model" | "upstreamModel" | "provider" | "project";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OverviewDistributionView"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PicoTeraError"];
                };
            };
        };
    };
    getOverviewSeries: {
        parameters: {
            query: {
                range: "1d" | "7d" | "1m";
                apiKeyId?: number;
                model?: string;
                upstreamModel?: string;
                providerId?: number;
                projectId?: number;
                dimension: "none" | "apiKey" | "model" | "upstreamModel" | "provider" | "project";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OverviewSeriesView"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PicoTeraError"];
                };
            };
        };
    };
    getOverviewSpeedBoxplot: {
        parameters: {
            query: {
                range: "1d" | "7d" | "1m";
                apiKeyId?: number;
                model?: string;
                upstreamModel?: string;
                providerId?: number;
                projectId?: number;
                dimension: "none" | "apiKey" | "model" | "upstreamModel" | "provider" | "project";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OverviewSpeedBoxplotView"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PicoTeraError"];
                };
            };
        };
    };
    getOverviewSummary: {
        parameters: {
            query: {
                range: "1d" | "7d" | "1m";
                apiKeyId?: number;
                model?: string;
                upstreamModel?: string;
                providerId?: number;
                projectId?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OverviewSummaryView"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PicoTeraError"];
                };
            };
        };
    };
    matchPricing: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MatchPricingRequestBody"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MatchPricingResponseBody"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PicoTeraError"];
                };
            };
        };
    };
    listProjects: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectView"][] | null;
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PicoTeraError"];
                };
            };
        };
    };
    upsertProject: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpsertProjectRequestBody"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectView"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PicoTeraError"];
                };
            };
        };
    };
    deleteProject: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DeleteProjectRequestBody"];
            };
        };
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PicoTeraError"];
                };
            };
        };
    };
    getProject: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectView"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PicoTeraError"];
                };
            };
        };
    };
    listProviderEndpoints: {
        parameters: {
            query?: {
                providerId?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProviderEndpointView"][] | null;
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PicoTeraError"];
                };
            };
        };
    };
    upsertProviderEndpoint: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProviderEndpointView"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProviderEndpointView"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PicoTeraError"];
                };
            };
        };
    };
    deleteProviderEndpoint: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DeleteProviderEndpointRequestBody"];
            };
        };
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PicoTeraError"];
                };
            };
        };
    };
    listProviders: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProviderView"][] | null;
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PicoTeraError"];
                };
            };
        };
    };
    upsertProvider: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpsertProviderRequestBody"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProviderView"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PicoTeraError"];
                };
            };
        };
    };
    createProvider: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateProviderRequestBody"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProviderView"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PicoTeraError"];
                };
            };
        };
    };
    deleteProvider: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DeleteProviderRequestBody"];
            };
        };
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PicoTeraError"];
                };
            };
        };
    };
    fetchModels: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FetchModelsRequestBody"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FetchModelsResponseBody"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PicoTeraError"];
                };
            };
        };
    };
    getProvider: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProviderView"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PicoTeraError"];
                };
            };
        };
    };
    updateProviderModels: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateProviderModelsRequestBody"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProviderView"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PicoTeraError"];
                };
            };
        };
    };
    listRequestTraces: {
        parameters: {
            query?: {
                limit?: number;
                cursor?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedBodyRequestTraceView"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PicoTeraError"];
                };
            };
        };
    };
    listRequests: {
        parameters: {
            query?: {
                limit?: number;
                cursor?: string;
                type?: number;
                providerId?: number;
                endpointPath?: string;
                model?: string;
                upstreamModel?: string;
                traceId?: string;
                projectId?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedBodyRequestView"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PicoTeraError"];
                };
            };
        };
    };
    getRequest: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RequestView"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PicoTeraError"];
                };
            };
        };
    };
    interruptRequest: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InterruptRequestResponseBody"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PicoTeraError"];
                };
            };
        };
    };
    getRequestLive: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RequestLiveView"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PicoTeraError"];
                };
            };
        };
    };
    listRequestSpans: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RequestView"][] | null;
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PicoTeraError"];
                };
            };
        };
    };
    listScripts: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScriptView"][] | null;
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PicoTeraError"];
                };
            };
        };
    };
    createScript: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ScriptMutateBody"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScriptView"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PicoTeraError"];
                };
            };
        };
    };
    deleteScript: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DeleteScriptRequestBody"];
            };
        };
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PicoTeraError"];
                };
            };
        };
    };
    getScript: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScriptView"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PicoTeraError"];
                };
            };
        };
    };
    updateScript: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ScriptMutateBody"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScriptView"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PicoTeraError"];
                };
            };
        };
    };
    listGlobalSettings: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GlobalSettingView"][] | null;
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PicoTeraError"];
                };
            };
        };
    };
    upsertGlobalSetting: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpsertGlobalSettingRequestBody"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GlobalSettingView"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PicoTeraError"];
                };
            };
        };
    };
    getGlobalSetting: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                key: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GlobalSettingView"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PicoTeraError"];
                };
            };
        };
    };
    deleteGlobalSetting: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                key: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PicoTeraError"];
                };
            };
        };
    };
    simulateDispatch: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SimulateDispatchRequestBody"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SimulateDispatchResponseBody"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PicoTeraError"];
                };
            };
        };
    };
}
