// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v7.34.1
// source: pkg/llmbridge/llmbridge.proto

package llmbridge

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	LLMBridge_GetInfo_FullMethodName         = "/picotera.llmbridge.v1.LLMBridge/GetInfo"
	LLMBridge_BridgeRequest_FullMethodName   = "/picotera.llmbridge.v1.LLMBridge/BridgeRequest"
	LLMBridge_BridgeNonStream_FullMethodName = "/picotera.llmbridge.v1.LLMBridge/BridgeNonStream"
	LLMBridge_BridgeStream_FullMethodName    = "/picotera.llmbridge.v1.LLMBridge/BridgeStream"
	LLMBridge_AggregateStream_FullMethodName = "/picotera.llmbridge.v1.LLMBridge/AggregateStream"
)

// LLMBridgeClient is the client API for LLMBridge service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type LLMBridgeClient interface {
	GetInfo(ctx context.Context, in *GetInfoRequest, opts ...grpc.CallOption) (*GetInfoResponse, error)
	BridgeRequest(ctx context.Context, in *BridgeRequestRequest, opts ...grpc.CallOption) (*BridgeBodyResponse, error)
	BridgeNonStream(ctx context.Context, in *BridgeNonStreamRequest, opts ...grpc.CallOption) (*BridgeBodyResponse, error)
	BridgeStream(ctx context.Context, opts ...grpc.CallOption) (LLMBridge_BridgeStreamClient, error)
	AggregateStream(ctx context.Context, in *AggregateStreamRequest, opts ...grpc.CallOption) (*AggregateStreamResponse, error)
}

type lLMBridgeClient struct {
	cc grpc.ClientConnInterface
}

func NewLLMBridgeClient(cc grpc.ClientConnInterface) LLMBridgeClient {
	return &lLMBridgeClient{cc}
}

func (c *lLMBridgeClient) GetInfo(ctx context.Context, in *GetInfoRequest, opts ...grpc.CallOption) (*GetInfoResponse, error) {
	out := new(GetInfoResponse)
	err := c.cc.Invoke(ctx, LLMBridge_GetInfo_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *lLMBridgeClient) BridgeRequest(ctx context.Context, in *BridgeRequestRequest, opts ...grpc.CallOption) (*BridgeBodyResponse, error) {
	out := new(BridgeBodyResponse)
	err := c.cc.Invoke(ctx, LLMBridge_BridgeRequest_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *lLMBridgeClient) BridgeNonStream(ctx context.Context, in *BridgeNonStreamRequest, opts ...grpc.CallOption) (*BridgeBodyResponse, error) {
	out := new(BridgeBodyResponse)
	err := c.cc.Invoke(ctx, LLMBridge_BridgeNonStream_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *lLMBridgeClient) BridgeStream(ctx context.Context, opts ...grpc.CallOption) (LLMBridge_BridgeStreamClient, error) {
	stream, err := c.cc.NewStream(ctx, &LLMBridge_ServiceDesc.Streams[0], LLMBridge_BridgeStream_FullMethodName, opts...)
	if err != nil {
		return nil, err
	}
	x := &lLMBridgeBridgeStreamClient{stream}
	return x, nil
}

type LLMBridge_BridgeStreamClient interface {
	Send(*BridgeStreamChunk) error
	Recv() (*BridgeStreamChunk, error)
	grpc.ClientStream
}

type lLMBridgeBridgeStreamClient struct {
	grpc.ClientStream
}

func (x *lLMBridgeBridgeStreamClient) Send(m *BridgeStreamChunk) error {
	return x.ClientStream.SendMsg(m)
}

func (x *lLMBridgeBridgeStreamClient) Recv() (*BridgeStreamChunk, error) {
	m := new(BridgeStreamChunk)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *lLMBridgeClient) AggregateStream(ctx context.Context, in *AggregateStreamRequest, opts ...grpc.CallOption) (*AggregateStreamResponse, error) {
	out := new(AggregateStreamResponse)
	err := c.cc.Invoke(ctx, LLMBridge_AggregateStream_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// LLMBridgeServer is the server API for LLMBridge service.
// All implementations must embed UnimplementedLLMBridgeServer
// for forward compatibility
type LLMBridgeServer interface {
	GetInfo(context.Context, *GetInfoRequest) (*GetInfoResponse, error)
	BridgeRequest(context.Context, *BridgeRequestRequest) (*BridgeBodyResponse, error)
	BridgeNonStream(context.Context, *BridgeNonStreamRequest) (*BridgeBodyResponse, error)
	BridgeStream(LLMBridge_BridgeStreamServer) error
	AggregateStream(context.Context, *AggregateStreamRequest) (*AggregateStreamResponse, error)
	mustEmbedUnimplementedLLMBridgeServer()
}

// UnimplementedLLMBridgeServer must be embedded to have forward compatible implementations.
type UnimplementedLLMBridgeServer struct {
}

func (UnimplementedLLMBridgeServer) GetInfo(context.Context, *GetInfoRequest) (*GetInfoResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetInfo not implemented")
}
func (UnimplementedLLMBridgeServer) BridgeRequest(context.Context, *BridgeRequestRequest) (*BridgeBodyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method BridgeRequest not implemented")
}
func (UnimplementedLLMBridgeServer) BridgeNonStream(context.Context, *BridgeNonStreamRequest) (*BridgeBodyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method BridgeNonStream not implemented")
}
func (UnimplementedLLMBridgeServer) BridgeStream(LLMBridge_BridgeStreamServer) error {
	return status.Errorf(codes.Unimplemented, "method BridgeStream not implemented")
}
func (UnimplementedLLMBridgeServer) AggregateStream(context.Context, *AggregateStreamRequest) (*AggregateStreamResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AggregateStream not implemented")
}
func (UnimplementedLLMBridgeServer) mustEmbedUnimplementedLLMBridgeServer() {}

// UnsafeLLMBridgeServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to LLMBridgeServer will
// result in compilation errors.
type UnsafeLLMBridgeServer interface {
	mustEmbedUnimplementedLLMBridgeServer()
}

func RegisterLLMBridgeServer(s grpc.ServiceRegistrar, srv LLMBridgeServer) {
	s.RegisterService(&LLMBridge_ServiceDesc, srv)
}

func _LLMBridge_GetInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LLMBridgeServer).GetInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LLMBridge_GetInfo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LLMBridgeServer).GetInfo(ctx, req.(*GetInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LLMBridge_BridgeRequest_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BridgeRequestRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LLMBridgeServer).BridgeRequest(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LLMBridge_BridgeRequest_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LLMBridgeServer).BridgeRequest(ctx, req.(*BridgeRequestRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LLMBridge_BridgeNonStream_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BridgeNonStreamRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LLMBridgeServer).BridgeNonStream(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LLMBridge_BridgeNonStream_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LLMBridgeServer).BridgeNonStream(ctx, req.(*BridgeNonStreamRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LLMBridge_BridgeStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(LLMBridgeServer).BridgeStream(&lLMBridgeBridgeStreamServer{stream})
}

type LLMBridge_BridgeStreamServer interface {
	Send(*BridgeStreamChunk) error
	Recv() (*BridgeStreamChunk, error)
	grpc.ServerStream
}

type lLMBridgeBridgeStreamServer struct {
	grpc.ServerStream
}

func (x *lLMBridgeBridgeStreamServer) Send(m *BridgeStreamChunk) error {
	return x.ServerStream.SendMsg(m)
}

func (x *lLMBridgeBridgeStreamServer) Recv() (*BridgeStreamChunk, error) {
	m := new(BridgeStreamChunk)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _LLMBridge_AggregateStream_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AggregateStreamRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LLMBridgeServer).AggregateStream(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LLMBridge_AggregateStream_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LLMBridgeServer).AggregateStream(ctx, req.(*AggregateStreamRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// LLMBridge_ServiceDesc is the grpc.ServiceDesc for LLMBridge service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var LLMBridge_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "picotera.llmbridge.v1.LLMBridge",
	HandlerType: (*LLMBridgeServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetInfo",
			Handler:    _LLMBridge_GetInfo_Handler,
		},
		{
			MethodName: "BridgeRequest",
			Handler:    _LLMBridge_BridgeRequest_Handler,
		},
		{
			MethodName: "BridgeNonStream",
			Handler:    _LLMBridge_BridgeNonStream_Handler,
		},
		{
			MethodName: "AggregateStream",
			Handler:    _LLMBridge_AggregateStream_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "BridgeStream",
			Handler:       _LLMBridge_BridgeStream_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "pkg/llmbridge/llmbridge.proto",
}
